### ISSUE TITLE
no app shortcuts

### ISSUE THREAD

**Issue by madvinegar** [amirzaidi/Launcher3#1]
I installed the v1.1 on my s7edge stock (nougat). All is working great, apart from the following:

i) No app shortcuts when long-pressing an app.
ii) When long-pressing home screen and selecting "wallpapers" instead of the google wallpaper app, I get the stock gallery app of samsung.
iii) Only one option in launcher settings (just permission to rotate home screen).

Keep up the good work!

**Comment by amirzaidi** [comment]
i) You're on Android 7.0, which doesn't support the shortcuts

ii) That has been changed in 1.1, check out the releases tab

iii) I don't want to bloat up the launchers with toggles, I'm aiming to provide just a simple user experience. If you want to change something download the code and build it :)

**Comment by madvinegar** [comment]
Thank you for your reply. 
What about notification badges?

**Comment by amirzaidi** [comment]
They seem to be an Android O Pixel Launcher feature, which has many more changes that will take more work to port. I first want to ensure these N Pixel Launcher features are stable before I'll even look into porting the O features. And there's also the problem that I don't have a Nexus/Pixel myself anymore to test Android O so there is no simple way for me to check if everything is working correctly. When O launches I'm sure Google will push the notification badges to the official AOSP Launcher3 and then I will simply import those.
