### ISSUE TITLE
[FEATURE REQUEST] swipe down to access the notification bar

### ISSUE THREAD

**Issue by raf555** [amirzaidi/Launcher3#102]
i request two features here
swipe down to access the notification bar
and also double tap the launcher to sleep the phone

**Comment by RikKoedoot** [comment]
First one would be nice, idk if it's in pixel launcher tho, second one
isn't, and if you have a fingerprint sensor it will not work anymore if you
enable that

**Comment by AxiK101** [comment]
Look,this is strictly pixel launcher stock experience. No modifications will be added. If you want that, try Lawnchair

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by amirzaidi** [comment]
This feature has been added :)
