### ISSUE TITLE
Not all icons are changing to the round style icon.

### ISSUE THREAD

**Issue by gcladores** [amirzaidi/Launcher3#104]
I have a nexus 6p. Stock rom. But the settings icon and the play games icon are not changing to the round icon

**Comment by gcladores** [comment]
Also the sim toolkit icon not changing

**Comment by amirzaidi** [comment]
That's a "bug" with those apps, they don't have a circle icon.

**Comment by gcladores** [comment]
Oh I see. Well thanks anyways. Everything's great except the icons for these 3 apps. Hopefully there's a fix in the future. If your not too busy.😁

**Comment by amirzaidi** [comment]
The fix would be for Google to add a circle icon to those apps. I am not planning on including any drawables or icon pack support.
