### ISSUE TITLE
Transition to Google Now isn't that smooth

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#106]
(compared to Google Now launcher's swiping)

**Comment by bajankristof** [comment]
Indeed a bit chunky on my Nexus 5X running Oreo, but I think previously when 7.1.2 was installed it was fine! I am glad to send any kind of help if I can, just tell me how. Great launcher btw the best I have ever tried!

**Comment by bajankristof** [comment]
## Description
When you swipe to the Google Now page, there is a slight lag during the transition.
([GPU Profile Video](https://drive.google.com/open?id=0B7-kYmgDUkK6OFBZUjhQcTJsenc))

## Environment
* Device: Nexus 5X
* Android Version: 8.0.0
* Launcher Version: 2.1
* Rom: -

**Comment by nikkomercado** [comment]
@bajankristof Consider yourself lucky. Mine's much worse: https://youtu.be/2UD6LZFMLjI (GPU performance video)
I'm running the launcher on a (kinda) low end device.

**Comment by amirzaidi** [comment]
Are you on the Google App beta? That one gave me severe lag too

**Comment by bajankristof** [comment]
@amirzaidi
I am not on the Google app beta.
I did install the Oreo factory image though, I don't know if that matters.

**Comment by Alez** [comment]
Agree. Lagging on Galaxy s8.
Using launcher3 2.1.
