### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by madvinegar** [amirzaidi/Launcher3#107]
Hi. Now that Android O is out, should we be expecting an updated version of the launcher? (1.6)

**Comment by AxiK101** [comment]
Yes we should. It was a looong wait

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
FYI

https://github.com/amirzaidi/Launcher3/issues/108#issuecomment-324479446

**Comment by Monsieurzik** [comment]
The last on Télégram IS ok with Android 8 ✌️

**Comment by madvinegar** [comment]
Yey !!!!
