### ISSUE TITLE
Android 8 Oreo: no round icons

### ISSUE THREAD

**Issue by zortax** [amirzaidi/Launcher3#108]
On Andoid 8.0 adaptive icons aren't round by default (at least if you don't use a Google Pixel). Also, one should be able to set the adaptive icon shape in the settings.

**Comment by RikKoedoot** [comment]
This app is Made when o was in beta. O is out for a day. No update that day
so he cant Have implemented that
Op di 22 aug. 2017 om 15:20 schreef Zortax <notifications@github.com>

**Comment by amirzaidi** [comment]
If everything goes well I'll release an update tomorrow, I just want to be sure that everything is working now

**Comment by zortax** [comment]
@rickkode just wanted to have that issue open ;D
@amirzaidi nice to hear :D

**Comment by aronfiechter** [comment]
Installed version 2.1 just now, there are some icons that still remain of the wrong shape; also, changing the shapes to teardrop works only for some apps, for example.

(Nexus 6P, Android 8.0 Oreo)

**Comment by suphon-t** [comment]
@Spyridox changing shapes will only work with apps that use adaptive icon.
