### ISSUE TITLE
Page indicator broken

### ISSUE THREAD

**Issue by aronfiechter** [amirzaidi/Launcher3#109]
In the latest release the page indicator on the home just shows a white line over the whole width.

Release: 1.5
Device: Nexus 6P
Android version: 8.0 Oreo (just released)

**Comment by amirzaidi** [comment]
Can you try the latest test build from my Telegram channel @appforks?

**Comment by Monsieurzik** [comment]
In this latest release on Télégram, no Google widget round anymore... Just the Old Google bar rectangular on Nexus 5X. Normal ?

**Comment by RikKoedoot** [comment]
He didnt implement it yet i think
Op do 24 aug. 2017 om 08:45 schreef Jonathan Chevalier <
notifications@github.com>

**Comment by Monsieurzik** [comment]
Seems to work now. I simply do an update of the previous version.

**Comment by aronfiechter** [comment]
I did not install any new version but I cannot reproduce the bug. Now it just works normally.

**Comment by Monsieurzik** [comment]
The last version on Télégram shows notification dots.
