### ISSUE TITLE
Circle icons

### ISSUE THREAD

**Issue by Fadmaestro** [amirzaidi/Launcher3#11]
Been waiting for this Launcher!! The latest one fixed the widget. Excellent work on the fix. 

Anyways wanna ask. The pixel circle icons, it won't work on my op3t? Or does it?

**Comment by amirzaidi** [comment]
No, it uses the AOSP implementation of getting the icons just like the real Pixel Launcher. I don't want to force circle icons upon everyone, switch to a ROM that supports them system-wide if you really want them.

**Comment by RikKoedoot** [comment]
Maybe as an option in the settings

**Comment by dewald-els** [comment]
I wouldn't mind the circle icons. I prefer the coherent look.

**Comment by VincentJoshuaET** [comment]
But the O Pixel Launcher has an in app setting to set the icon mask, right?

**Comment by Fadmaestro** [comment]
Having it as an option will awesome, I agree

**Comment by SethuSenthil** [comment]
@amirzaidi or just add icon pack support and leave the rest to the user if they want to tamper with the settings.

**Comment by alinalihassan** [comment]
We should use the new app icon implementation from O DP3, adaptive icons with user customizable shapes.

**Comment by amirzaidi** [comment]
I am building against API 25 so I cannot do that.

**Comment by akapu1** [comment]
please implement this feature... i think most of the users will appreciate this automatic round icons.

**Comment by dewald-els** [comment]
I think you should just force circle icons. :)

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v1.4

Could you guys try this? It should have the round icon support!

**Comment by akapu1** [comment]
It is working... Thanks very much..! I am so happy now...

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RWOne** [comment]
Sweet!

**Comment by cyberon** [comment]
I'm not getting them on my Stock Nexus 6P. 🤔

**Comment by amirzaidi** [comment]
Clear app cache and if it still doesn't work clear app data.

**Comment by cyberon** [comment]
Fixed clearing app data, thanks.

**Comment by Fadmaestro** [comment]
Thanks man! Keep doing what u are doing!!

**Comment by RikKoedoot** [comment]
Is round icons only for 7.1?

**Comment by amirzaidi** [comment]
No, update to 1.4 and clear app data. Should work on any device.

**Comment by TheOkayMan** [comment]
I get round icons for some apps, Google Books and Play Store, but not with others Google Movies, Music, Chrome. This is with Nexus5x and Android O beta. [Screenshot](http://imgur.com/gallery/CFQB1)

**Comment by P3draum** [comment]
Not work the rounds icons in my Nexus 6P ..

**Comment by RikKoedoot** [comment]
Try clearing appdata

**Comment by blackjetcat** [comment]
Round icons depends on your framework.apk. If you have config.useRoundIcons=true - you will have round icons. If "false" - usual icons. I think that stock Nexus Android and OP3T use "false" parameter. You can use custom ROM for round icons or modify framework by yourself.

**Comment by akapu1** [comment]
@sh0w0ffin It's already been implemented in this launcher..!

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by amirzaidi** [comment]
It uses the round icons for the apps that have one by parsing every app's metadata and loading the round icon manually. So it can load the round icons even when your system has them disabled. However, there is no icon pack in the launcher, so if your apps don't have a round icon at all it won't show.
