### ISSUE TITLE
App quickshortcuts for <7.1

### ISSUE THREAD

**Issue by AxiK101** [amirzaidi/Launcher3#110]
Can u manage that?
Thanks

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by t1m0thyj** [comment]
#44 requested this feature, and the developer said this:
"It's not high on the priority list but I'll see what I can do later"

**Comment by AxiK101** [comment]
On latest beta i think dev backport shortcuts for 7.0 os but i don't get them work. Is it in development still?

**Comment by amirzaidi** [comment]
I haven't uploaded the WIP yet because I haven't had the time to finish the code and make it stable
