### ISSUE TITLE
Transparent circle around folders on 2.0.1 - Should be fixed on 2.0.2

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#116]
A transparent circle appears around the folder hahahahahahah

**Comment by PlugaruT** [comment]
![](http://i.imgur.com/i2GFLL4.jpg)
In the image above can be seen a transparent circle when folder is open.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by amirzaidi** [comment]
Check 2.0.2

**Comment by PlugaruT** [comment]
This is fixed. Thanks a lot for your work.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiva39** [comment]
Send me that link
