### ISSUE TITLE
Can we hide the Google pill?

### ISSUE THREAD

**Issue by lokesh-krishna** [amirzaidi/Launcher3#117]
Thanks for all your work :)

Is there any way you could automatically hide the Google pill on devices without the Google app?

**Comment by genericbar** [comment]
Or make it use the Assistant over Search?

**Comment by amirzaidi** [comment]
Working on the original request, assistant over search is a no

**Comment by amirzaidi** [comment]
Should be working in v2.1

**Comment by cabman133** [comment]
The Google pill isn't working is there a way to turn it on?

**Comment by amirzaidi** [comment]
You need an updated version of the Google app installed
