### ISSUE TITLE
Support for weather with OpenWeatherMap as a provider

### ISSUE THREAD

**Issue by lokesh-krishna** [amirzaidi/Launcher3#118]
Could it be possible to offer OpenWeatherMap as a provider for the weather display like in Lawnchair? Letting users use their own custom API key would help mitigate issues about using up the API quota.

**Comment by RikKoedoot** [comment]
This one uses the One pixel launcher uses. And tht the Google app uses so
its the dame as in the Google app. When you use openweathermap that isnt
the case
Op vr 25 aug. 2017 om 14:10 schreef Noctis <notifications@github.com>

**Comment by lokesh-krishna** [comment]
I know this uses what the Pixel launcher does and that it requires the Google app with the weather card. I am asking if it could be possible to offer OpenWeatherMap as a weather provider. It does make the app more complex but it is just expanding upon an existing feature and lets users who do not have the Google app use that rather nice feature.

**Comment by jleslie97** [comment]
This launcher is solely for implementing and replicating exactly the features the pixel launcher has for non rooted users. 

If you aren't even using Google now. I would usually suggest using a different launcher that's a better fit for purpose. If you want the pixel widget you can get it on any launcher with various weather sources from the play store. Such as the following 3…

https://play.google.com/store/apps/details?id=uk.co.hassie.widget.pixelpill

https://play.google.com/store/apps/details?id=com.vizorg.widget.pix

https://play.google.com/store/apps/details?id=in.accountmaster.pixelwidget

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lokesh-krishna** [comment]
> This launcher is solely for implementing and replicating exactly the features the pixel launcher has for non rooted users. If you aren't even using Google now. I would usually suggest using a different launcher that's a better fit for purpose.  

And it is the replication of one such feature for users not using Google Now that I was requesting. I find this launcher to be the best fit for my purposes due to its dedication to simplicity and minimalism. I see no reason why using Google should be a prerequisite to enjoying it though.

I can close the issue if @amirzaidi  feels that this goes against his vision for the app.
