### ISSUE TITLE
The YouTube app is not have notification dot(version 2.02)

### ISSUE THREAD

**Issue by brunofeng** [amirzaidi/Launcher3#119]
I'm very like this launcher
I see the YouTube is not have notification dot
Please check it

**Comment by shiva39** [comment]
Send me that link

On Aug 25, 2017 5:54 PM, "brunofeng" <notifications@github.com> wrote:

I'm very like this launcher
I see the YouTube is not have notification dot
Please check it

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amirzaidi/Launcher3/issues/119>, or mute the thread

**Comment by brunofeng** [comment]
https://goo.gl/photos/Ho2r1gTzHJsHE25eA
See the image

**Comment by amirzaidi** [comment]
Make sure the app has notification access and then try rebooting your phone - sometimes it doesn't initially work because the app permission wasn't given at the right time

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1, YouTube notification for not working for me either. Screen: https://goo.gl/photos/utjbxQuCuNriDzZc6

I also checked in YouTube App Info and notification dots are enabled.

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/blob/9c947ecfe20a2743b3c133bdb82f3f6054d8a0fe/src/com/android/launcher3/notification/NotificationListener.java#L221

    private boolean shouldBeFilteredOut(StatusBarNotification sbn) {
        Notification notification = sbn.getNotification();
        if (Utilities.isAtLeastO()) {
            getCurrentRanking().getRanking(sbn.getKey(), mTempRanking);
            if (!mTempRanking.canShowBadge()) {
                return true;
            }
            if (mTempRanking.getChannel().getId().equals(NotificationChannel.DEFAULT_CHANNEL_ID)) {
                // Special filtering for the default, legacy "Miscellaneous" channel.
                if ((notification.flags & Notification.FLAG_ONGOING_EVENT) != 0) {
                    return true;
                }
            }
        }
        boolean isGroupHeader = (notification.flags & Notification.FLAG_GROUP_SUMMARY) != 0;
        CharSequence title = notification.extras.getCharSequence(Notification.EXTRA_TITLE);
        CharSequence text = notification.extras.getCharSequence(Notification.EXTRA_TEXT);
        boolean missingTitleAndText = TextUtils.isEmpty(title) && TextUtils.isEmpty(text);
        return (isGroupHeader || missingTitleAndText);
    }

This is my current logic for notification filtering, straight from AOSP other than the isAtleastO check. It might be the YouTube app setting the notification as a group header. If that is the case it won't show, just like in the real Pixel Launcher. I know WhatsApp also weirdly uses the group header flag sometimes causing this bug. If someone had a real Pixel on Android 8 here I could check if it was the app's fault. If you want to disable filtering altogether, fork the code and add a "return false;" at the top of the method ^

**Comment by bkr32** [comment]
dunno if i'm experiencing it alone or it's a known issue, but whatsapp doesn't have notification dots either.
all other tested apps however do
