### ISSUE TITLE
dynamic Google calendar icon

### ISSUE THREAD

**Issue by kici8** [amirzaidi/Launcher3#12]
With the Pixel Launcher, the Google calendar icon changes and displays today's date. Anyway great work!

**Comment by amirzaidi** [comment]
I added that in 1.1 already. Does it not work for you?

**Comment by kici8** [comment]
sorry! It works!

**Comment by Smileline** [comment]
@amirzaidi sorry, how do download 1.1? Where can I see the latest version.

**Comment by kici8** [comment]
@Smileline 
[v1.1](https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v1.1)
[v1.2](https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v1.2)

**Comment by Smileline** [comment]
@kici8 thx
