### ISSUE TITLE
the icon size

### ISSUE THREAD

**Issue by zengjie824** [amirzaidi/Launcher3#121]
the icons on the desktop are bigger than those on the dock

**Comment by amirzaidi** [comment]
Screenshot? This shouldn't be the case

**Comment by zengjie824** [comment]
![screenshot_20170825-234453-01](https://user-images.githubusercontent.com/29570297/29721533-317f23d6-8983-11e7-9b4b-e296b44f0201.jpeg)

I have changed the display size

**Comment by amirzaidi** [comment]
You have set the display size to a value where it's being recognized as a tablet and is using the tablet layout. Consider slightly changing it

**Comment by zengjie824** [comment]
Oh, I see, thanks for everything

**Comment by Aziir** [comment]
Guys can I somehow change number of icons displaying on the dock in this launcher. I have  only 4. My phone - lg g flex 2

**Comment by amirzaidi** [comment]
Decrease dpi/increase display width
