### ISSUE TITLE
Blue app drawer on tablet with v2

### ISSUE THREAD

**Issue by ekerazha** [amirzaidi/Launcher3#122]
With Launcher3 v2, the app drawer background is blue when installed on a tablet, making it unusable.

**Comment by amirzaidi** [comment]
Can you send me a screenshot? and which device is this on?

**Comment by ekerazha** [comment]
@amirzaidi It's a 8-inch Galaxy Tab S2, I don't have the tablet with me now, I can send a screenshot on Monday. However on that device the app drawer background is light blue and the grey icon labels become unreadable on that background color.

**Comment by amirzaidi** [comment]
As far as I know the app drawer background should be hardcoded to oreo colours in colours.xml.. Make sure you are using the latest build and test it again

**Comment by YBogomolov** [comment]
I can provide you with a screenshot, as I have the same tablet. I'm using the latest 2.1 build. Please let me know if you need any further information.

![screenshot_20170826-053653](https://user-images.githubusercontent.com/908865/29737955-9bf205ce-8a20-11e7-9f6e-42659bb82745.png)

**Comment by RikKoedoot** [comment]
I have seen this problem in lawnchair too. Maybe amir can ask deletescape
how he fixed it
Op za 26 aug. 2017 om 04:38 schreef Yuriy Bogomolov <
notifications@github.com>

**Comment by ekerazha** [comment]
@amirzaidi It's the same issue you can see in the screenshot that @YBogomolov posted.

**Comment by thewafflehouse** [comment]
Well chalk up one more with this issue. It exists on a Galaxy Tab S3 running 7.0 as well.

**Comment by amirzaidi** [comment]
So, for some reason, Galaxy tabs manage to override my overriden XML colour.. can any of you check if there is something about partner customization in your system apps list?

**Comment by thewafflehouse** [comment]
Not seeing anything in the Applications -> Show System Apps for anything involving Partner Customization. Is there an easy way to export a list of all System Applications via ADB to output here?

**Comment by bds001** [comment]
Same issue on the 10 inch Galaxy Tab S2.

**Comment by ekerazha** [comment]
@amirzaidi Note that v1 didn't have this issue.

**Comment by amirzaidi** [comment]
Try 1.5, does that have the issue?

**Comment by ullaaaaaaa** [comment]
[
![screenshot_20170830-015748](https://user-images.githubusercontent.com/31434408/29838921-d0eb6474-8d26-11e7-8ced-6b4950e7146f.png)
](url)

This is my Galaxy tab A p355 using 1.5 version

**Comment by amirzaidi** [comment]
So it seems to be an Android 8 launcher sources thing, can you try the official Pixel Launcher?

**Comment by ullaaaaaaa** [comment]
[
![screenshot_20170830-025926](https://user-images.githubusercontent.com/31434408/29841360-58d8df26-8d2f-11e7-82dd-fce76c15dff8.png)
](url)

Its not available on my tab

**Comment by amirzaidi** [comment]
@ullaaaaaaa https://www.apkmirror.com/apk/google-inc/pixel-launcher/

**Comment by ullaaaaaaa** [comment]
![screenshot_20170830-031358](https://user-images.githubusercontent.com/31434408/29841908-5ec410e8-8d31-11e7-9d03-f35c9efe44d9.png)

**Comment by amirzaidi** [comment]
Delete my Rootless Pixel Launcher first @ullaaaaaaa

**Comment by ekerazha** [comment]
@amirzaidi Same bug on the Pixel Launcher from Android 8

**Comment by Eddy69** [comment]
I have the same issue on a brand new Samsung Tab A 2016. Almost unreadable.
