### ISSUE TITLE
Notification Dots issue.

### ISSUE THREAD

**Issue by CristianFulga99** [amirzaidi/Launcher3#124]
Notification Dots does not working on Moto G 2014 with android 7.1.2

**Comment by amirzaidi** [comment]
make sure the app has notification permissions then reboot your phone

**Comment by CristianFulga99** [comment]
It has permission and i reboot many times the phone but not work.

**Comment by amirzaidi** [comment]
Are you actually getting notifications? Which app isn't working?

**Comment by CristianFulga99** [comment]
I've put the app as system app and now everything works well
