### ISSUE TITLE
Icon pack support edited icons to change icons from icon pack 5 icons in transparent dock

### ISSUE THREAD

**Issue by NathanFrederick** [amirzaidi/Launcher3#128]
Add icon pack support add 5 icons in transparent dock add 5 icons to app drawler for each row

**Comment by NathanFrederick** [comment]
Please

**Comment by amirzaidi** [comment]
> add 5 icons in transparent dock add 5 icons to app drawler for each row

Lower your DPI. It already has 5 icons if your dpi is low enough, like for most people.

> Add icon pack support

No
