### ISSUE TITLE
Pixel Launcher Oreo Icons

### ISSUE THREAD

**Issue by AndreHM** [amirzaidi/Launcher3#129]
I would like you to add support for icons the Android O (Square, rounded corner rect, squircle, cylinder) formats for a more pure experience. NOTE: It is not necessary to add support for icons, because by the name of the launcher (pixel launcher) we see that it is not something customizable. In my opinion, it is not necessary to fill it with resources, but rather to delve into the resources of the PIXEL LAUNCHER OF THE ANDROID OREO. :)

**Comment by ashwan** [comment]
Go to the Launcher settings (long press on a home screen and select "Settings") and you will see it already supports the different icon shapes. Apps have to themselves support it though, so not all icons will change.

**Comment by amirzaidi** [comment]
I have this but only on Android 8 because it would be near-impossible to backported adaptive icons

**Comment by AndreHM** [comment]
Okay, I understand, my Android is Marshmallow
