### ISSUE TITLE
unable to see toggles for notification dots/icon shapes

### ISSUE THREAD

**Issue by uicnren** [amirzaidi/Launcher3#130]
As above, am unable to see the toggles to set/change those settings.

Only available setting is to allow home screen rotation.

version: Pixel-v2.1 d199f13
OS: OPR6.170623.013
Nexus 6P

**Comment by amirzaidi** [comment]
Try clearing the app data

**Comment by uicnren** [comment]
unfortunately, all it did was reset everything, still no toggles

**Comment by amirzaidi** [comment]
And you are sure that you are on Android 8? Can you send a screenshot?

**Comment by cavon08** [comment]
Is this coming to previous android versions (nougat in my case) in a coming update?

**Comment by ziv01** [comment]
same issue for me. on O and can't see notification dots setup anywhere.

**Comment by ghost** [comment]
i also wasnt able to see notification dots but after some time they
appeared. this launcher is awesome

**Comment by amirzaidi** [comment]
@cavon08 changing the icon shape is deeply linked with the Android 8 system and adaptive icons. On older versions my launcher will force circle icons.

**Comment by uicnren** [comment]
LOL, yes, Im quite sure, been on every DP build, and now retail.

Also, for the record, not sure if it matters or not, but I also disabled and re-enabled developer settings.

![screenshot_20170826-081146](https://user-images.githubusercontent.com/6878010/29741219-7cde2300-8a36-11e7-80e0-8d11fea9fa84.png)
![screenshot_20170826-081129](https://user-images.githubusercontent.com/6878010/29741220-7ce11c4a-8a36-11e7-87b1-77720aa25a92.png)

**Comment by amirzaidi** [comment]
Are you 100% sure you are using this version: https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v2.1
This is an extremely weird issue I haven't seen before

**Comment by uicnren** [comment]
yep, downloaded from that link yesterday. I will uninstall and try it again with a fresh d/l I suppose

**Comment by uicnren** [comment]
ok, so now, I uninstalled, set google now as default, rebooted, re-downloaded, re-installed. 
different from the install this time than yesterday, for whatever reason, I was prompted to allow notification access to Launcher3, allowed it.

In any case, I now see the toggles and can set/enable them, and they are working.

thank you for the help, and the app!
