### ISSUE TITLE
Cannot add settings shortcut to home screen

### ISSUE THREAD

**Issue by 5haney** [amirzaidi/Launcher3#131]
Brings up the dialogue to select the setting but doesn't appear on screen.

RPL version 2.1
Nexus 5x
Android 8 Oreo

**Comment by amirzaidi** [comment]
Can you take a screen recording and a logcat of this happening?

**Comment by 5haney** [comment]
Actually this seems to only affect the "App info" setting shortcut

**Comment by amirzaidi** [comment]
That's not a regular shortcut, just a general launcher feature. You indeed cannot add that "shortcut", nor the widgets one

**Comment by 5haney** [comment]
I'm not sure I understand, this is an android feature regardless of launcher.
Here is a video of the issue, it shows adding the app info shortcut fails but adding the battery setting is successful

https://drive.google.com/open?id=0B3xLU3JC9m9IVC1sM284d2VueUE

**Comment by amirzaidi** [comment]
I am not sure if this is a bug in my launcher, can you test it in another launcher?

**Comment by 5haney** [comment]
It adds to the screen as expected in Google Now Launcher, Pixel Launcher Lawn chair, Nova and Action.

https://drive.google.com/file/d/0B3xLU3JC9m9IekVrNHpaanVHTnc/view?usp=drivesdk
https://drive.google.com/file/d/0B3xLU3JC9m9ITEJ5ZkIwN0x2bG8/view?usp=drivesdk
https://drive.google.com/file/d/0B3xLU3JC9m9ILUR0YnN5aXgyeHM/view?usp=drivesdk

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1... cannot resemble your issue. Video: https://goo.gl/photos/5QZZyd7vRGoujqZ7A

**Comment by 5haney** [comment]
Strange, I've uninstalled and reinstalled but still getting the same issue.
It appears to be unique to me though so I will consider this closed.

**Comment by 5haney** [comment]
I don't get it, I have done a full factory install of latest Oreo, setup device as new (in case there was some corruption) and still getting this problem and again, only with this launcher.

**Comment by abdullahibneat** [comment]
Have you tried already clearing the RPL (Launcher3) app data and cache from your settings? Also, can you try reverting to your old launcher and launch Rootless Pixel Launcher again (as seen here https://goo.gl/photos/X1defDRCvPkAZfnz6)?

**Comment by 5haney** [comment]
@abdullahibneat yes, those were the first things I tried and like I said, last night I wiped my phone, flashed the Oreo factory image and setup as a new device with no backups.
I just don't understand it at all.

**Comment by abdullahibneat** [comment]
Did you try rebooting you Nexus 5X? That's the same device I own, but I'm unable to replicate your issue.

But have you followed the step on the video (https://goo.gl/photos/X1defDRCvPkAZfnz6) after you flashed the factory image?

**Comment by amirzaidi** [comment]
@5haney can you check if this App Info is already used in any other launcher? 

https://github.com/amirzaidi/Launcher3/issues/162

According to this person removing it from GNL made it work in this launcher

**Comment by 5haney** [comment]
Yes, that has solved the issue for me. Thankyou
