### ISSUE TITLE
Notification access request on boot

### ISSUE THREAD

**Issue by 5haney** [amirzaidi/Launcher3#132]
When notification access is left disabled, it pops up the notification access screen on startup after reboot.

RPL version 2.1
Nexus 5x
Android 8 Oreo

**Comment by amirzaidi** [comment]
Give the app notification access and then disable notification dots through the launcher's settings menu. I intentionally added the prompt on startup to prevent people reporting "notification dots are not working" because they can't enable the permission

**Comment by impreza233** [comment]
I don't have in the launcher settings menu the "disable notification dots" 
Android 7.1.1
BQ Aquaris U Plus
RPL version 2.1

**Comment by 5haney** [comment]
@impreza233 it's called Icon badging

**Comment by impreza233** [comment]
![screenshot_20170826-105818](https://user-images.githubusercontent.com/25793051/29740031-a86d3d28-8a4d-11e7-903a-0eca9f87f348.png)
I don't have that option...

**Comment by 5haney** [comment]
@impreza233 it looks like you may be using the old version?

**Comment by impreza233** [comment]
![screenshot_20170826-111613](https://user-images.githubusercontent.com/25793051/29740156-159a64f0-8a50-11e7-9560-70da04a92344.png)
I have the latest version...

**Comment by ziv01** [comment]
have the latest 2.1 version on oreo and I don't have the 3 dots option and i have granted notification access to the launcher.

**Comment by abdullahibneat** [comment]
Follow these steps: https://goo.gl/photos/JPm66CQpi8U5Xw1c6

**Comment by amirzaidi** [comment]
Yep, that is what I mean, if you are on Android 8 just follow those steps and give the app notification access, it will remove the popup on boot

**Comment by impreza233** [comment]
I don't have Android 8, so, no luck following that steps. I only view the rotation option. Thanks for all the support :)

**Comment by abdullahibneat** [comment]
No worries, we are a community after all ;)

**Comment by impreza233** [comment]
The Launcher works very well on my device, so I assume that this problem is an Android 7.1.1 limitation...

**Comment by abdullahibneat** [comment]
The notification feature was presented with Android Oreo, so definitely a Nougat limitation.

**Comment by impreza233** [comment]
Yes, but I can live happily with it. The Launcher is always in foreground activity, even when I enter in an app  This means that when I return to the Launcher, transitions are super-smooth, with a very low impact on battery life of my phone.

**Comment by abdullahibneat** [comment]
If you're happy, you can now close this issue thread.

**Comment by impreza233** [comment]
With the permission of all, I close this thread....
