### ISSUE TITLE
no launcher setting on my galaxy s7

### ISSUE THREAD

**Issue by nandito10** [amirzaidi/Launcher3#133]
hi amir, first of all thanks for the launcher, i love it so much, but sadly ive got an issue.
as you can see from the attached image, when i hold the home screen and open the launcher setting, there are no settings available, what should i do? 
![screenshot_20170826-094603](https://user-images.githubusercontent.com/31361643/29738036-93007f36-8a43-11e7-835f-ffcd6e4a59df.png)

**Comment by amirzaidi** [comment]
This is normal, the settings you see in the screenshot on Photos are for Android 8 only. However, notification dots and  circle icons should be enabled by default for you too :)

**Comment by nandito10** [comment]
awwww, i thought i could change the icon shape, anyway thanks for your launcher and the answer

**Comment by nandito10** [comment]
is there some ways that i could change the icon shape? or which launcher version that allowed me to do that?

**Comment by amirzaidi** [comment]
It's part of the Android 8 API with the adaptive icons, so you cannot do it until Samsung releases the Android 8 update
