### ISSUE TITLE
Add weather widget.

### ISSUE THREAD

**Issue by Princepritam1994** [amirzaidi/Launcher3#135]
Please add weather info with the clock in homescreen.

**Comment by amirzaidi** [comment]
Sign.. can people please learn to search

Enable location and Google location services, make sure weather in Google Now feed is enabled, refresh the feed twice

**Comment by Princepritam1994** [comment]
Thanks man got it... But I found a major bug. When i create a folder in homescreen and then remove a app fron it by dragging something happened. See it on your device. You will get it what i meant to say.

**Comment by amirzaidi** [comment]
Works completely fine for me, send me a screen recording of this

**Comment by Princepritam1994** [comment]
Where i can send you?

**Comment by amirzaidi** [comment]
Upload it somewhere and put a link in this issue

**Comment by Princepritam1994** [comment]
I had emailed you

**Comment by amirzaidi** [comment]
That's very weird @Princepritam1994 can you give me more information about your setup?

**Comment by Princepritam1994** [comment]
I am using Lenovo k6 power.

**Comment by amirzaidi** [comment]
Android version?

**Comment by Princepritam1994** [comment]
Android 7.0

**Comment by amirzaidi** [comment]
Does the official Pixel Launcher do this?

**Comment by Princepritam1994** [comment]
I haven't tried the official version yet. I love your version very much.

**Comment by Princepritam1994** [comment]
Just checked with the official app. It also happens there.

**Comment by amirzaidi** [comment]
Must be a device specific problem, I've never seen this before. Can you check version 1.5 from my GitHub?

**Comment by Princepritam1994** [comment]
Ya sure
