### ISSUE TITLE
App Drawer is invisible on Android 5.0 (Lenovo A1000)

### ISSUE THREAD

**Issue by fmcgorenc** [amirzaidi/Launcher3#136]
When I drag up the app drawer is invisible /  transparent. At first is visible until I lift my finger. It then becomes invisible.  But when I drag it down a little it becomes visible again.

**Comment by fmcgorenc** [comment]
ps: it's invisible only in portrait mode. Works in lanscape mode.

**Comment by SethuSenthil** [comment]
What skinned version of Android do you use?

**Comment by RikKoedoot** [comment]
Lenovo used zuk ui i think
Op zo 27 aug. 2017 om 17:09 schreef Sethu Senthil <notifications@github.com>

**Comment by fmcgorenc** [comment]
It's stock rooted. This is it http://www.specdevice.com/showspec.php?id=47b7-ba09-f02f-48940033c587
