### ISSUE TITLE
App icon doesn't go away when removed (?)

### ISSUE THREAD

**Issue by Princepritam1994** [amirzaidi/Launcher3#138]
When dragging an app to homescreen the app's icon stay there even if i remove it.. Please fix it.

**Comment by woohooatb** [comment]
what

**Comment by krazyq00** [comment]
I've just added and removed a bunch of icons and had no issue

**Comment by Princepritam1994** [comment]
Try to put a app in folder in the homescreen  and let me know what happened

**Comment by Princepritam1994** [comment]
After creating a folder remove it from folder and then see.

**Comment by uicnren** [comment]
working as expected for me, no issue as described.
to homescreen, or within folder, both drag to and can be removed from without issue.

**Comment by amirzaidi** [comment]
I can't reproduce this, please make a screen recording of this "bug"

**Comment by abdullahibneat** [comment]
Cannot replicate this either on Nexus 5X, Android Oreo (8.0.0) and RPL 2.1

**Comment by uicnren** [comment]
regardless of title, still not seeing the issue

**Comment by Princepritam1994** [comment]
Ok i will make a screen recording but where i can send u @amirzaidi

**Comment by RikKoedoot** [comment]
If you are on Mobile webpage you can request desktop pagina. And then write
what you want. Then there is a paperclip icon that is for attachments
Op zo 27 aug. 2017 om 05:52 schreef Princepritam1994 <
notifications@github.com>
