### ISSUE TITLE
Samsung email and weather widget don't work

### ISSUE THREAD

**Issue by krazyq00** [amirzaidi/Launcher3#139]
The default Samsung email and weather widget aren't showing up.
Anyway to fix this?
Thanks

**Comment by amirzaidi** [comment]
They are probably exclusive to the Samsung TouchWiz launcher

**Comment by krazyq00** [comment]
Ah that sucks
Thanks for the quick reply.
Launcher is awesome otherwise

**Comment by amirzaidi** [comment]
I'm 99% sure they are exclusive because they never showed up on 3rd party launchers on my old S5 either. If you can use them in for example Nova then I might look into it
