### ISSUE TITLE
Widget selection background colour

### ISSUE THREAD

**Issue by dewald-els** [amirzaidi/Launcher3#14]
The widget selection screen still shows teal as the background colour making the white text difficult to read. Not a bug but maybe a possible improvement. :) 

![screenshot_20170613-134354](https://user-images.githubusercontent.com/10051247/27080934-6b2188c8-503e-11e7-9d7d-3530c7d85ba7.png)

**Comment by amirzaidi** [comment]
This is a Samsung problem, because it uses the default system-wide background colour. I could force it into the Pixel colours if more users would like that.

**Comment by dewald-els** [comment]
I see! Thank you for the feedback! :)

**Comment by fishears** [comment]
on stock Android 8 DP3 on my Nexus 5X it looks like this (a bit hard to read):
![screenshot_20170613-134730 resized](https://user-images.githubusercontent.com/909571/27083099-493e6568-503f-11e7-88a8-e1cc6b07c436.png)

**Comment by amirzaidi** [comment]
The easiest solution for me would be to force the Pixel background colours, but I'm not sure if that would make themers happy

**Comment by fishears** [comment]
meh, to be honest I'm just happy to have the swipe-right working. Anything else is truly a bonus - I mean, how often does anybody add a widget?! ;) Great work.

**Comment by amirzaidi** [comment]
I've decided to force the Pixel colours for 1.3 in the widgets view, so stay tuned for that.
