### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mrmanolitos** [amirzaidi/Launcher3#140]
I am new here and I would like to know how to install the launcher 3

**Comment by intelligentcasanova** [comment]
Go to the "releases" section and download the latest .apk file to install.

**Comment by mrmanolitos** [comment]
Thanks

**Comment by david331** [comment]
Where is the releases section?

**Comment by 101164** [comment]
Where is releases located?

**Comment by intelligentcasanova** [comment]
https://github.com/amirzaidi/Launcher3/releases

**Comment by 101164** [comment]
Thank you
