### ISSUE TITLE
Date to weather widget?

### ISSUE THREAD

**Issue by burningDew** [amirzaidi/Launcher3#141]
I'm having this problem for long time and after googling still i can't find any solution. Is there any solution to get the weather instead of the date widget? i've done clearing the cache, data, checking the customize for weather section, but still it showing the date widget.

**Comment by amirzaidi** [comment]
Enable system-wide location and google location services, make sure your Google app is up to date, refresh the google now feed twice and look if the weather card is there. Then check again.

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1, follow amirzaidi's suggestion, and it should work as followed (video cut to not show my location): https://goo.gl/photos/GZwRz4Y1fcbpAVqf8

Basically, clicking on the weather widget opens Google Now to show the weather forecast.

**Comment by burningDew** [comment]
Location, Mode is on High Accuracy.
For location services, there are Google Location History & Google Location Sharing
Google version is 7.10.26.21 (beta)

At Google now feed, there is no weather card. Even after I disabled and enabled it again. So I'm putting the weather icon at home screen, but still, the date widget won't change.

**Comment by abdullahibneat** [comment]
Can you try opening Google Now and search for "weather"? Does it show the weather forecast for your area?

**Comment by burningDew** [comment]
![screenshot_20170827-162404](https://user-images.githubusercontent.com/31372272/29748234-a3624d26-8b44-11e7-929d-51244e4b6465.jpg)
Here is the screenshot when I type the weather at Google Now.

**Comment by abdullahibneat** [comment]
This means the location is working perfectly on your device. Also, reading online other users experienced the same issue, which was solved the day after. Can you try clearing the launcher's app data and cache from the settings and rebooting your device?

**Comment by abdullahibneat** [comment]
Sorry, I meant clearing app data and cache (not location lol)

**Comment by burningDew** [comment]
No luck in clearing cache & data. Even after rebooting, it still didn't change the date to weather.

**Comment by amirzaidi** [comment]
You need the weather card and weather notification. If you don't have those it's an issue in the Google app.

**Comment by burningDew** [comment]
Or is it because i'm using pico gapps? some of the feature not available?

**Comment by amirzaidi** [comment]
Yes. Please use Nano or higher

**Comment by RikKoedoot** [comment]
I get the weather Back in Google now when you Delete data of Google app.
Try that. It May work
Op zo 27 aug. 2017 om 17:59 schreef Amir Zaidi <notifications@github.com>

**Comment by burningDew** [comment]
Problem solved. Flash new rom + nano gapps. Weather card appeared, date changed to weather. Thanks amirzaidi.

**Comment by tsdh** [comment]
Can I also do the inverse? I have the weather widget but would prefer the date widget as a shortcut to the calendar. Or actually I'd prefer having the weather widget opening the default calendar app. I've already removed the weather card from Google Now but that did not help.

**Comment by amirzaidi** [comment]
Disable weather updates in Google Now I guess

**Comment by alecbe** [comment]
In the last 24 hours, after rebooting, both my Nexus 5 and 7 have lost the weather widget. There was no update to the Google app. I suspect this may have been caused by an update to Play Services or maybe a server-side change.

**Comment by alecbe** [comment]
Weird! After several hours use of my Nexus 5, the weather widget has reappeared.
