### ISSUE TITLE
Bad display of icons

### ISSUE THREAD

**Issue by Willet1978** [amirzaidi/Launcher3#142]
Hello,
I have trouble with displaying icons. Right and lower edge are cut off. The problem occurs when i set circle shapes. I did not change the dpi of screen.

Launcher 3 2.1, Nexus 5X, Oreo

![screenshot](https://user-images.githubusercontent.com/31372122/29743208-d66bc6b0-8a8c-11e7-9853-a40209bfddb6.png)

**Comment by amirzaidi** [comment]
Does changing the DPI influence this?

**Comment by Willet1978** [comment]
No, the DPI is default, but if i change size of interface elements in Settings/Display, problem will be resolved. On screen I show situation, when I have default settings.

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1, same, but this is unnoticeable

**Comment by amirzaidi** [comment]
Could you test if the normal Pixel Launcher from apkmirror doesn't have this?

**Comment by abdullahibneat** [comment]
I will try tomorrow, I am going to sleep now (+ 5% battery remaining XD)

**Comment by Willet1978** [comment]
Which version should I install? Pixel Launcher ODR-4023749?

**Comment by abdullahibneat** [comment]
That should be it. Any version would do really.

**Comment by Willet1978** [comment]
Wait. Problem concerns only circle shapes. On Pixel Launcher from XDA at stock Oreo, it is not possible to enable this feature.

**Comment by abdullahibneat** [comment]
Apparently, the stock Pixel Launcher should not have this issue: on XDA, Nexus 5X PixelRom thread, this screen (https://goo.gl/rYNN8X) shows perfectly round icons.

**Comment by amirzaidi** [comment]
@abdullahibneat link is down, could you give me the XDA thread please?

**Comment by abdullahibneat** [comment]
https://forum.xda-developers.com/nexus-5x/development/rom-pixelmod-lg-nexus-5x-t3486862

(End of first post, second screen?

**Comment by amirzaidi** [comment]
Might just be because of the screenshot resolution, if I zoom in it does look like it has the same problem on the bottom of the phone icon. I just think it's an anti aliasing "problem" when sampling for the screen resolution.

I don't want to dismiss it that easily but don't see a proper way to fix this if the vector drawable overlay is a circle..

**Comment by Willet1978** [comment]
Nexus 5X has FHD screen as Google Pixel. Unfortunately I have no idea how to solve the problem.

**Comment by Willet1978** [comment]
I also noticed that Lawnchair doesn't have this problem.

**Comment by ivancuric** [comment]
The icon size is 98% by default on lawnchair. Might be it.

**Comment by Willet1978** [comment]
You're right! When I change icon size to 100%, the problem returned.

**Comment by amirzaidi** [comment]
I'll close it as a vector drawable scale bug then. Don't think I can really fix it. If Lawnchair manages to fix it I'll import the fix :)

**Comment by Willet1978** [comment]
I download your source code, change icon size in the code and build exclusive version specially for N5X :)

For me the problem is solved. Thanks for sharing files!
