### ISSUE TITLE
Wallpaper scaling issue

### ISSUE THREAD

**Issue by Goku003** [amirzaidi/Launcher3#144]
If we are setting wallpaper from other gallery apps 
If we set the wallpaper without changing the position (i mean use as wallpaper and set it without making any modifications like moving left or right anything) will make the wallpaper set correctly that is scaling is proper and scrollable
Izf we make any adjustments while setting the wallpaper then the wallpaper is scaled to portrait size and been set which makes it uglier

**Comment by amirzaidi** [comment]
The launcher is optimized for Google Wallpapers, please install that app and do it through that if you are facing issues. I didn't want to add support for other wallpaper pickers at first but kept it - however, I always recommend using Google Wallpapers.

Can you try if you can reproduce this with Google Wallpapers and if yes send me a screenshot/screenrecording?

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1... using custom background works fine for me. Video: https://goo.gl/photos/JU9vRC4PxLw4ckpR9

**Comment by amirzaidi** [comment]
@abdullahibneat I think the issues are from people not using Google Wallpapers, thanks a lot for the video confirming that it should be working fine through Google Wallpapers

**Comment by abdullahibneat** [comment]
Tried again without Google Wallpapers, still working: https://goo.gl/photos/HNgvxs9knSS15jPS9

**Comment by amirzaidi** [comment]
@itsGoku003 please send a screen recording of this issue.

**Comment by Goku003** [comment]
After using Google wallpaper once,i couldn't repo the same issue using other wallpaper picker
I will let you know if it occurs again

**Comment by Goku003** [comment]
https://goo.gl/photos/GQ9KMiGKa44nPuza7


Here you go
Happens when i move to the left/right most area 
No issue with Google wallpaper

**Comment by abdullahibneat** [comment]
Again, applying a wallpaper from Google Photos I encounter no issue at all: https://goo.gl/photos/RnXXwQXwrbifteYi6

Have you tried clearing app data and cache from setting for Launcher3?

**Comment by Goku003** [comment]
Like i said set the wallpaper by bringing to the left most corner as i showed in the video otherwise there arnt any issue

**Comment by abdullahibneat** [comment]
You didn't mention to put the wallpaper to the far left in any other post... Anyway, I can now confirm this is a bug which is fixed by installing the Google Wallpapers app and setting the wallpaper from there: https://goo.gl/photos/LvtYZDJjP34DGd4e8

**Comment by Goku003** [comment]
Happens when i move to left or right most area

**Comment by abdullahibneat** [comment]
I understand, however if you use Google Wallpapers (as amir has optimised the launcher for this) it works as expected.

**Comment by Goku003** [comment]
Yeah,it works well with Google wallpaper
I just want to let you know becz there were some misunderstanding saying it works well for some and not 
So just want to make it clarify
Anyway great work

**Comment by abdullahibneat** [comment]
All right. If you're happy you may close this issue.

**Comment by Goku003** [comment]
Done
