### ISSUE TITLE
Long-press widget to open app shortcuts

### ISSUE THREAD

**Issue by frandavid100** [amirzaidi/Launcher3#145]
I have a Google Calendar widget on my home screen, and I'd like to be able to long-press it to open its app shortcuts. Right now you can get to the shortcuts from the app's icon, but not from the widget.

Would that be possible?

**Comment by amirzaidi** [comment]
Deviates too much from Launcher3 and sounds like weird UI because long pressing a widget is supposed to make it resize. Thanks for the feature request, but I don't think I will add this.

**Comment by frandavid100** [comment]
Thanks for the quick reply.

Right now long-pressing an app icon merely opens its shortcuts, and the zoom-out animation (which lets you move the icon around, remove it and so on) is only triggered when you actually move the icon.

Maybe you could consider making widgets behave the same way: just open the shortcuts when you long-press them, and only trigger the zoom-out animation (letting you move the widget around, resize it or remove it) when you actually move the widget.

That way all items would behave the same way, which would seem more logical than the current behavior although (admittedly) it would deviate from Launcher3.

However, thank you in advance from considering my suggestion even if you decide against it.

**Comment by amirzaidi** [comment]
What do you suppose should happen if the widget fills the entire page? There would be no space to show the shortcuts popup or it would have to go over the widget. I try to think of all the possible things that can go wrong and prevent as much as possible 😸

**Comment by frandavid100** [comment]
That's a good question... I'm not sure about that, since I've never used widgets like that, but I guess making it show up over the widget would be fine? After all, anyone long-pressing such a widget probably wants to move it, resize it or remove it, which would still be possible and would require basically the same actions it does now.

The only problem I can see with that is closing the shortcut. Let me explain:

Right now, when you long-press an app icon to open the shortcut, you can close the shortcut by clicking anywhere outside the icon itself, which remains active and opens the app when clicked.

In most cases that would also be a desirable behavior for widgets: keep the widget active, and let the user click anywhere outside the widget to close the shortcut. But that behavior would be a problem for widgets filling the whole page, since there is no real space outside the widget.

So, maybe click anywhere, including inside the widget, to close the shortcuts? What do you think?

**Comment by frandavid100** [comment]
Also, yeah, make the shortcuts show up over the widget itself if there's no space for them outside the widget.
