### ISSUE TITLE
No notification dot for Telegram inside the app drawer

### ISSUE THREAD

**Issue by frandavid100** [amirzaidi/Launcher3#146]
When notifications are pending, Telegram shows a notification dot on the home screen but not inside the app drawer.

I have tried disabling and reenabling notification dots, and then restarting the phone, and the problem persists.

**Comment by amirzaidi** [comment]
Can you send a screen recording of this? Never seen this before and I can't reproduce it.

**Comment by frandavid100** [comment]
Sorry, the dot now appears after disabling and re-enabling dots again. I'll send a recording if it happens again.
