### ISSUE TITLE
No recent/most used apps row

### ISSUE THREAD

**Issue by gio1135** [amirzaidi/Launcher3#147]
Why is there no recent/commonly used apps row on the top of the app drawer?

**Comment by AndreHM** [comment]
I'm also interested to know, I miss her.

**Comment by abdullahibneat** [comment]
I can confirm there is no App Suggestion setting in RPL 2.1. I tried activating the option from Google Now settings, however nothing happens. Personally though, I don't find this feature useful (look unaesthetic to me)

**Comment by AndreHM** [comment]
Besides being useful, it makes the launcher more faithful to the original Pixel Launcher

**Comment by gio1135** [comment]
It was so convenient having those apps that I used so often that are at the bottom of the list sitting right there on top.

**Comment by amirzaidi** [comment]
Because the official Pixel Launcher uses a MASSIVE library to do this app suggestion/prediction. I ported it to the Nougat RPL versions but it caused some lag and instability, and it was all obfuscated code. So I decided it wasn't worth keeping and didn't add it. Sorry.

**Comment by ManikandanGuru** [comment]
So, it won't be coming anytime soon?
I miss that feature so much already.
I don't want to scroll all the way down to open Solid Explorer.
Hope you figure this out soon.

**Comment by gio1135** [comment]
Solid Explorer is exactly why.

**Comment by abdullahibneat** [comment]
Unless Google cleans up the code in a future version of the Pixel Launcher, or another open source project finds an easy workaround, we won't see this feature at all.

**Comment by amirzaidi** [comment]
@ManikandanGuru how about adding it to the hotseat or home screen :P

**Comment by gio1135** [comment]
I thought of that, of course, but I have my icons set up just right so that I can see my wallpaper. It was just easier to have those apps on top. Plus, I'm American, I can't handle having to swipe more than once to open an app I use often.

**Comment by ManikandanGuru** [comment]
@amirzaidi I can but I don't want to see that icon in my home screen. If the icons are not circle it's a no no.

**Comment by RikKoedoot** [comment]
Folders are circles

**Comment by amirzaidi** [comment]
Yep, you can add it to a folder for example. I am currently not considering adding it because I know having two versions of the launcher will cause confusion and the app suggestions enabled version will be laggy.
