### ISSUE TITLE
Auto pop-up

### ISSUE THREAD

**Issue by SANJAYSKIM** [amirzaidi/Launcher3#148]
Good launcher but it requires permission for notifications

**Comment by AndreHM** [comment]
Yes, to have the Notification Dot feature implemented from the Android Oreo Pixel Launcher

**Comment by SANJAYSKIM** [comment]
But wallpaper an lock screen and home  screen are not as it said to be

**Comment by SANJAYSKIM** [comment]
I add a widget of feed under Google section but doesn't appear on screen only grey bar is appearing.
Lenovo p2
Android 7.0
July patch

**Comment by RikKoedoot** [comment]
Send a screenshot/recording of what you ment
Op zo 27 aug. 2017 om 03:10 schreef SANJAYSKIM <notifications@github.com>
