### ISSUE TITLE
No app drawer in landscape

### ISSUE THREAD

**Issue by ghost650** [amirzaidi/Launcher3#149]
Using this on nVidia Shield Tablet. In landscape, there is no highlighted box around app dock (on the side) and so nothing to swipe, either up or to the side, to access the app drawer. If I rotate the device the box appears and functions as normal.
![screenshot_20170826-161905](https://user-images.githubusercontent.com/31377131/29745813-51e301f4-8a7a-11e7-9149-0019b4ed2a36.png)

**Comment by suphon-t** [comment]
Swipe up from the bottom bezel.

**Comment by RikKoedoot** [comment]
This is normal. Happens in normal pixel launcher. And a lot of others
Op zo 27 aug. 2017 om 04:11 schreef paphonb <notifications@github.com>

**Comment by ghost650** [comment]
It works as expected (and as the person above indicated) on my Pixel XL: you swipe up from the bottom bezel and it activates the app drawer. On the Shield Tab, however, nothing happens.

Edit: swiping up from the center of the screen works, not the bottom. Not sure if that's intentional or by design.

> This is normal. Happens in normal pixel launcher. And a lot of others
Op zo 27 aug. 2017 om 04:11 schreef paphonb <notifications@github.com>

**Comment by abdullahibneat** [comment]
On my Nexus 5X, Android Oreo (8.0.0) it works from the whole side, not only the center. Could it be because Google didn't initially optimize the Pixel Launcher for tablet devices?

**Comment by RikKoedoot** [comment]
Pixel launcher is on pixel c too i think. You can swipe up from next to the
dock. Or press the arrow
Op zo 27 aug. 2017 om 10:11 schreef Abdullah Ibne Atiq <
notifications@github.com>
