### ISSUE TITLE
No notification dot for Google+

### ISSUE THREAD

**Issue by AndreHM** [amirzaidi/Launcher3#150]
When I get a Google+ notification there is no Notification Dot, neither on the desktop, nor in the drawer

**Comment by SethuSenthil** [comment]
Check issue #119 
Can you also provide more information on what Android you are using and the skin?

**Comment by AndreHM** [comment]
Android Pure Marshmallow 6.0.1

**Comment by amirzaidi** [comment]
Reopen if this is still a bug, and it does work on the real Pixel Launcher.
