### ISSUE TITLE
Is this working for Mate 9? 

### ISSUE THREAD

**Issue by pauljohnabdon** [amirzaidi/Launcher3#151]
Is this launcher working with mate 9? Yeah, it works but I only get 1 setting under "Settings" of this launcher, which is Auto Rotate Wallpaper. That's all. No other option to change icons, or any other features listed. Please let me know if this is really compatible with Mate 9 running 7.0.

I'm new to this launcher so I don't know. Will go back to Nova for now.

**Comment by pauljohnabdon** [comment]
Correction
It's "Allow home screen rotation" not wallpaper rotation.

**Comment by pauljohnabdon** [comment]
![screenshot_20170827-091446](https://user-images.githubusercontent.com/31378226/29746423-735f751e-8b0c-11e7-8fdc-f13c7c1136fa.png)

**Comment by suphon-t** [comment]
Other options are for Android 8 only.

**Comment by abdullahibneat** [comment]
Since the Pixel Launcher is officially available for android nougat and Oreo, all settings are implemented for those 2 android versions. I imagine you aren't running your device on Android Nougat or Oreo.

**Comment by abdullahibneat** [comment]
Correction: Pixel Launcher is available from Android 7.1+, if you update your device to at least this version you should get the options I suppose...

**Comment by RikKoedoot** [comment]
All oprions are on by default
Op zo 27 aug. 2017 om 10:04 schreef Abdullah Ibne Atiq <
notifications@github.com>

**Comment by pauljohnabdon** [comment]
I only have 7.0. I thought this is available for all Nougat Version. Thanks anyway. Will just stay with Nova and will wait for their Oreo update for Nova.

**Comment by udozockt** [comment]
As far as I know is the icon feature an Android Oreo feature. I 've upgraded my Nexus 5x from Android 7 to Android 8 today. With Android 7 I got one setting under "Settings", with Android 8 there are more settings including the icon settings.

**Comment by abdullahibneat** [comment]
Have you had a look at [Lawnchair](https://github.com/Deletescape-Media/Lawnchair/releases)? That might solve the issue for now. But you're free to stay with Nova if you want :) .

**Comment by amirzaidi** [comment]
@pauljohnabdon the settings menu is normal, there's nothing to customize before Android 8.

> No other option to change icons

They're all forced into Pixel circles (when available) before Android 8

> or any other features listed

Notification dots are working on Android 7.0, there is just no way to DISABLE them
