### ISSUE TITLE
Sk

### ISSUE THREAD

**Issue by sadisd** [amirzaidi/Launcher3#152]
Need to make Force all apps to have rounded icon's like Pixel device,without it desktop looks a mess

**Comment by suphon-t** [comment]
Round icons will be used on apps that support round icons.

**Comment by sadisd** [comment]
But isn't there anyways to force all icons to have a round background?

**Comment by abdullahibneat** [comment]
You'll have to use a launcher with a circle icon pack. As amirzaidi said in Issue #11 (https://github.com/amirzaidi/Launcher3/issues/11):

"It uses the round icons for the apps that have one by parsing every app's metadata and loading the round icon manually. So it can load the round icons even when your system has them disabled. However, there is no icon pack in the launcher, so if your apps don't have a round icon at all it won't show."

**Comment by sadisd** [comment]
thanks for the feedback :)
