### ISSUE TITLE
why not publish in Play Store

### ISSUE THREAD

**Issue by steelbytes** [amirzaidi/Launcher3#153]
why not publish in Play Store?

**Comment by eaingaran** [comment]
It has the same package name as Google's Pixel Launcher. I don't think play store will accept to publish this app.

**Comment by impreza233** [comment]
Impossible to publish. The rules on Play Store say that apps with the same package name as existent apps are forbidden.

**Comment by amirzaidi** [comment]
The comments above are right, and I also answered this in my Reddit FAQ.

**Comment by steelbytes** [comment]
so why use the same package name?

I ask this as if I wanted to actually use your launcher I would have to manually install updates instead of letting Play Store take care of it.

**Comment by amirzaidi** [comment]
I need the package name to display the weather widget and I need the debug variant to use the Google now panel rootlessly. It's all in the FAQ
