### ISSUE TITLE
How to download apk from GitHub ????

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#154]
Cannot see any apk in the files .

**Comment by burningDew** [comment]
seriously man? u can't find it at Release?

https://github.com/amirzaidi/Launcher3/releases/download/Pixel-v2.1/Launcher3-aosp-debug.apk

**Comment by johndoe422** [comment]
Yes, there is no download page / link here. Many people come to this link from blogs and they can't find the download link.

**Comment by abdullahibneat** [comment]
amir, can I suggest you to add a README file so you can add a bit of description for this launcher and place a link to the release section?

**Comment by abdullahibneat** [comment]
Issue #33

**Comment by johndoe422** [comment]
Common problem with github.com. The project page won't have any links or info as to where can the binaries be downloaded from.

**Comment by abdullahibneat** [comment]
@amirzaidi  I've created a pull request for the README.md file (pull #157 ). Please look into it

**Comment by Keksilton** [comment]
Releases page: https://github.com/amirzaidi/Launcher3/releases
All versions are there.

**Comment by Keksilton** [comment]
@burningDew it could be hard if you are not familiar with GitHub and you are using mobile version.

**Comment by SethuSenthil** [comment]
If words can't explain it, here is an [image](https://goo.gl/photos/rkToCsdtZzLGVGKU7) and please close this silly issue, the developers have **real** bugs and features to fix.

**Comment by johndoe422** [comment]
It is hard to find the page to download it. And after downloading, it won't install - says package appears to be corrupt.

**Comment by abdullahibneat** [comment]
That's because you need at least Android 5

**Comment by johndoe422** [comment]
Lol. I'm on Android 7.1.2.

**Comment by abdullahibneat** [comment]
That's odd. Can you download it again? Also, do you have any other Pixel Launcher installed? If so, remove that first and install amir's version.

**Comment by johndoe422** [comment]
I downloaded it again and same issue. That's when it struck me, I am using lawnchair launcher and I also have the pixel launcher that came with my OS, Resurrection remix.

**Comment by abdullahibneat** [comment]
That's the issue. Can you try removing Lawn chair and install this instead? That should do the trick

**Comment by amirzaidi** [comment]
The last part is the problem. Lawnchair doesn't interfere with my launcher.

**Comment by johndoe422** [comment]
So I removes lawnchair and tried installing this launcher but couldn't. I don't want to remove pixel launcher because that's part of the system (I have root and can remove, but don't want to do). It would have been helpful if this launcher was like lawnchair, whichever co-exists with pixel launcher.

**Comment by amirzaidi** [comment]
I can't do that, I need to claim the Pixel Launcher package name to provide the weather widget (without implementing my own which is what Lawnchair does). So sorry but you won't be able to install it unless you remove the normal Pixel Launcher.
