### ISSUE TITLE
Notification bar invisible when app drawer opens

### ISSUE THREAD

**Issue by hahalia** [amirzaidi/Launcher3#155]
The time,date and notification bar is invisible when I open the App Drawer. I've attached a screenshot to specify the problem.
I'm running Android 5.0.1 on an Acer Liquid z630s
![screenshot_2017-08-27_094753](https://user-images.githubusercontent.com/31379924/29747142-30fb4d6a-8adf-11e7-8172-01758923ddbb.jpg)

**Comment by OwenHunter** [comment]
its not invisible but because it's white on a white app drawer (background) then you cannot see it easily

**Comment by amirzaidi** [comment]
Android 6 lacks the API for the dark status bar so this is indeed what happens. Sorry but it's a limitation of the system. One fix would be to add a dark bar underneath it, but not sure if that is a proper solution
