### ISSUE TITLE
Small Fonts in Launcher

### ISSUE THREAD

**Issue by studio-suman** [amirzaidi/Launcher3#156]
Thanks a lot for a awesome launcher, if we can get some customisation of having small icons will be really great, including google search in Home Page

**Comment by abdullahibneat** [comment]
On some devices, if you go to Settings -> Display, you can find an option to set the Font Size. Trying this on Nexus 5X, Android Oreo (8.0.0), RPL 2.1, I can see that the setting impacts the Font of the launcher (not the icons')

**Comment by studio-suman** [comment]
Thanks a lot mate, but if we can have options to reduce icons size will be really great

**Comment by PlugaruT** [comment]
@studio-suman this launcher is the closest to the Pixel Launcher and from my understandings the dev wants to keep it this way, which is good. For more customisations there is Lawnchair which can do a lot of stuff... including changing icon sizes.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abdullahibneat** [comment]
More info [here](https://github.com/Deletescape-Media/Lawnchair)

You can close the issue if you're happy.

**Comment by studio-suman** [comment]
Sure thank you.. appreciate the response to the query. Cheers it's a good application and thumbs up!!

**Comment by abdullahibneat** [comment]
Quick update: it looks like if you enlarge your display settings (you might not have these settings) it scales up the icons too! (https://goo.gl/photos/39dAAt3r2YNv4w6u9)

The downside is that every app will be scales up, not just the icons in the launcher.

**Comment by amirzaidi** [comment]
Yep, play around with font size and display size to find a setting you like. The XML is exactly the same as the Pixel Launcher and I won't change that.
