### ISSUE TITLE
Moto G4

### ISSUE THREAD

**Issue by amer4rock** [amirzaidi/Launcher3#158]
Basic Buttons are not in Pixel Style & No Access to Settings from Home screen.

**Comment by abdullahibneat** [comment]
What do you mean by "Basic Buttons" (post a screenshot or use a screen recorder)? If you long-press on an empty space in the desktop, are you able to access the launcher settings?

**Comment by amer4rock** [comment]
Sorry, I mean Home (Navigation) Buttons. The ones we operate with [Triangle, Circle, Square].
In Pixel they're Filled in & mine are Plane.

**Comment by amer4rock** [comment]
![screenshot_20170827-155318-01](https://user-images.githubusercontent.com/31383788/29749012-28aaa4ec-8b40-11e7-896b-df1d225817de.jpeg)
These Buttons

**Comment by amer4rock** [comment]
![screenshot_20170827-155325-01](https://user-images.githubusercontent.com/31383788/29749016-3d2c058c-8b40-11e7-9495-e91aabf6d22a.jpeg)

After Long Pressing on Homescreen; Settings; Rest of the Options are not Visible, like Icon Type etc.

**Comment by abdullahibneat** [comment]
The pixel launcher **does not** change the navigation buttons _(triangle, circle and square)_. For that, you may use Substratum. Also, you can only see those options because you don't have Android Oreo (all other options are related to notification dots and shape of icons, which have been introduced in Android Oreo).

**Comment by amer4rock** [comment]
Thanx anyways. But One of the Videos Showed some Buttons & a Link to here.

I thought you can fix this
This Link [https://youtu.be/sQ7GkmoIuTQ](url)

**Comment by abdullahibneat** [comment]
At this minute: https://youtu.be/sQ7GkmoIuTQ?t=2m13s You can see the Google Pixel on the left and Nexus 6P on the right. On the Nexus 5X, you can see he installed an app called "Custom Nav". My guess is that he used this app to fill the navigation buttons.

**Comment by amer4rock** [comment]
Okay. Thank You so much.

Didn't mean to lower the Gratitude 😀 but Honestly, must confess "Of all the Launchers yours is the best1. As the other Launchers lack Google Now access from Homescreen."

Unless you Planted a Malware 😉😆😝😝😝 LoL

**Comment by abdullahibneat** [comment]
Well, the good thing about this launcher is that is **open source**, meaning anyone can check the code [here](https://github.com/amirzaidi/Launcher3) and analyse it for any malicious code.

**Comment by amer4rock** [comment]
Just Kidding


Thank You so much for the Support...!!👏👍
Good Luck

**Comment by abdullahibneat** [comment]
I know you're kidding, but some people do actually think about this.

You can close this issue if you're happy.

**Comment by SethuSenthil** [comment]
Try this [app](https://play.google.com/store/apps/details?id=com.axndx.prithvee.pixelnavbar&hl=en)
