### ISSUE TITLE
Google Calendar icon does not update

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#159]
Google Calendar icon does not update at 0:00 as expected, and maintains last day date.

My device is a 2015 Samsung Galaxy A5 (model SM-A500FU) with Android 6.0.1 Marshmallow (not rooted).

**Comment by abdullahibneat** [comment]
What happens at 00:01? Also, does this mean at this moment it shows 26 instead of 27?

**Comment by ghost** [comment]
Yesterday I waited until 02:00 AM, and last day date remained (26 instead of 27). This morning the date was correct, but could be because I have programmed my Galaxy to automatic restart all sundays at 05:00 AM.

**Comment by amirzaidi** [comment]
It might have to do with the time your device sends out the "date changed" intent, that's when the launcher updates the icon. Once I get home I'll double check if the Intent is properly implemented

**Comment by abdullahibneat** [comment]
So, it's now midnight, and the icon changed immediately: https://goo.gl/photos/xJACJDAQSKiSyM4T6

**Comment by ghost** [comment]
Yeah, today Google Calendar icon changed immediately at midnight and now shows correct date. I will check in the next few days if it continues to work the same.

Certainly with Samsung smartphones you never know what's going to happen.

My congratulations for the excellent job you're doing with this fork of Pixel Launcher.

**Comment by abdullahibneat** [comment]
Glad to hear that. You may close the issue for now.
