### ISSUE TITLE
Pixel Accent Color

### ISSUE THREAD

**Issue by GitHub-Varun** [amirzaidi/Launcher3#16]
Thanks so much, Amir, for the launcher.  I see that you have mentioned the latest version forces the Pixel accent color throughout the app, instead of the default teal.
I installed it on my Nexus 6P(unrooted, running 7.1.2) & noticed that the accent color is changed to blue only in the app drawer and the rest (settings..) still in teal. 
Could you please take a look or let me know if I am missing something here?

**Comment by amirzaidi** [comment]
No, I only changed it for the app drawer and widget scrollbar. I'm still looking on whether I should port all the colours or leave it as it is, I don't want to stray too far from AOSP's implementation.

**Comment by GitHub-Varun** [comment]
All right. Thanks for your response.

**Comment by amirzaidi** [comment]
How's 1.3?

**Comment by GitHub-Varun** [comment]
Thank you! Just installed the latest version & got the round icons too. 
Bravo!!

**Comment by RikKoedoot** [comment]
What Android version do you have with the round icons?

**Comment by amirzaidi** [comment]
Should work on any version (5+)
