### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by mischugo** [amirzaidi/Launcher3#160]
Starting the installation of the apk-file give me a pop up du udate the existing launcher.
I do that, but then i got a message that the package is defect :-(

MI6

**Comment by mfelipec** [comment]
Same problem

**Comment by ecklf** [comment]
Remove the existing pixel launcher first and reinstall from scratch.

**Comment by mischugo** [comment]
Thanks, it works.

**Comment by abdullahibneat** [comment]
If you're happy, you may close the issue.
