### ISSUE TITLE
Notification dots does not work in Samsung app for SMS 

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#161]
When I receive a new SMS, Samsung app for SMS (does not show notification dot nor notification preview after holding down icon. This also happens with Samsung Internet app when I receive a notification, but only sometimes.

**Comment by abdullahibneat** [comment]
Check issue #139

**Comment by SethuSenthil** [comment]
Yes, check issue #139 (basically it could not be done) instead try using Googles own SMS client called [Android Messages](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging&hl=en)

**Comment by ghost** [comment]
Okay, thanks for the reply. I've tried out with the Google Messages app and notification dots works. Curiously, notification dots works with Samsung Internet browser, but only sometimes.
