### ISSUE TITLE
Settings widget does appear on home screen

### ISSUE THREAD

**Issue by Chedi07** [amirzaidi/Launcher3#162]
Settings widget appears only for WiFi, Data usage & Battery. If I choose anything else the widget does not appear on the home screen.

**Comment by abdullahibneat** [comment]
Check issue #131

**Comment by Chedi07** [comment]
Checked issue #131. For me 'App Info' is visible as a setting widget but when I select 'Display' the widget is not created. I followed the steps mentioned in issue #131, still din't solve the problem.

**Comment by abdullahibneat** [comment]
I tried random settings as shown here: https://goo.gl/photos/J4jd5LLC1uB6Vq3u8

I'm running Android Oreo (8.0.0) on Stock Nexus 5X, and with the latest version of Rootless Pixel Launcher (2.1) I encounter no issues. Can you give more details about your device?

**Comment by Chedi07** [comment]
Resolved. While using Google Now launcher I had placed the display setting widget on my home screen. I switched to Google Now launcher removed the settings widget, switched to Rootless Pixel Launcher and voila now the display setting widget appears on the screen.
Thanks for the support & btw this is a kick-ass launcher 👍

**Comment by Chedi07** [comment]
I'm running Android Oreo (8.0.0) on Stock Nexus 6P, and with the latest version of Rootless Pixel Launcher (2.1)

**Comment by abdullahibneat** [comment]
Weird, but good find!

**Comment by 5haney** [comment]
Fantastic. That fixed it for me also.
