### ISSUE TITLE
Full HD icons get serrated

### ISSUE THREAD

**Issue by AndreHM** [amirzaidi/Launcher3#163]
I changed the icon of an app that I have installed, and the icon is in Full HD and it stays serrated, it is not perfectly round like the others.

**Comment by SethuSenthil** [comment]
Since you have changed the icon of the app manually, you have overridden the default icon settings.

**Comment by AndreHM** [comment]
But the icon is only serrated on this launcher

**Comment by amirzaidi** [comment]
Upload a screenshot please

**Comment by AndreHM** [comment]
![image](https://user-images.githubusercontent.com/31327537/29751470-156ee71a-8b24-11e7-8d50-dd12f696760d.png)

**Comment by amirzaidi** [comment]
That does indeed look horrible, does the normal Pixel Launcher not have that bug?

**Comment by AndreHM** [comment]
Wow how strange, I noticed that only in the Google launchers (Google Now and Google Pixel Launcher) the icon is serrated.

**Comment by amirzaidi** [comment]
Might be because they downscale the icon to preserve RAM. My Launcher is based on Oreo Launcher3 sources so it will basically work identical to the real Pixel Launcher.

**Comment by AndreHM** [comment]
I understand, it's a shame that it gets a little jagged, sometimes it bothers, but it's kind of pointless to worry about it
