### ISSUE TITLE
Tapping on date doesn't open calender

### ISSUE THREAD

**Issue by isaumya** [amirzaidi/Launcher3#164]
Hi,
In Reddit you have mentioned that "Pressing the date widget opens the default calendar app". But I'm unable to do this. Whether I tap on the current weather or the date it always opens up the weather. Do you have any idea what is causing this? Also I've seen one more thing. After installing the launcher I've seen it is showing dot badge for a few apps. but when I long pressed on them there is no notification. So, I left it like that and after few time it went away automatically.

Looking forward to your reply.

**Comment by SethuSenthil** [comment]
What calendar app do you use?

**Comment by ctt1wbw** [comment]
I was going to ask this as well.  I just installed it on my BlackBerry KEYone and it runs super super fast and fluid.  I wasn't sure if I was doing something wrong or not either.

**Comment by isaumya** [comment]
@SethuSenthil Google Calendar (the latest version)

**Comment by amirzaidi** [comment]
Which Android version?

**Comment by isaumya** [comment]
@amirzaidi Android 7.1.1 OnePlus 5 Midnight Black.

**Comment by SethuSenthil** [comment]
Did you set a default calendar app?

**Comment by isaumya** [comment]
@SethuSenthil There is only one calendar app. No other calendar app is present.

**Comment by isaumya** [comment]
Also I've tried uninstalling and reinstalling the launcher. Now rebooting the phone also just to check.

**Comment by SethuSenthil** [comment]
Hmmm... That's a bit odd, did you set the launcher as default? Yes, restart the phone idk if it will help but its worth a try.

**Comment by isaumya** [comment]
Restarted my phone. At the beginning. There was just the date no weather as the weather data takes a few second to update. At that time when I clicked on the date, it opened calendar but then the weather data came and again the same thing. Clicking on the weather opens weather details but clicking on the date or the day doesn't do anything.

**Comment by amirzaidi** [comment]
Ohhhhh yes that's normal, the small date under the weather is provided by the Google App and thus doesn't open the date

**Comment by isaumya** [comment]
Ohk. When you said "Pressing the date widget opens the default calendar app", I thought that's what it's gonna do. Is this same for pixel devices as well? Sorry, I don't have a pixel device to test it that's why asking.

**Comment by amirzaidi** [comment]
Pixel devices don't open the calendar at all. I added opening the calendar when the weather is NOT shown

**Comment by isaumya** [comment]
Thanks a lot for the info. May be in future you can add the same feature for the small date as well. Just a small feature request. Thought I know that in the FAQ you have clearly mentioned that you don't like to take feature requests, but still said.

Anyways one last question, which is also off topic also. Can you please let me know how can I subscribe to this repo so that everytime you push a new release tag I can get an email. I'm already watching and starring this repo since v1 but when you pushed v2 I didn't any email notification. So thought I better ask if you know.

**Comment by amirzaidi** [comment]
I'm not sure about getting an e-mail for every release, I am not that familiar with the GitHub subscription system, but for now I plan to focus on other things anyways. 2.1 seems to be working great without any real bugs so I won't be making a new update for a while. If you see another "Rootless Pixel Launcher" in the Android news again the new update is out ;)

**Comment by isaumya** [comment]
Awesome reply..... :) Keep up the good work man.... Really appreciate it.

**Comment by SethuSenthil** [comment]
Hmmm, after thinking about this for a while, I figured out how to send notifications from our upcoming website, using GSM, or Web Push API's automatically! This will be live soon!
