### ISSUE TITLE
Notification Dot Bug

### ISSUE THREAD

**Issue by AndreHM** [amirzaidi/Launcher3#166]
When I delete a notification from the status bar, the Notification Dot of the app in Drawer does not disappear, that is, it continues to show the Polka Dot, and shows no notification

**Comment by amirzaidi** [comment]
Works fine here, which Android version?

**Comment by AndreHM** [comment]
Android Marshmallow 6.0.1

**Comment by AndreHM** [comment]
After a certain time (approximately 20 minutes), the ball disappears

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1, everything works fine: https://goo.gl/photos/JoRPJCgcFxXXXBZ68

**Comment by AndreHM** [comment]
Here only happened once with the Google App and another with Gmail

**Comment by abdullahibneat** [comment]
Could you be more clear? Is the issue only happening on certain apps or all of them?

**Comment by AndreHM** [comment]
Sorry, I'll explain, it already happened to the Google App when I cleared the weather notification, and now it happened to Google+. It's a ball still in the app, but only by the drawer. Then after about 20 minutes it goes off alone.

**Comment by AndreHM** [comment]
Strangely, it's not always the case, I've received other Google+ notifications and cleared the status bar to see if it bugged again, but it did not bug me.

**Comment by AndreHM** [comment]
It's a random bug

**Comment by abdullahibneat** [comment]
Well, so far I didn't notice that bug... As soon as I swipe out a notification, the dot disappears (like in the video I made). Could it be because you're not on Android Oreo? Because this function has been backported, I would expect some bugs.

**Comment by AndreHM** [comment]
Yes, my device will soon receive the Android Nougat, so I'll see if the bug will remain.

**Comment by abdullahibneat** [comment]
If you are happy, you may close this issue.

**Comment by AndreHM** [comment]
Thanks
