### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by ggkameleon** [amirzaidi/Launcher3#167]
Hi ! I had a custom rom in my OnePlus 3 name FreedomOs and I had Pixel Launcher install in system app and when I want install your pixel launcher said do you want to update it I click install but won't install.

**Comment by abdullahibneat** [comment]
That's the problem: you already have the Pixel Launcher installed. This version uses the same package name as the Pixel Launcher, so your device is detecting this as an update while it's a completely different app. The only way to solve this is either:

1) Revert to stock firmware, this way Rootless Pixel Launcher will not cause any problems during the installation;

2) Install a different ROM which doesn't come with Pixel Launcher by default;

3) Install a temporary, third party launcher, use System App Remover (requires root) to uninstall the default Pixel Launcher, finally install Rootless Pixel Launcher (and maybe set it as a system app in case you wipe your data and prevent not having a launcher afterwards).

**Comment by RikKoedoot** [comment]
Hey. Is this default launcher on your ROM the official pixel launcher? If yes. Try to somehow delete it. And that is only possible with root I guess. Do you have root access?

**Comment by abdullahibneat** [comment]
If [this](https://forum.xda-developers.com/oneplus-5/development/rom-freedomos-1-0-t3627701) is the ROM you're talking about, I see you have Magisk installed (thus I assume you have root). All you need to do is the 3rd step I mentioned before:

> Install a temporary, third party launcher, use System App Remover (requires root) to uninstall the default Pixel Launcher, finally install Rootless Pixel Launcher (and maybe set it as a system app in case you wipe your data and prevent not having a launcher afterwards).

**Comment by ggkameleon** [comment]
Ok thank you so much 😊 I do to dirty flash my Rom and don't install pixel Launcher and then install your pixel Launcher 😋

**Comment by abdullahibneat** [comment]
If you're happy, you may close this issue.

**Comment by Tachyonic007** [comment]
Uninstalled pixel launcher. Still didn't help it. App not installed is still the error
