### ISSUE TITLE
Notification doesn't work on SO+

### ISSUE THREAD

**Issue by pativets** [amirzaidi/Launcher3#168]
The notification dots are not showing for Galaxy S8+ and also in settings there is only one option to allow rotation. Don't see options for changing the dot colour etc. 

Otherwise awesome work!

**Comment by amirzaidi** [comment]
> Don't see options for changing the dot colour etc.

That is normal

> In settings there is only one option to allow rotation

Normal for Android 7 and lower

> The notification dots are not showing for Galaxy S8+

Give the app notification access when it prompts for it then reboot
