### ISSUE TITLE
Android 5 app drawer does not appear

### ISSUE THREAD

**Issue by arozcaldo** [amirzaidi/Launcher3#170]
After swiping up from home screen, the app drawer is invisible. This issue is present on version 2.0 & 2.1.

**Comment by RikKoedoot** [comment]
Can you send a screenshot please?

**Comment by arozcaldo** [comment]
I provided an 8-sec video regarding the issue. Please check https://1drv.ms/i/s!Auaq2JzuEOlKhRx0CxTQqWsEqO_O

**Comment by abdullahibneat** [comment]
Are you sure that is Rootless Pixel Launcher? Because with this launcher you have 5 columns in both drawer and desktop (and you can't change this value unless you compile the launcher by yourself), but in the video you posted I see 4 columns.

**Comment by amirzaidi** [comment]
That depends on the DPI, the launcher can indeed show 4 columns on high DPIs. Anyways, this looks like a weird issue, which device is this? Can you send me a logcat?

**Comment by arozcaldo** [comment]
Here are the logs:
[Log_2017-08-28_22-11-27.txt](https://github.com/amirzaidi/Launcher3/files/1258366/Log_2017-08-28_22-11-27.txt)
[Log_2017-08-28_22-20-59.txt](https://github.com/amirzaidi/Launcher3/files/1258367/Log_2017-08-28_22-20-59.txt)

Does the presence of another factory installed launcher named 'Launcher3' affects the Rootless Pixel Launcher3? By the way the my device is a local brand -- Cherry Mobile Cubix Cube Lite.

**Comment by amirzaidi** [comment]
Are you sure these are the full logs for the event? There's very little information in them

**Comment by arozcaldo** [comment]
How about this one 
[alogcat.2017-08-29-14-21-05+0800.txt](https://github.com/amirzaidi/Launcher3/files/1259351/alogcat.2017-08-29-14-21-05.0800.txt)
Please check. Thank you.

**Comment by fmcgorenc** [comment]
I get the same thing on Lenovo A1000 (Android 5.0). I also see 4 columns (4" screen: 480x800 , dpi 240).

**Comment by abdullahibneat** [comment]
As amir said, to have 5 columns you need to change the DPI.

**Comment by fmcgorenc** [comment]
The number of columns is not the problem. The real problem here is that the app drawer is invisible when you open it.
