### ISSUE TITLE
Shortcuts off screen

### ISSUE THREAD

**Issue by hellenicsun** [amirzaidi/Launcher3#171]
Here's the 1.000 words description: 

![screenshot_20170828-064920](https://user-images.githubusercontent.com/21250045/29761057-ee18916e-8bcf-11e7-8854-86106e43a1c3.png)
![screenshot_20170828-090128](https://user-images.githubusercontent.com/21250045/29761058-ee1fb944-8bcf-11e7-9047-8d0db855e1e1.png)

Latest Launcher version running on LineageOS build lineage-14.1-20170821, OPO.

**Comment by RikKoedoot** [comment]
This also happens in the normal pixel launcher. And unless you resize it it is not fixable. If you rotate it to the other side it will do the same.

**Comment by hellenicsun** [comment]
Well, for me that's a first among all launchers that support app shortcuts (G. Now, Nova, Action) and I don't remember seeing this with Google's Pixel launcher. Anyway, it's easy to solve this issue in the shortcuts bar: just move the icon to the right. But, within app drawer I don't see a solution.

**Comment by Antuox** [comment]
I agree to have it fixed! And more having a screen of: 5.5 "

**Comment by RikKoedoot** [comment]
Yeah you're right. but it isn't making the launcher unusable so I think he is doing it in the next update. And that's probably in a while

**Comment by hellenicsun** [comment]
Whenever he can - so far he has done a great work for our benefit ;) 

It's not a major issue but like everything else we users notice, it should/ must be reported.

**Comment by abdullahibneat** [comment]
What device do you have? On Nexus 5X, Android Oreo (8.0.0) and RPL 2.1 I don't have this issue: https://goo.gl/photos/39dAAt3r2YNv4w6u9

**Comment by hellenicsun** [comment]
OPO aka OnePlus One

**Comment by amirzaidi** [comment]
I am not "fixing" this, it is intended. Change your display size or smallest width in developer settings so everything will fit on screen

**Comment by hellenicsun** [comment]
Changed smallest width from 360 to screen's default 400 and everything works great. Thank you.
