### ISSUE TITLE
Oneplus 3T opening app drawer lag

### ISSUE THREAD

**Issue by stefensuhat** [amirzaidi/Launcher3#173]
Hi, Thanks for this awesome APK. Love it.

Tried on my OP3T when opening the drawer it lags (very noticeable) and I think the app icon is too big.

THanks

**Comment by abdullahibneat** [comment]
If by lag you mean "slow", you might want to change the animation scale settings. Go to Settings -> About Device, and keep on tapping on Build Number. You should see a message like "You are now a developer". Now go back and you'll see a new entry in the settings, Developer Options. Now scroll down to "Drawing", and set all animations scales to 0.5. You may try other values until you get the animation speed you like.

Here is a video I did quickly (note: Developer Options on my device are under a different setting, on your OnePlus it should be right at the end of the main settings page): https://goo.gl/photos/DfjGwxSJWNhj8v2W8

**Comment by stefensuhat** [comment]
@abdullahibneat I think its not about the animation. because when I scrolled through my app drawer it feels lag.

**Comment by abdullahibneat** [comment]
I suggest you wait for amir.

**Comment by amirzaidi** [comment]
Can you enable profile GPU rendering -> on screen as bars, and then send me a screen recording of you scrolling @stefensuhat

**Comment by MFava91** [comment]
Hi,
I think I have the same issue. I'm on Nexus 5X, Android 8.0 stock rooted only for AdAway.
I leave here a [LINK](https://drive.google.com/open?id=0B-tmzwGTYoROam5CdW5yWHJTNW8) to a video I've made. Hope these help.
Anyway thanks for your work.

**Comment by stefensuhat** [comment]
@amirzaidi sorry for late reply. already tried your suggestion still happening. it exactly same as @MFava91 video

**Comment by abdullahibneat** [comment]
It wasn't a suggestion. If you follow his steps he can see what is going on and provide a solution. Here are the steps you need to follow:

> Can you enable profile GPU rendering -> on screen as bars, and then send me a screen recording of you scrolling

**Comment by stefensuhat** [comment]
@abdullahibneat  What do you call it if it's not a suggestion?

Like I wrote above, Already "tried" but still same and the lag is exactly same like @MFava91 video.

**Comment by abdullahibneat** [comment]
That was not the fix. Enabling those bars would act as a debugging tool, a.k.a. information used to solve the issue. This is what it would've looked like: 
![screenshot_20170829-143143](https://user-images.githubusercontent.com/7048592/29823787-8f75fe28-8cc7-11e7-8851-4e9ff52db90e.png)

Notice those bars? That is useful information for amir to work out a solution. Hope that helps :)

**Comment by mkygod** [comment]
Same issue on Nexus 6p w/ OPP4

Since no one is putting up a video w/ the GPU bars, here's mine:
[https://youtu.be/rdPUvnvLTlg](url)

**Comment by amirzaidi** [comment]
Can you guys disable all accessibility services? Like password managers and stuff
