### ISSUE TITLE
Unable to add contact widget

### ISSUE THREAD

**Issue by attila123456** [amirzaidi/Launcher3#174]
Nexus 6P, stock 8.0. When trying to add a contact widget (e.g. direct dial), the screen goes black and after a while the stock launcher opens.

**Comment by amirzaidi** [comment]
Which dialer app are you using? Can you send me a logcat?

**Comment by attila123456** [comment]
Stock dialer. I'll send logcat.

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo (8.0.0), RPL 2.1, I tried and it works for me (with stock dialer Google Phone, https://play.google.com/store/apps/details?id=com.google.android.dialer): https://goo.gl/photos/mvRDDiy7krvagHqX8

**Comment by ritchiedc** [comment]
I had the same problem when Contacts was updated from v1.7 to v2.1.2 (not sure about the in between versions). v2.1.3 fixed the problem for me but the existing shortcuts didn't work and had to be replaced.
