### ISSUE TITLE
Unable to change wallpaper using launcher built-in feature

### ISSUE THREAD

**Issue by craimasjien** [amirzaidi/Launcher3#175]
I tried to set the wallpaper while using this launcher as my default.
After successfully changing it (awesome wallpapers in the box by the way) I can't seem to change them anymore using the built-in variant. If I long-press the menu button on my OnePlus 5 and select "Wallpaper" it shows the "Finish action with..." dialog instead of using the built-in switcher (like it did the first time).

Relevant info:

Manufacturer: OnePlus
Model: A5000 (OnePlus 5)
OS Version: OxygenOS 4.5.8
Android version: 7.1.1
Launcher3 version: 2.1

**Comment by abdullahibneat** [comment]
Do you have Google Wallpapers (https://play.google.com/store/apps/details?id=com.google.android.apps.wallpaper) installed? This launcher is optimised for this wallpaper picker.

**Comment by craimasjien** [comment]
No, I did not have that app installed. After installing it, Launcher3 assumed that it should use this app to pick wallpapers. But, the weird thing is; it’s still not the intent I got when doing it the first time and I can’t seem to find the awesome wallpapers I got when I changed it the first time..

**Comment by abdullahibneat** [comment]
What happens if you now uninstall this, does the old wallpaper picker show up (which I believe is OnePlus', right?)? If not, try digging in your device's settings and see if you can find anything related to Default Apps (on my Nexus 5X is under "Apps and Notifications")

**Comment by craimasjien** [comment]
Then it gives me three options. I've included a screenshot. 

The selected app is OnePlus' wallpaper picker, the other 2 are self-explanatory. All 3 aren't providing the Intent I received the first time I used the feature.

![screenshot_20170828-105144](https://user-images.githubusercontent.com/1733692/29766487-2be77e24-8bdf-11e7-93b9-3531e70f0c1d.png)

**Comment by abdullahibneat** [comment]
Can you use a screen recorder to show the issue? I'm pretty sure it's a similar to issue #144, where other wallpaper pickers cause trouble due to not the launcher not being optimised for third party pickers.

**Comment by RikKoedoot** [comment]
Does the same issue happen if you use the stock launcher. Or try to set the wallpaper under display settings.
