### ISSUE TITLE
Your apk don't work on note 3 lineage 7.1.1

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#176]
This is a Google photos like down here 
I'm using pixel launcher as my default.
Plz let me know if more information needed
My phone 
Note 3 smn9005 hlte Snapdragon..

https://goo.gl/photos/2ucf7D9Y98vXLUUE6

**Comment by RikKoedoot** [comment]
Do you the original pixel launcher installed? If yes. Delete that first.

**Comment by ghost** [comment]
I cant delete my default launcher there is no option to uninstall it

**Comment by suphon-t** [comment]
Change your default launcher first then delete.

**Comment by abdullahibneat** [comment]
Can you be more clear? Did you have a Pixel Launcher installed prior to installing Rootless Pixel Launcher? A screen recording might be useful here. Also, the Google Photos link you posted is empty on my end.

**Comment by suphon-t** [comment]
Change your default launcher first then uninstall the original Pixel Launcher.

**Comment by RikKoedoot** [comment]
Install another launcher. Delete pixel launcher. Install launcher3

**Comment by ghost** [comment]
Thanks I have solve the problem. 😀😀😀

**Comment by ghost** [comment]
Hey,

I just signed the petition "European Parliament: Stop the
censorship-machinery! Save the Internet!" and wanted to see if you could
help by adding your name.

Our goal is to reach 4,500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/rv6LKvvqV8

Thanks!
wahhaj
