### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by Basavaraj-PN** [amirzaidi/Launcher3#177]
When i tried to install launcher3, having original pixel launcher already installed app will not install

**Comment by Basavaraj-PN** [comment]
![8da9c62d-5421-42ae-82f1-daeae0c99561](https://user-images.githubusercontent.com/23361336/29776844-9e0ed63a-8c27-11e7-8e7f-258a353c0491.jpg)

**Comment by schliflo** [comment]
Did you even try to solve the issue yourself? I mean it's literally the first point in the FAQ... Reading that is not too much to ask I guess.

**Comment by abdullahibneat** [comment]
Basically, you'd have to uninstall the Pixel Launcher you already have, and then install Rootless Pixel Launcher. In case the Pixel launcher is part of a custom ROM you're using, you'll need root privileges to uninstall it.
