### ISSUE TITLE
UI is not smooth ,some lags

### ISSUE THREAD

**Issue by Basavaraj-PN** [amirzaidi/Launcher3#178]
nexus 5x android o

**Comment by bajankristof** [comment]
You should describe the problem in details (what system are you using, what device, where does lag happen, etc.). It's really hard for a developer to work with basically no information about problems...

**Comment by abdullahibneat** [comment]
I think it's the same issue as issue #173. Can you confirm @basavaraj1995 ?

**Comment by RikKoedoot** [comment]
If I is #173 or he doesn't reply let's close this issue.

**Comment by Basavaraj-PN** [comment]
yes #173 as issue

**Comment by abdullahibneat** [comment]
I'd suggest you close this issue and follow the other thread.

**Comment by Basavaraj-PN** [comment]
Okay
