### ISSUE TITLE
Can't Install in 7.0 Moto G4 Plus

### ISSUE THREAD

**Issue by Peterjohn2603** [amirzaidi/Launcher3#18]
While installing appilcation it displays as the package appears to be corrupt

**Comment by amirzaidi** [comment]
Remove Pixel Launcher first.

**Comment by Peterjohn2603** [comment]
Yeah I have Removed it and tried to install still same error is displayed

**Comment by Peterjohn2603** [comment]
After removing Cache I tried to install its working but some features still not working like in the O version

**Comment by amirzaidi** [comment]
It's not based on the O version, and some features are 7.1+ specific like app shortcuts.

**Comment by Peterjohn2603** [comment]
But those features not working in 7.0 of moto g4 plus

**Comment by amirzaidi** [comment]
No, app shortcuts are not working. That's a system limitation. What other features are not working?
