### ISSUE TITLE
When i hide nav bar....

### ISSUE THREAD

**Issue by PR1D3S** [amirzaidi/Launcher3#181]
https://ibb.co/kXGD7Q when i hide nav bar the app icons not getting back to its original place....

**Comment by PR1D3S** [comment]
Samsung galaxy s4 9505 jfltexx lineage 14.1official

**Comment by abdullahibneat** [comment]
So there are some apps on the desktop, but they disappear? And you have used LineageOS' feature to hide the nav bar, is that right?

**Comment by amirzaidi** [comment]
This is part of the official Pixel Launcher too, it calculates the space if you have an on screen nav bar. Try a ROM with immersive mode built-in, that should work.
@abdullahibneat I think he means the bottom hotseat padding

**Comment by PR1D3S** [comment]
Bro working very well with the official pixel launcher,when i hide nav bar apps getting back to its original place on hotseat.....

**Comment by amirzaidi** [comment]
Can you try a force close of the app after you hide the navigation bar?

**Comment by PR1D3S** [comment]
Simply i do restart phone and apps get back to its original place....
