### ISSUE TITLE
Website for Mainstream Users?

### ISSUE THREAD

**Issue by SethuSenthil** [amirzaidi/Launcher3#182]
for many mainstream users, GitHub is not really that not friendly. When one first load the page you get bombarded with files and the user tends to leave or freak out. Using the content in the READ.md file we can craft a website UI that's more user-friendly. We can host this website on Github's own service GitHub pages which I think we all are familiar with.

**Comment by abdullahibneat** [comment]
Good idea, I can land a help with that (I'm currently using GirHub Pages to host my portfolio, so I know how it works). Amir, even though it's not necessary, you might want to purchase a domain name pertinent to Rootless Pixel Launcher? Otherwise, you'll have [repo-name].github.io, which is fine for me but doesn't sound too user-friendly.

**Comment by SethuSenthil** [comment]
We could use [freenom](http://www.freenom.com/en/index.html?lang=en) for a free domain name

**Comment by RikKoedoot** [comment]
I also agree. But it would cost amir money. And he doesn't ask for donations. And personally I don't want him to pay for a site others want

**Comment by abdullahibneat** [comment]
For my previous web designs, I used a lightweight, responsive framework called [Skeleton](http://getskeleton.com). It has one demo we could use as a template [here](http://getskeleton.com/examples/landing/) which I believe would be perfect for this project.

**Comment by abdullahibneat** [comment]
Quick update: here is a more specific example for this project: [https://abdu.io/rpl/](https://abdu.io/rpl/) ([SOURCE](https://github.com/abdullahibneat/rpl)) based on the demo above.

**Comment by SethuSenthil** [comment]
Lookin' good so far!

**Comment by SethuSenthil** [comment]
I did some modifications, will be adding more soon. How did I not know about the Skeleton Framework! It's really good, especially for performance.

**Comment by abdullahibneat** [comment]
I know! It's such a great framework, providing the essentials. I also approved your commits. Thanks for the help.

**Comment by SethuSenthil** [comment]
No prob, While looking into the GitHub API, I found that there is a way to directly send them directly to the latest APK without the user going through GitHub. This works by sending an AJAX request, not sure if it will work...
`<script type="text/javascript">
    $(document).ready(function () {
        GetLatestReleaseInfo();
    });

    function GetLatestReleaseInfo() {
        $.getJSON("https://api.github.com/repos/amirzaidi/Launcher3/releases/latest").done(function (release) {
            var asset = release.assets[0];
            var downloadCount = 0;
            for (var i = 0; i < release.assets.length; i++) {
                downloadCount += release.assets[i].download_count;
            }
            var oneHour = 60 * 60 * 1000;
            var oneDay = 24 * oneHour;
            var dateDiff = new Date() - new Date(asset.updated_at);
            var timeAgo;
            if (dateDiff < oneDay)
            {
                timeAgo = (dateDiff / oneHour).toFixed(1) + " hours ago";
            }
            else
            {
                timeAgo = (dateDiff / oneDay).toFixed(1) + " days ago";
            }
            var releaseInfo = release.name + " was updated " + timeAgo + " and downloaded " + downloadCount.toLocaleString() + " times.";
            $(".Launcher3-download").attr("href", asset.browser_download_url);
            $(".release-info").text(releaseInfo);
            $(".release-info").fadeIn("slow");
        });
    }
</script>`

**Comment by abdullahibneat** [comment]
Did you delete your previous comment about the GitHub API? I wanted to thank you, I implemented the code and it works perfectly.

**Comment by SethuSenthil** [comment]
O wow! I thought it failed!

**Comment by abdullahibneat** [comment]
It was just a matter of extracting the code responsible for generating the download link for the latest APK available:
```
$.getJSON("https://api.github.com/repos/amirzaidi/Launcher3/releases/latest").done(function (release) {
      var asset = release.assets[0];
      $("#dlink").attr("href", asset.browser_download_url);
});

<a class="button button-primary" id="dlink">Get Rootless Pixel Launcher now</a>
```

**Comment by abdullahibneat** [comment]
@amirzaidi Could you post a list of information you want to be displayed? Preview link of the work done so far: [https://abdu.io/rpl](https://abdu.io/rpl) ([source](https://github.com/abdullahibneat/rpl))

**Comment by amirzaidi** [comment]
@abdullahibneat could you perhaps contact me on Telegram? That might be easier than talking over GitHub. My username is @mirai
