### ISSUE TITLE
Option to Remove pill and date/weather

### ISSUE THREAD

**Issue by tdguchi** [amirzaidi/Launcher3#183]
I want to keep my screen as clean as I can, I  have never used google now, and the date/weather part is using a lot of space in screen

So maybe in launcher config could be a toggle to hide that part, and use that space in icons or other widgets.

thanks

**Comment by RikKoedoot** [comment]
Amir doesn't want to add features that aren't in the original pixel launcher. So I don't think it this will be impme

**Comment by RikKoedoot** [comment]
Implemented*

**Comment by RikKoedoot** [comment]
Btw. To remove pill you can remove google app

**Comment by amirzaidi** [comment]
There is actually a toggle for it in the Java Config but you cannot toggle it after compiling.

**Comment by tdguchi** [comment]
a toggle to toggle on/off or a toggle to on/off for all?

**Comment by amirzaidi** [comment]
It's a boolean in the Java configuration. If you want to remove the date/weather open up Android Studio, download my sources, and find the boolean. Then set it to false.

https://github.com/amirzaidi/Launcher3/blob/o/src_config/com/android/launcher3/config/FeatureFlags.java#L39

**Comment by tdguchi** [comment]
i have installed android studio, and the api for my android (7.1.1) i have loaded the project via "project from version control->github" and cloned your repository. 

I have selected in app modules the android 7.1.1 api, (8 was selected by default) and changed that part of the file, then run build-> build apk, but i got this error:

Error:(70, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'Launcher3' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.3 and sync project</a></li><li>The project 'Launcher3' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

whats wrong?

**Comment by amirzaidi** [comment]
Update all your dependencies in the Android SDK Manager and keep the target at Android 8 or else it won't compile.

**Comment by tdguchi** [comment]
boolean modified, apk generated, installed, but.... force close when trying to run it on 7.1.2, I give up.

**Comment by ghost** [comment]
Setting QSB_ON_FIRST_SCREEN to false indeed ends up in a force close when trying to run it on 7.1.2.
