### ISSUE TITLE
To many space between icons

### ISSUE THREAD

**Issue by EugenWiens** [amirzaidi/Launcher3#184]
On my LG g5 I can only place 4x3 icons. It seems that the space between the icons is calculated wrong.

**Comment by RikKoedoot** [comment]
Try to decrease your dpi.

**Comment by nikkomercado** [comment]
Decrease your DPI so app grid will automatically adjust.

**Comment by EugenWiens** [comment]
Where can I adjust the dpi? My phone running on the LG firmware. No custom
ROM no root.

Thanks
Eugen

**Comment by nikkomercado** [comment]
It depends. If you are running Android 7.0 or later, you can adjust it in Developer Options through 'smallest width'. You can't do this on Android Marshmallow. You'll have to root if you're running Marshmallow or below to change DPI.

**Comment by EugenWiens** [comment]
LG G5 do not have this option but with the gdb I changed the dpi to 600 form 640 and now it looks better.

Thx,
Eugen

**Comment by AxiK101** [comment]
Root is not necessary on android 6. just use adb commands via your pc to adjust the dpi of your screen. works like if you had root
