### ISSUE TITLE
Notification bar colour not changed

### ISSUE THREAD

**Issue by tsram90** [amirzaidi/Launcher3#188]
## Description

The quick notification bar and the notification bar are black and white like in 7.0

## Expected Behavior

The notification bar was supposed to be Grey and white.

## Steps to Reproduce

![whatsapp image 2017-08-29 at 16 53 58 2](https://user-images.githubusercontent.com/31439548/29818731-4b9dfb56-8cdb-11e7-88bd-7663432883ef.jpeg)

1.
2.
3.
4.

## Environment

* Device: Moto G4 Plus
* Android version: 7.0
* Launcher version: 2.1
* Rom: Builtin

## Logcat

```
your log here
```

**Comment by bajankristof** [comment]
@tsram90 
I think that this is more like a system feature than a bug or issue. The light navigation bar was introduced in Android Oreo and this launcher follows the Pixel Launcher as close as possible. As you stated above you are using 7.0.0 so that is why the navigation bar is dark.

**Comment by tsram90** [comment]
May be it can be considered as a feature request for a future version.

**Comment by abdullahibneat** [comment]
The launcher has no effect on the navigation bar. The light theme has been introduced in Android Oreo. You may close this issue if you're happy with the answers.

EDIT: Amir (the developer) wants to stick with the original Pixel Launcher features, meaning it's unlikely this feature will be included in future versions of RPL.
