### ISSUE TITLE
Nexus 5 charging

### ISSUE THREAD

**Issue by alecbe** [amirzaidi/Launcher3#189]
## Description

When launcher is selected as the default, charging slows to a crawl and the phone is warmer than normal. If you select the Google Now launcher as default, charging returns to normal.

## Expected Behavior

Should charge the same as with the Google Now launcher.

## Actual Behavior

Phone overheats and charging slows to crawl.

## Steps to Reproduce

1.Choose launcher as default.
2.
3.
4.

## Environment

* Device:Nexus 5
* Android version:6.0.1
* Launcher version:2.1.0
* Rom:Stock

**Comment by amirzaidi** [comment]
What happens if you keep the screen off? My app is just running as a regular user space app, the only thing I can think of is that it's so demanding the entire phone starts to throttle everything.. it doesn't have root access to influence charging at all

**Comment by alecbe** [comment]
The problem occurs when the screen is off. I agree that a launcher shouldn't have any influence on charging but it only happens when launcher is the default. I also have launcher installed on a Nexus 7 2013 running the same version of Android and it charges without any problems. I wonder if the issue could relate to the Google Now launcher being introduced with the Nexus 5 and Google using it for something undocumented.

**Comment by alecbe** [comment]
I think I may have found the cause of the problem. I switched off Daydream and the Nexus 5  charged without any issues. Looks like when Daydream is enabled something is running riot in the background. Daydream running on the Nexus 7 makes no difference but the 7 didn't come with Google Now launcher as default.

**Comment by kfenaugh** [comment]
Similar story with my Nexus 5x. Sometimes it would charge rapidly, other times it would say it would be fully charged in over a day! I have GNL as the factory launcher, and daydream enabled during charging. Reverted to GNL and charging normally once more every time.

**Comment by alecbe** [comment]
Seems evidence is sufficient to suggest that devices that shipped with the Google Now launcher as default have a Daydream/launcher3 compatibility issue. A bug?
