### ISSUE TITLE
Transparent home row 

### ISSUE THREAD

**Issue by mikelaube** [amirzaidi/Launcher3#19]
Awesome job btw no complaints thank you for doing what others could not!

**Comment by amirzaidi** [comment]
Do you mean you do or do not have a transparent home row?

**Comment by mikelaube** [comment]
Do not good sir all black

**Comment by jdawg0024** [comment]
installed on nexus 5X and home row is transparent

**Comment by JesusM** [comment]
If for "home row" you mean the navigation bar (where back, home and recents virtual buttons are placed), on my LG G6 running 7.0.0 it's not transparent.

**Comment by mikelaube** [comment]
Yes that's what I meant sorry I have the same phone as well

**Comment by bappa555** [comment]
Please reduce the transparency level on the dock, for me it is 100% transparent on MIUI 8.2

**Comment by amirzaidi** [comment]
Can you try the latest Telegram test build?

**Comment by JesusM** [comment]
Testing latest release (from https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v2.1) I still see navigation bar opaque. Other launchers have transparent navigation bars so I'd say it's not caused by OS (unless I'm missing something).

**Comment by amirzaidi** [comment]
Test the official Pixel Launcher please

**Comment by JesusM** [comment]
It was caused by LG scaling app to 16:7:9 rather than 18:9 full screen. Sorry!
