### ISSUE TITLE
Lag while sliding to open drawer

### ISSUE THREAD

**Issue by AndreHM** [amirzaidi/Launcher3#191]
When I slide up to open the drawer, it is caused a little lag, it is not flat like and fast the lawnchair for example.

**Comment by RikKoedoot** [comment]
Is it possible for you to take a screen recording?

**Comment by AlexTheChef** [comment]
I have the same lag with nexus 6p on Oreo.

**Comment by AndreHM** [comment]
worse than it starts to get lag, after a few days of use

**Comment by GGHolz** [comment]
Same issue on my Nexus 5X running Android O

**Comment by tiwaryabhishek** [comment]
same issue with my Lenovo K5 note plus (4gb ram).
The sliding animation is bit slow. 
We slide and the tray opens along with our finger. Ideally, it should just go up like a jet :)

**Comment by RikKoedoot** [comment]
I actually also have this issue

**Comment by mkygod** [comment]
Heres video of it in 60fps. I have a Nexus 6p on Android O developer preview 4.

[https://youtu.be/rdPUvnvLTlg](url)

**Comment by amirzaidi** [comment]
I suspect it's an app with a too high resolution drawable or some accessibility service, could you try using the launcher on another account (provided you're on AOSP which has native multi user support) and check how it performs there?

**Comment by ashishagrawal2645** [comment]
Changing font size and display size fixed the issue for me to some extent.
