### ISSUE TITLE
Google pill missing

### ISSUE THREAD

**Issue by VincentDArnold** [amirzaidi/Launcher3#192]
My phone is a Nexus 6 using 7.1.1 and I am on Launcher3 version 2.1.  Can you shed some light on what it is that I am missing please?

![screenshot_20170829-202836](https://user-images.githubusercontent.com/31450764/29850711-7f69e5f4-8cfd-11e7-912b-d6c1253ea67f.png)

**Comment by amirzaidi** [comment]
Huh? I don't see anything missing in this screenshot..?

**Comment by VincentDArnold** [comment]
On the bottom row between the text and Google chrome icon in the readme image is an icon.  What is that I thought that was the Google pill if not I am sorry then you can close this.  By the way I really like what you have done for us making this available!

**Comment by RikKoedoot** [comment]
What you ment Is the app drawer icon I guess. Thw google pill is in top left. Pixel launcher doesn't have app drawer icon.
If you are happy you can close this now

**Comment by amirzaidi** [comment]
@VincentDArnold the Google Pill is the button in the top left, the space in the middle.is just for placing an app.
