### ISSUE TITLE
Ok google not working

### ISSUE THREAD

**Issue by Tyrian81** [amirzaidi/Launcher3#195]
## Description
When activating OK Google, the voice screen appears , but does not seem to be registering voice ....

## Expected Behavior
Ok google voice screen dots should move

## Actual Behavior
voice screen dots not registering voice ...

## Steps to Reproduce

1. say "ok google"
2. see dots on voice recognition not moving... :P
3.
4.

## Environment

* Device: Samsung galaxy S7
* Android version: Latest
* Launcher version: latest
* Rom: unknown

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
It's working for me on Nexus 5X. Are you sure you set the permissions correctly for the Google app? Did you allow microphone usage permissions? Check inside Settings -> Apps -> Google -> Permissions.

**Comment by Tyrian81** [comment]
checked permissions for Google , set for microphone, although launcher3 does not have the option to set permission for microphone ...? it is activating but not registering voice afterwards ?

**Comment by RikKoedoot** [comment]
This should be a google app thing right? The launcher doesn't enable this of you didn't have this before

**Comment by Tyrian81** [comment]
On google now launcher it was working 100 % , now on launcher 3 , voice not registering ....

**Comment by Tyrian81** [comment]
Changed voice language to english and activated "from every screen" option , not helping ...

**Comment by abdullahibneat** [comment]
https://goo.gl/photos/zSEarDvTfGzX98c5A

It works for me. Do you have a custom ROM installed?
