### ISSUE TITLE
Google play game's icon is not circular

### ISSUE THREAD

**Issue by AadityaBhutada** [amirzaidi/Launcher3#196]
All the Google's icons are circular but play game's is not.
## Description
Many icon's may not be of circular shape, try to make them circular, the launcher work's good in my moto g2. Making play game's icon good will improve the launcher's look because it looks like an odd man out in the menu.

## Expected Behavior
Google play game's icon should be circular because other Google's apps are of circular shape.

## Actual Behavior
The play game's icon is triangular.

## Steps to Reproduce

1. Install Google play games.
2. Install the launcher3.
3. Look at the play game's icon.
4.

## Environment
You experience it as soon as you open the launcher.
For example: When you open the launcher.
Device: Motorola Moto G 2nd Generation.
Android version: 6.0
Launcher version: 2.1.0
ROM: Stock ROM
![screenshot_20170830-184654](https://user-images.githubusercontent.com/31450369/29874194-a89c1eea-8db3-11e7-9d51-af22b689e54c.png)

**Comment by abdullahibneat** [comment]
Mine is circular (https://goo.gl/photos/M2K7zDSEE1TqFKXt9). Have you got the latest version of Google Play Games? As this launcher does not come with any icon pack, it relays on app's metadata to fetch a circular icon (if it's available). Try updating the app.

**Comment by AadityaBhutada** [comment]
The app is already updated.
![screenshot_20170830-191353](https://user-images.githubusercontent.com/31450369/29875470-c5c91ae6-8db7-11e7-9cc3-908a8affc369.png)
 :( 
Why is this happening then?
Anyways, thanks a lot! The launcher is great! Hope to see the new and improved version with many new features soon.
All the best! @abdullahibneat @amirzaidi

**Comment by RikKoedoot** [comment]
Blame google 
They forgot to add the round icon. 
Round icon have to be in the apps before the launcher can make them round

**Comment by abdullahibneat** [comment]
@rickkode As you see in my screen, it does have the round icon. @AadityaBhutada can you try clearing the laucher's cache?

**Comment by AadityaBhutada** [comment]
Yes, tried clearing the cache. Even cleared the app data. Doesn't help. Guess it's the Google cause of which this is happening. @rickkode  @abdullahibneat

**Comment by RikKoedoot** [comment]
Maybe try if there is a beta. (Can't check myself because my phone gets repaired) one question to the post maker. Where did you find this issue template? I can't find it

**Comment by abdullahibneat** [comment]
Whenever you open an issue, this template appears (pull #180)

**Comment by AadityaBhutada** [comment]
How will I come to know if the launcher gets an update here? (Didn't find an option to ask you this personally) @abdullahibneat

**Comment by abdullahibneat** [comment]
You'll have to check regularly the release page. Hopefully this project will also have a website soon where you can check updates as well.

**Comment by AadityaBhutada** [comment]
Okay, thanks! @abdullahibneat
