### ISSUE TITLE
Unable to Install on lineageOS 14.1 : Package might be corrupt

### ISSUE THREAD

**Issue by umarhussain15** [amirzaidi/Launcher3#197]
## Description
the apk doesn't install saying the package might be corrupt
## Environment

* Device: Motorola Moto X 2014
* Android version: 7.1.1
* Launcher version: 1.4.large
* Rom: LineageOS 14.1

**Comment by abdullahibneat** [comment]
Are you sure you don't already have any other Pixel Launcher installed?

**Comment by umarhussain15** [comment]
yes i have installed it by default but there is no option to uninstall or disable it
correction version is 7.1.1-3862848

**Comment by abdullahibneat** [comment]
You'll need root privileges to do that.

**Comment by RikKoedoot** [comment]
Abdullah is right. You'll need root. Or install another ROM that doesn't use pixel launcher
