### ISSUE TITLE
Is there a way to lock down the placement of the icons on the screen?

### ISSUE THREAD

**Issue by coyage** [amirzaidi/Launcher3#198]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by bajankristof** [comment]
What do you mean? This title is just not clear at all.

**Comment by coyage** [comment]
Is there an option to lock the apps and widgets on the screen so they don't accidentally get dragged and dropped around when the screen is on?

**Comment by RikKoedoot** [comment]
Please fill in the lay out. But your question probably no because it isnt in pixel launcher. If you realy want that you can try lawnchair. Its pixel launcher with more customizability

**Comment by amirzaidi** [comment]
This is the issues tracker not the features request tracker. No there is no way to do this at the moment.
