### ISSUE TITLE
About releasing to the Play Store ...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [amirzaidi/Launcher3#199]
This is the written reason for not doing so:

> No, because the Pixel Launcher package name is not allowed. Neither is a debug variant app.

Why not change the package name then? And put a release variant?

Does it cause limitations?
Does Google have anything against it?

**Comment by bajankristof** [comment]
It's because the Launcher can only access the weather data (next to the Google pill on the home screen) if it has the right package name...
In other words only the pixel launcher package has permission to fetch weather data from google.

**Comment by AndroidDeveloperLB** [comment]
And other than that? Is it 100% ok ?
You can get weather data from other sources, and I think Google weather data is already available via API, no? Could be wrong of course.

**Comment by RikKoedoot** [comment]
The awnser to this question is in the faq in the readme

**Comment by SethuSenthil** [comment]
Yes you can, but there are many other package names such as the one used for the notification dots and shortcuts etc, that doesn't have a play store legal API alternative. Also, the pill is already in the play store in apps like Nova Launcher.

**Comment by PR1D3S** [comment]
Yes we can get weather data from other sources but data will not be accurate like lawnchair,so if we want this launcher on play store then we have to kill weather feature for ever and it cant be fixed....so leave this topic...

**Comment by AndroidDeveloperLB** [comment]
@SethuSenthil Pretty sure "notification dots and shortcuts" are not something launchers aren't allowed to use. It's part of the new API on Android O.

@PR1D3S Just for weather? There are plenty of weather apps out there. What's so special here?

**Comment by SethuSenthil** [comment]
Sorry, I used the wrong examples, It's mainly for the Google feed.

**Comment by AndroidDeveloperLB** [comment]
@SethuSenthil Currently not available for the play store, but the Google feed can be added via APK to the launcher, according to what I see on Nova launcher.

**Comment by amirzaidi** [comment]
Yes but that is a hacky solution which I'm not sure if I am able to properly implement. If Google ever releases the necessary APIs to make this launcher into a user release app without the Pixel Launcher package name and keep Google Now and Weather integration I will put it on the Play Store.

**Comment by AndroidDeveloperLB** [comment]
@amirzaidi Please consider starring this request then:
https://issuetracker.google.com/issues/65146924
Also, how did you get the code to Google's launcher anyway? Is it available on Github somewhere?

**Comment by amirzaidi** [comment]
Decompiling with apktool, enjarify and procyon ;)

**Comment by AndroidDeveloperLB** [comment]
@amirzaidi Is it legal?

**Comment by bajankristof** [comment]
Aaaand let's close this thread right now :D

**Comment by amirzaidi** [comment]
Why would it be illegal? There's no patent on their XML and smali as far as I know

**Comment by AndroidDeveloperLB** [comment]
@amirzaidi Logically, since it's not open sourced, it might not be the creators' intention to let everyone modify or copy it.
Legally, the default license of closed source apps say you should not modify it or copy it, etc...
That's at least what I've been taught.

**Comment by amirzaidi** [comment]
Is there anything in the law they could use to sue me for doing this project? I'm not making money from it in any way

**Comment by PR1D3S** [comment]
Nothing will happen they will remove it from play store if they found something wrong,thats it...

**Comment by PR1D3S** [comment]
https://www.google.co.in/amp/m.indiatoday.in/lite/story/pixel-launcher-2-0-available-for-android-smartphones-comes-with-few-android-oreo-features/1/1036142.html
If they wanted to take legal steps against you then they did it bfore because your launcher story in our Indian news and tech sites u can see above...

**Comment by AndroidDeveloperLB** [comment]
@PR1D3S Probably. It's in a lot of websites already.
Seeing that Google is usually open, maybe they don't mind.

**Comment by PR1D3S** [comment]
If you are doing illegal project then nova and actoin also illegal....

**Comment by AndroidDeveloperLB** [comment]
@PR1D3S How come?

**Comment by PR1D3S** [comment]
What?

**Comment by AndroidDeveloperLB** [comment]
@PR1D3S What what?
How come "nova and actoin also illegal." ? 
What's special on Nova that you say it's illegal?

**Comment by SethuSenthil** [comment]
They don't have all the features like this launcher does.

**Comment by AndroidDeveloperLB** [comment]
@SethuSenthil And the opposite.
