### ISSUE TITLE
Can't scroll up on Google Calendar Widget

### ISSUE THREAD

**Issue by sumodevelopment** [amirzaidi/Launcher3#2]
Swiping up on Google Calendar widget to scroll brings up the application drawer instead of scrolling on the widget.

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/commit/213a078132df59bf5f6583bf7c9264f62c0bdf39

Working on this, commit is ready, I'm just letting some Telegram users test it before I update my reddit post :)

**Comment by amirzaidi** [comment]
It should be fixed now, if you can confirm 1.2 fixed it for you too I will close the issue.

**Comment by dewald-els** [comment]
Awesome :) Let me download and let you know asap.

**Comment by dewald-els** [comment]
Where can I download the APK, I tried building the project but I keep getting Gradle cache corrupt :(

**Comment by amirzaidi** [comment]
It's under releases, https://github.com/amirzaidi/Launcher3/releases

**Comment by dewald-els** [comment]
Fixed with 1.2
