### ISSUE TITLE
Google Search pill animation not working in landscape mode

### ISSUE THREAD

**Issue by git-drift** [amirzaidi/Launcher3#20]
The Google Search pill animation is not working and it just flashes away way too fast when you open and close the Google Search pill.
Also once you have opened the Google search pill in landscape mode, the Google now page becomes transparent when you slide across.
The Google icon in the search bar is overlapping the 'Search' text.
![screenshot_2017_06_13_11_55_18](https://user-images.githubusercontent.com/29410978/27098160-395c3f08-5094-11e7-8f6f-fbc0633407f5.png)
![screenshot_2017_06_13_11_56_27](https://user-images.githubusercontent.com/29410978/27098196-5a825424-5094-11e7-9c35-e55b4c7f80ef.png)

**Comment by amirzaidi** [comment]
It looks like you're using substratum themes, could you disable all of those and test again? So far I've never heard of this problem before.

**Comment by git-drift** [comment]
I am on LineageOS 14.1,and I'm not using any substratum themes. Everything thing works fine in portrait mode.

**Comment by amirzaidi** [comment]
Well, maybe I've just missed an option in the Google app but how did you set that car in the background of the Google Now panel?

**Comment by git-drift** [comment]
The car is my wallpaper. The Google now panel gets transparent once I use the Google pill in landscape mode.

**Comment by amirzaidi** [comment]
Huh, but the first picture shows the Google Now panel with your background. That is what is worrying me, I've never seen that before, and neither have I heard of this bug
