### ISSUE TITLE
OTA updates

### ISSUE THREAD

**Issue by SethuSenthil** [amirzaidi/Launcher3#200]
I was just wondering, people were requesting for notifications for new updates but what if it updates itself (with user input). Apps like [Terrarum TV](https://terrariumtv.com) are doing it flawlessly maybe something like that would be good. It's not necessary, but would be a great feature to have. Thank you for your support!

**Comment by amirzaidi** [comment]
People might complain to me about spam or advertising, so I'd rather not.
