### ISSUE TITLE
Request: shortcuts on Android < 7.1

### ISSUE THREAD

**Issue by vibos07** [amirzaidi/Launcher3#203]
Hallo! Is it possible to implement long-press shortcuts on Android lower then 7.1? Atleast 7.0 and 6.x?

**Comment by coupdeville360** [comment]
No short cuts on notification short cuts

**Comment by lintangwahyu** [comment]
like on action launcher or lawnchair

**Comment by RikKoedoot** [comment]
In https://t.me/appforks amir showed he is working on back porting.

**Comment by RikKoedoot** [comment]
It's a telegram channel btw

**Comment by jleslie97** [comment]
I don't know if this is known but on the Galaxy S8 Android 7.0 Notification Dots work as expected.

**Comment by RikKoedoot** [comment]
@Jleslie97 please make a new issue for that
