### ISSUE TITLE
No notification dots

### ISSUE THREAD

**Issue by Burnz316** [amirzaidi/Launcher3#204]
## Description
Notification dots do not show for any app.

## Expected Behavior
Notification dots should appear when notification still active.

## Actual Behavior
Notification dots do not appear at all.

## Environmont
* Device: Nexus 6P
* Android version: 8.0
* Launcher version: 2.1.0
* Rom: Stock Rom

**Comment by PlugaruT** [comment]
have you activated notification dots from settings?

**Comment by Burnz316** [comment]
![screenshot_20170831-195034](https://user-images.githubusercontent.com/31500334/29917616-d7644e82-8e85-11e7-89aa-2ce56b44f2e4.png)

**Comment by bajankristof** [comment]
@Burnz316 
Also did you give permission to Launcher3 to access notifications?

**Comment by Burnz316** [comment]
![screenshot_20170831-205856](https://user-images.githubusercontent.com/31500334/29920087-46fe7cbe-8e8f-11e7-9a41-e89c8d93fb8f.png)
It only has storage and telephone under app permissions, am I in the right spot or have I missed something..

Thanks for the help, really enjoying the launcher!

**Comment by Burnz316** [comment]
Ahh just found the setting buried somewhere else.. Thanks so much for the help!

**Comment by bajankristof** [comment]
@Burnz316 You're welcome! ;)

**Comment by Burnz316** [comment]
For anyone else who comes across this issue..

Goto Settings -> Apps & notifications -> Advanced -> Notification access
