### ISSUE TITLE
Question/Update

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#206]
When allow "suggested apps" in drawer?

**Comment by RikKoedoot** [comment]
He had this in his old version (1.5) but it was too messy code so he deleted it (please read the readme FAQ first)

**Comment by ghost** [comment]
oh sorry I found it

**Comment by nyancrimew** [comment]
@amirzaidi take a look at this commit, it might be that "open source solution" you are looking for :wink: https://github.com/DirtyUnicorns/android_packages_apps_Launcher3/commit/8b30593a77005446e2d2171e69fb2945368274d3

**Comment by andy0105781** [comment]
How can i remove launcher 3 from my galaxy s7 edge.cant seem to go back to standard launcher

**Comment by highpowerxh** [comment]
@andy0105781 Settings->Apps->Three dots->Default Apps->Home Screen to change default launcher. You can always uninstall the launcher from Settings->Apps
