### ISSUE TITLE
Google Assistant

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#207]
Add Google Assistant shortcut on the google search side

**Comment by abdullahibneat** [comment]
When you press the G pill, and say Ok Google it opens up Google Assistant. Not sure if you can open Google Assistant directly from the pill.

**Comment by amirzaidi** [comment]
@MrLuckas there is no Assistant shortcut on Pixels either. Only the voice search shortcut for regions without the assistant. But that shortcut is ugly, in my opinion.
