### ISSUE TITLE
Long press icon for  "quick options" not working on Moto G(5) Plus

### ISSUE THREAD

**Issue by TimeMuffins** [amirzaidi/Launcher3#21]
Thanks for porting this for all.

After installing I noticed that long press for quick action is not  working on my device. Just wanted to know if it has not yet been implemented or there is some issue.

**Comment by amirzaidi** [comment]
You need Android 7.1+ and it needs to be the default launcher

**Comment by RikKoedoot** [comment]
Moto g5 has 7.0, not 7.1, it's a shame Lenovo is bad at updates (same for g4plus too)
