### ISSUE TITLE
Home,” “Upcoming,” and “Recent tab are misssing in the Google app and Google now

### ISSUE THREAD

**Issue by tiwaryabhishek** [amirzaidi/Launcher3#211]
## Description
In other devices I can find the three tabs at the end of the screen while in the google app. But uplon installing the Launcher I do not see the three apps appearing.
I only see one page with all the google now cards.
Home,” “Upcoming,” and “Recent tab are misssing

## Expected Behavior
When I launch the google app or draw google now pannel from left slide on home screen, I should be able to see three tabs there.
Home,” “Upcoming,” and “Recent tabs

## Actual Behavior
Home,” “Upcoming,” and “Recent tab are misssing

Screenshot
1.https://11259261859358188502.googlegroups.com/attach/8680f8ac44d2b/Screenshot_20170202-124416.png?part=0.1&view=1&vt=ANaJVrG6BIF1vY9h1Z6NPifqvPVA0sdmxvF53TgP22tZrvS5f_j51cpjJwR3SML3Yhf1dvdqv6nzdd4LkFuPLb7DVG6ttGw7RvsMZRuQpieP_wlXZ02zwnw 

## Environment
* Device: Lenovo K5 note plus
* Android version: 6.0
* Launcher version: 2.1
* Rom: Lenovo vibe

Regards,
Abhishek

**Comment by abdullahibneat** [comment]
Can you post a screen of the missing buttons? I don't think I ever saw them. Also, the launcher doesn't impact on the Google App itself, so it might be an that you updated your Google App.

Using the default launcher on my Nexus 5X I can't find those buttons either, so I'm pretty sure Rootless Pixel Launcher is not the cause of this issue: https://photos.app.goo.gl/7z3OKJk3PnnCEXl22

**Comment by RikKoedoot** [comment]
Thats because the slideout Google pannel doesnt use the tabs. Thats a fault of the Google app. They are working on a full redesign of the pannel

**Comment by tiwaryabhishek** [comment]
Hi,
I was speaking about the following tabs:


![download_20170903_214344](https://user-images.githubusercontent.com/28593548/30004674-5e90d3f4-90f1-11e7-9151-bf2bd414130d.png)

The description about them and when they were introduced is provided here.
http://www.androidpolice.com/2017/08/16/google-rolling-tabbed-google-app-interface-users/ 
Regards,

**Comment by tiwaryabhishek** [comment]
Yes, @abdullahibneat @rickkode 

I learnt that later on that these tabs are also not present in the Google Nexus and pixel mobile phone version of Google now.

I am happy to have an app the way it is. I do not require extra feature just to avoid any bloat ware. So, I am happy with @amirzaidi version of rootless launcher. As the mentioned feature is not present in the original APK. :)

**Comment by tiwaryabhishek** [comment]
@amirzaidi ,

Thank you for building the app with out any bloatware. 
I need it just the way AOSP launcher3 is. 
I appreciate your work and thanks for making it bloatware and adware free. 

Hope you also release the updates as and when Google releases updates to its version of the launcher.

Thank you and regards,
Abhishek
