### ISSUE TITLE
Wallpaper issues.

### ISSUE THREAD

**Issue by cyberon** [amirzaidi/Launcher3#212]
I'm using Backdrops as my wallpaper app and lost the option to set a wallpaper only on the lockscreen. It works fine on GNL, can it be a issue with this launcher?

**Comment by amirzaidi** [comment]
Install Google Wallpapers and select Backdrops through there

**Comment by cyberon** [comment]
Unfortunately it doesn't fix the issue, still can't set the wallpaper to lockscreen only.

**Comment by amirzaidi** [comment]
Live wallpapers can't be set to lockscreen only as far as I know?
