### ISSUE TITLE
date in the bar

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#215]
My date is with the month in lowercase (Portuguese - Brazil) Can fix

**Comment by abdullahibneat** [comment]
Do you mean this: https://photos.app.goo.gl/q1v1TnKYYeeu1JWe2 ? Can you post a screenshot of your issue?

**Comment by abdullahibneat** [comment]
Did you solve the issue? It'd be nice to share the solution for future reference.
