### ISSUE TITLE
Weather in Launcher3

### ISSUE THREAD

**Issue by Eddy69** [amirzaidi/Launcher3#217]
I've cleaned up my apps. Probably one too many: the weather next to the Google drawer doesn't appear anymore. Which app do I have to install to fix this?

**Comment by abdullahibneat** [comment]
You need the Google app.

**Comment by RikKoedoot** [comment]
Google app needed with location enabled. And In google feed refresh to see weather there

**Comment by Eddy69** [comment]
I do have that app installed. With that info I've adjusted the settings for weather. You should've enabled "Weather updates" and "Weather updates for your location".
Fixed! Thx :)

**Comment by Eddy69** [comment]
Answers crossed.

**Comment by RikKoedoot** [comment]
If you are happy please close the issue :)
