### ISSUE TITLE
Apps can't create shortcuts

### ISSUE THREAD

**Issue by jagomf** [amirzaidi/Launcher3#218]
Apps which create shortcuts on desktop (e.g., Telegram, Evernote) can't seem to create any shortcut.

Ways to reproduce:

Telegram:
1. Open Telegram
2. Go to any conversation
3. Tap on header
4. Open three-dot context menu
5. Create/add shortcut

Evernote
1. Open Evernote
2. Open any note
3. Tap on three-dot context menu
4. Add shortcut to start screen

In both cases, no shortcut is created when it actually should

Versions:
Rootless launcher 2.1
Android 8.0
Nexus 5x

**Comment by RikKoedoot** [comment]
Hmm. I cant replicate this Right now. Maybe Someone else can try if it works for them?

**Comment by abdullahibneat** [comment]
I just checked and this is definitely a bug (at least for telegram). However, if you long-press on the telegram icon on the desktop/app drawer you can create shortcuts from there (basically drag and drop any contacts from the list).

**Comment by PR1D3S** [comment]
https://ibb.co/k5aJYa
https://ibb.co/eEp1mv

**Comment by abdullahibneat** [comment]
Ok, I switched back to Google Now launcher, and even there Telegram and Evernote don't create any shortcuts. Can anyone try any other launcher?

**Comment by amirzaidi** [comment]
It's an Android 8 bug that has existed since the DPs and Google never fixed it..

**Comment by censto** [comment]
Same.
Facebook  and ES File Manager can't create shortcuts
Working on 7.1.2
But not in Android 8

**Comment by Daimonion1980** [comment]
First i installed Launcher3 at Oreo and i can't add shortcuts too. Tried it with Hangouts and one other App.
Even in Google Now Launcher it doesn't work. 

@amirzaidi is there a bug report which can be starred?

**Comment by jagomf** [comment]
I first had Android 8 compilation OPR6, then I got this *apparently* older OTA (version OPR4) but still I installed it. According to Google it's not older but newer.

After I got mentioned OTA, shortcuts can now be added again. Actually, whenever I create a shortcut, system prompts to either drag and drop to desktop or add automatically.

**Comment by Daimonion1980** [comment]
So, you want to say us that with opr4 shortcuts are working and with opr6 they are not working?

Hmm
As https://developers.google.com/android/ota says for N5X the OPR4 is the september Build and you are right.

I own a N6P ans actually i'm on OPR6 September Build. It seems that we N6P owner have to wait for it.

**Comment by jagomf** [comment]
As mentioned, seems that [OPR4 goes **after** OPR6](https://www.reddit.com/r/nexus5x/comments/6zkmkr/question_about_android_o_build_number_after_update/dmw83mf/), and yes, with OPR4 I have no problem to create shortcuts.
