### ISSUE TITLE
App shortcuts not working 

### ISSUE THREAD

**Issue by varunrramani** [amirzaidi/Launcher3#22]
Long pressing app shortcuts not working on nexus 6p on 7.1.2

**Comment by saiakhil8** [comment]
Make the launcher default...it should work...initially I also faved same thing in Nexus 6p...I cleared data and made launcher default..then they worked

**Comment by GuyKh** [comment]
I'm experiencing the same problem. Even after Default Launcher and clearing data and cache

**Comment by RikKoedoot** [comment]
What Android version are you on? If you're on 7.0 or lower it doesn't work, because it's implemented in Android 7.1

**Comment by varunrramani** [comment]
@saiakhil90 thanks that worked!

**Comment by SethuSenthil** [comment]
Set the launcher as your default launcher. If it still doesn't work restart
your phone.
