### ISSUE TITLE
OK Google voice detection not working properly

### ISSUE THREAD

**Issue by benzeyf** [amirzaidi/Launcher3#220]
"ok google" does not work normally. I try to tell to sort it.
- "ok google" .. listening
- One dollar, how many euro? .. opens the navigation window, responds.
- "ok google" .. listening
- how many calories an apple? opens the navigation window, responds.
.. (it continues this way)
I press the main screen key and back to home screen.
- "ok google" this time opens the google search bar and keyboard for manual search as like to press google search bar

I close the previous navigation window.
- - "ok google" .. listening (everything is normal)

Device General Mobile 4G (androidone)
OS 7.1.1
Launcher 2.1

**Comment by abdullahibneat** [comment]
I don't understand what the problem is... Could you post a screen recording of the issue?

**Comment by SethuSenthil** [comment]
This doesn't seem to be an issue with the launcher

**Comment by benzeyf** [comment]
but there is no problem with "google now launcher". working!

**Comment by asianfez123** [comment]
Have the same issue on my Moto Z Play.

It will sometimes work once from the homescreen, and will continue to work from the results screen. But if I am to go back to the home screen and try "Ok Google", it will just bring up the search bar and keyboard (Swiftkey if that matters). This is only with Google Assistant turned off, only using Ok Google search bar.

Video of my experience:
https://www.youtube.com/watch?v=ewHqkPF-XiE

Moto Z Play Unlocked
Android 7.1.1
Launcher 2.1

**Comment by abdullahibneat** [comment]
Nexus 5X, Android Oreo, RPL 2.1, this is definitely a bug: https://photos.app.goo.gl/D2GBp4xDcOvQxMF42

As you can see, with RPL "Ok Google" brings up the keyboard if the Google app is in background. However, when I switch to Google Now Launcher voice detection works regardless of the Google app being in the background. THIS HAPPENS WHEN YOU DISABLE GOOGLE ASSISTANT.

**Comment by asianfez123** [comment]
Thanks abdullahibneat for confirming on your side, me turning on Google Assistant didn't have any issues. This seems to be a bug with the current launcher, only with google assistant disabled. I am going to assume the OP was in the same situation.

I didn't really care to use Google Assistant before, so I didn't turn it on. But I guess I'll just have to slightly adjust my behavior to get use to it, which isn't a big issue.

**Comment by benzeyf** [comment]
just like that. I could not send video.

**Comment by abdullahibneat** [comment]
We'll need to wait for Amir to see if he can solve the issue.

**Comment by amirzaidi** [comment]
Can you guys test this on 3.3?

**Comment by amirzaidi** [comment]
Reopen if the bug persists.
