### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#221]
Can you replace the Motorola icons?

**Comment by abdullahibneat** [comment]
This launcher does not implement any built-in icons, thus it doesn't change the icons of any app. The only thing it does is it fetches round icons from the data provided by each app. If no information is included for round icons, it then uses the default icons.

If you want to integrate icon packs, you may have to use a different launcher, such us [Lawnchair](https://github.com/Deletescape-Media/Lawnchair/releases).

If you're happy with this answer, you may close the issue.
