### ISSUE TITLE
Add Change Icon

### ISSUE THREAD

**Issue by ismailxebia** [amirzaidi/Launcher3#222]
I think this is the best launcher, if in add iconpack

**Comment by abdullahibneat** [comment]
Please have a look at issue #221.

**Comment by 24aitor** [comment]
You can use Awesome Icons app to create custom icons shortcuts to homescreen, not to the menu.

[Awesome Icons on Play Store](https://play.google.com/store/apps/details?id=com.momocode.shortcuts&hl=es&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dawesome+icons&pcampaignid=APPU_1_E7e5Wdy-AsGsabvUkegK)
