### ISSUE TITLE
Launcher 3 on Galaxy S8 is very slow and horrible in use.

### ISSUE THREAD

**Issue by filmmaker07** [amirzaidi/Launcher3#223]
## Steps to Reproduce

1.
2. https://drive.google.com/file/d/0B_gu5GLNSQVTQTE2MEZNQU9NMjg/view?usp=drivesdk   
3.
4.

## Environment

* Device: Galaxy S8
* Android version: 7.0
* Launcher version: 2.1
* Rom: Stock

## Logcat

```
your log here
```

**Comment by RikKoedoot** [comment]
tbh I don't see much lag.

**Comment by abdullahibneat** [comment]
Enable developer options -> set animation scales to x 0.5.

**Comment by filmmaker07** [comment]
Where. I'm not developer.

**Comment by jleslie97** [comment]
I can confirm as another S8 user that there is lag present on this launcher when compared to Google now launcher.  In particular occasional hangs when pulling out the Google feed. 
It's the exynos variant of the S8 that I'm using.

**Comment by abdullahibneat** [comment]
Look at issue #173 (my first reply).

**Comment by jleslie97** [comment]
@filmmaker07 to activate the developer options on the s8 scroll to the bottom of settings. About device > software information. Tap the build number 8 times. 
Back twice. Then at the bottom of settings developer options appear.

**Comment by jleslie97** [comment]
@abdullahibneat nah I mean it's smooth then on occasion there are delays after using the launcher for a day or 2. But I should note that I'm also getting excessive RAM usage issue while using this launcher. Average around or over 100mb then maximum sometimes over 200mb. Don't think this is normal compared with what other people are reporting.

**Comment by jleslie97** [comment]
I should mention I haven't used the launcher for a week or so and can't seem to replicate the lag just while switching back for a few minutes. after initial loading of icons and widgets.

**Comment by abdullahibneat** [comment]
For RAM usage, please report to issue #205. For the lag, can I suggest to wait for a few days?

**Comment by andy0105781** [comment]
I cant seem to go back to standard launcher on samsung s7 edge.tried deleting oreo launcher but will not remove from homescreen.any ideas

**Comment by jleslie97** [comment]
@andy0105781
This should be titled as launcher 3 with the google/pixel launcher logo when you go to settings > apps. 
If it successfully uninstalls but the same homscreen remains then it must be another launcher. Got to settings > apps and click the 3 dots > default apps and you can change the launcher from there

**Comment by jleslie97** [comment]
@abdullahibneat I've been testing the launcher and although its not terribly lagging. I'm not experiencing delays swiping between homscreens. 
I do however experience consistent hiccups/slight delays when swiping to the Google (now) feed page. Swiping the app drawer isn't really that smooth. I would describe it as a delay it's just less smooth than most launchers 
When I try to screen record it everything lags so doesn't really show the issue. I'll try and record it with another phone when I have time.

**Comment by amirzaidi** [comment]
1. Disable all accessibility services
2. Make sure you are not on the Google App Beta

**Comment by filmmaker07** [comment]
Still lags

**Comment by jleslie97** [comment]
@amirzaidi tested the launcher further. Although I do get the occasional lag while opening the app drawer. The consistent lag while opening Google feed isn't specific to this launcher as I get the same on nova and action launcher with Google feed enabled. 
Also disabling accessability setting made little to no difference. Hope this helps. 

Thank you for all you work and good luck with Uni :)
