### ISSUE TITLE
Google Feed

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#224]
Will be possible update to the Google Feed transparent as some Pixels?

**Comment by RikKoedoot** [comment]
idk. I was wondering about that too. but I think the Google app checks if you have pixel and then gives the transparent feed. let's wait for amir

**Comment by xXIRapToRIXx** [comment]
I am running Oreo on my OP3T and I have the transparent google feed when using the official pixel launcher but as soon as I switch to this it turns back to "normal white"....
