### ISSUE TITLE
SUGGESTION - New setting to turn the Parallax wallpaper effect

### ISSUE THREAD

**Issue by ArtemSmaznov** [amirzaidi/Launcher3#226]
## Description
If not mistaken the original Pixel launcher had the parallax effect for the background wallpaper which was moving to the opposite direction when you were swiping between different home screens. It would be nice to have an option in the settings to enable that in this launcher as well. Sounds like a cool effect.

Using Nexus 6 with Android 7.1 here so never experienced the effect from stock Pixel launcher.

**Comment by RikKoedoot** [comment]
I think this is a live wallpaper. search for pixel live wallpapers

**Comment by RikKoedoot** [comment]
search on Google*

**Comment by amirzaidi** [comment]
Install "Google Earth Wallpapers" from XDA
https://forum.xda-developers.com/android/apps-games/port-live-earth-wallpapers-t3481640
