### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#227]
Enable/Disable option to Google Pill... This option is available in new phones that come with Pixel Launcher preinstalled

**Comment by RikKoedoot** [comment]
can you give us an example of a phone that has that. because phones other than pixel don't use pixel launcher

**Comment by abdullahibneat** [comment]
Just disable the Google app and it should be gone.

**Comment by ghost** [comment]
@rickkode Essential phone, new Motorola's phone, etc

**Comment by ghost** [comment]
@abdullahibneat if I do that Google feed and services stop too

**Comment by RikKoedoot** [comment]
@carlossicaja that isn't pixel launcher. Just a launcher that also has swipe up to drawer

**Comment by ghost** [comment]
@rickkode ohh ok if isn't pixel launcher then tell me whats the name of that launcher.

**Comment by PR1D3S** [comment]
Its called stock launcher....

**Comment by suphon-t** [comment]
They're based on Launcher3.

**Comment by abdullahibneat** [comment]
It's a revisited version of Launcher3, the default launcher for AOSP (Android Open Source Project). 

There is a reason Pixel Launcher has the term "Pixel". It's been designed for Pixel and Pixel XL devices.

Also, the only way I know of disabling the Google Pill is to uninstall/disable the Google app (just read the README file in the tab "Code" on top of this page). If you know some Java programmings and have used Android Studio before, you may also find the code that displays the Google Pill and delete that out.
