### ISSUE TITLE
Quickshortcuts solution for 7.0?

### ISSUE THREAD

**Issue by AxiK101** [amirzaidi/Launcher3#228]
Only a few work. Can you copy the algorithm that Lawnchair use to make them work? Thanks
Xperia XA Ultra 7.0 stocka

**Comment by amirzaidi** [comment]
I've been experimenting with it in the little free time I have and it seems buggy, until I figure out how to do it properly I won't add it

**Comment by vibos07** [comment]
Maybe you can a "beta" thread with some unstable features?

**Comment by Randomblock1** [comment]
@vibos07 http://telegram.me/AppForks

**Comment by vibos07** [comment]
@randomblock1 and?

**Comment by RikKoedoot** [comment]
@vibos07 thats the telegram channel where the beta versions of the app is
