### ISSUE TITLE
Backport adaptive icons on 7.0

### ISSUE THREAD

**Issue by AxiK101** [amirzaidi/Launcher3#229]
Is it possible?

**Comment by PR1D3S** [comment]
Adaptive icons even not available on 7.1.2.....amir may be working on it....lets hope for it....

**Comment by RikKoedoot** [comment]
@PR1D3S because it's an Android o API. That's hard to backport I guess

**Comment by AxiK101** [comment]
@rickkode yes but not impossible. Lawncher do the trick at some point i think

**Comment by PR1D3S** [comment]
Lawnchair and nova launcher already backported it....

**Comment by PR1D3S** [comment]
Comeon amir bro now wakeup and do something for adaptive icons...

**Comment by amirzaidi** [comment]
Probably won't do this because of how hacky the implementation will be
