### ISSUE TITLE
No settings available

### ISSUE THREAD

**Issue by bogdansoare9** [amirzaidi/Launcher3#230]
## Description

No available settings when accessing menu (other than "allow screen rotation" which has an **inactive action button**).

## Expected Behavior

See all featured settings.

## Actual Behavior

Only allow screen rotation setting is shown (also this one cannot be used since it's action button is inactive). Also happened when my phone was on 7.1.2.

## Steps to Reproduce

1. Install
2. Access settings menu from main screen
3.
4.

## Environment

* Device: LG Nexus 5X
* Android version: 8.0.0
* Launcher version: 2.1
* Rom: Stock Oreo

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
So you're on Nexus 5X with Oreo but cannot see all settings? That's odd. Can you try clearing app data and cache?

**Comment by bogdansoare9** [comment]
Hi,

Yes. Reinstalled the app a few times and it's the same. Will install it
once more and send you a screenshot.

**Comment by RikKoedoot** [comment]
just delete date of the app that does the same I guess

**Comment by fporte** [comment]
Hi, have the exact same issue on a oneplus x running lineageos (7.1.2). Tried to clear cache/data, reinstall but with no luck.

**Comment by abdullahibneat** [comment]
If you had a read of the F.A.Q. you would have noticed it's stated: "This is normal, only Android 8 users can see the other options. Notification dots are always enabled on Android 6 & 7"

**Comment by fporte** [comment]
My bad, didn't see that, thx for the reply
