### ISSUE TITLE
animated icons feature request

### ISSUE THREAD

**Issue by benzeyf** [amirzaidi/Launcher3#231]
I have seen Lawnchair Launcher support animated icons. For example Google Clock icon. I think this is also in the Pixel launcher. Could it be in it?

**Comment by amirzaidi** [comment]
The only launcher I know that has an animated clock is Action launcher which is closed source and obfuscated heavily. I tried adding it but am getting confused on the roundIcon version

**Comment by nyancrimew** [comment]
@amirzaidi Lawnchair has an animated clock implementation, open source as always :blush:

**Comment by stainslav** [comment]
Hey amir sir, I want to do a request may you build this to an app please because you Know better then is please link for files here:
https://github.com/AlexAltea/nucleus
It's an PlayStation 3 emulator for Android and iOS as well please

**Comment by cyberon** [comment]
I would love this also.
