### ISSUE TITLE
wallpapers and Voice Search Icon missing

### ISSUE THREAD

**Issue by SANJAYSKIM** [amirzaidi/Launcher3#232]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Lenevo p2
* Android version: 7.0
* Launcher version: 2.1
* Rom:

## Logcat

```
your log here
```

**Comment by SANJAYSKIM** [comment]
![screenshot_20170912-023307](https://user-images.githubusercontent.com/25060258/30297059-0cbe3c00-9764-11e7-96f8-529d8d299006.jpeg)
![screenshot_20170912-023307](https://user-images.githubusercontent.com/25060258/30297061-0d2e80c8-9764-11e7-8b7f-c42e99d18c32.jpeg)

**Comment by SANJAYSKIM** [comment]
![screenshot_20170912-024057](https://user-images.githubusercontent.com/25060258/30297106-3771fbee-9764-11e7-919b-9ffc23595eed.jpeg)
![screenshot_20170912-023307](https://user-images.githubusercontent.com/25060258/30297108-378d241e-9764-11e7-8326-85a46f8d4402.jpeg)

**Comment by abdullahibneat** [comment]
The second screenshot doesn't seem to be correlated to Rootless Pixel launcher. Also, I can't understand what your problem is. Can you explain what the actual problem is and, if necessary, provide a screen recording?

**Comment by SANJAYSKIM** [comment]
2nd screen shot nos for reference which is vibe ui(icon are in alphabetical order)

**Comment by RikKoedoot** [comment]
why you copy his message, and amir disabled the wallpaper app icon, idk about the voice, you can long press and click wallpapers to go to wallpaper app

**Comment by amirzaidi** [comment]
This is in fact a feature and not a bug.. it's what the original Pixel Launcher does.

https://github.com/amirzaidi/Launcher3/commit/9b06581bdf384deac0a699f04ab29a4679fbc3e5 (I added Google Now Launcher in the list myself)
