### ISSUE TITLE
Google Fit widget not updating

### ISSUE THREAD

**Issue by alecbe** [amirzaidi/Launcher3#233]
## Description

The Google Fit widget only updates when you open the Fit app.

## Expected Behavior

The widget should periodically update in sync with the Fit app.

## Actual Behavior

Widget only updates after the Fit app is opened.

##

## Environment

* Device:Nexus 5
* Android version:6.0.1
* Launcher version:2.1.0
* Rom:Stock

## Logcat

```
your log here
```

**Comment by gbellini79** [comment]
Same problem here and same device, but I'm experiencing the same behavior even if I'm back to the Google Launcher

**Comment by alecbe** [comment]
After a Play Services update, this problem seems to have gone away. Looks like it was a Google issue.
