### ISSUE TITLE
Launcher stops responding

### ISSUE THREAD

**Issue by SANJAYSKIM** [amirzaidi/Launcher3#235]
## Description

After some day of use launcher stop responding while physical buttons(three button in the bottom for back home and resent app) is working & notification panel(scroll down shortcuts features and setting buttons notifications) is working to fix it i have to stop the app and restart it again.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Lenevo p2
* Android version: 7.0
* Launcher version: 2.1
* Rom: Vibe Ui

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
A logcat might be useful here for amir to determine the issue. Are you still encountering this issue? If yes, post your logcat here.

**Comment by SANJAYSKIM** [comment]
How to get the logcat
