### ISSUE TITLE
picture in picture

### ISSUE THREAD

**Issue by therealbernardo** [amirzaidi/Launcher3#236]
Dear,

thanks for the tremendous  job done and time spend on this.

On Android 8 picture in picture seems not to work correctly. 
Trying to get to the home screen by pushing the center navigation button does not work.
Also in other circumstances it does not work

It is me doing something wrong or is this something that should/could be fixed with an update?

thanks dude

**Comment by abdullahibneat** [comment]
If it's a YouTube video, you need a YouTube Red subscription for PiP to work. Other videos should work fine.

**Comment by therealbernardo** [comment]
you are perfctly right. thanks for the fast feedback.
