### ISSUE TITLE
Turning off airplane mode turns on bluetooth

### ISSUE THREAD

**Issue by tiwaryabhishek** [amirzaidi/Launcher3#237]
## Description
After Toggling Airplane Mode, Bluetooth Turns On Automatically.
Everytime I turn off Airplane mode, the bluetooth keeps turning on eventhough it was not on before I activated airplane mode.

## Expected Behavior
Step1: Turn Bluetooth **off**.
Step2: Turn **on** Airplane mode.
Step3: Turn **off** Airplane mode after few seconds (30sec to 60 sec)
Result: **Bluetooth is off**.

## Actual Behavior

Step1: Turn Bluetooth **off**.
Step2: Turn **on** Airplane mode.
Step3: Turn **off** Airplane mode after few seconds (30sec to 60 sec)
Result: **Bluetooth turns on automatically**.

## Environment
* Device: Lenovo K5 note 
* Android version: 6.0.0 
* Launcher version: 2.1 
* Rom: Vibe 

```
Regards,

**Comment by nyancrimew** [comment]
And how is this related to your Launcher? :joy:

**Comment by abdullahibneat** [comment]
1) Rootless Pixel Launcher does not ask for Bluetooth usage permission, thus it has no effect on Bluetooth options (i.e. turn on/off)

2) I tried anyway on my Nexus 5X, and nothing happened.

I'd suggest you report the issue on Reddit or XDA in the relevant sections for your specific device, and seek for help there. In the meantime please close this issue as this is not related to the launcher.

**Comment by RikKoedoot** [comment]
this isn't launcher related, please close if you're happy

**Comment by tiwaryabhishek** [comment]
Hello All,

But I just now uninstalled the RPL and the toggle buttons are behaving properly. 

Anyways, as you guys say. if this is not a problem with RPL I am just closing the issue.

**Comment by amirzaidi** [comment]
The launcher indeed does not even use Bluetooth in any way or have an Airplane mode toggle.
