### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#238]
Next update will take time?

**Comment by t1m0thyj** [comment]
I'm wondering this too, I like version 2 of the launcher but I miss the app suggestions. It looks like the app suggestions were added back in a commit 2 weeks ago, which hasn't been released yet.

I don't want to be demanding, I realize that this is a free open-source project with a single developer, but I would be interested to know what the plan is for new releases.

**Comment by ghost** [comment]
@t1m0thyj absolutely

**Comment by RikKoedoot** [comment]
@t1m0thyj he didn't want to use the original pixel launcher recent apps, because it was a mess of a code. If there is an open source alternative he may implement it

**Comment by t1m0thyj** [comment]
@rickkode I understood why the recent apps feature was removed, but I think these two commits restored that feature and have not been released yet: 0d3afeee19a8e000fabcd3a85b0921adc559a662, 68dd06d17cd7a7731a26a21cf6c4c8d956cc490d

**Comment by amirzaidi** [comment]
I'm busy with University and a new official release is not high on my priorities right now. There's always new test builds on Telegram, @appforks

**Comment by t1m0thyj** [comment]
I don't want to have to create a Telegram account. Would someone be kind enough to upload the latest test build APK to Google Drive (or somewhere else easily accessible) and share the link?

**Comment by abdullahibneat** [comment]
I recommend you do create one, I upload the latest APK (from 3rd september), But I don't know what the changes are (I just grabbed the APK)
[3 september.zip](https://github.com/amirzaidi/Launcher3/files/1308585/3.september.zip)

_I have no responsibility for any damages (if any) this APK may cause, such as unexpected behaviour._
