### ISSUE TITLE
Cant go back to stock launcher on s7 edge

### ISSUE THREAD

**Issue by andy0105781** [amirzaidi/Launcher3#239]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```
Ive tried deleting oreo launcher and selecting stock launcher but still nothing.any ideas?

**Comment by RikKoedoot** [comment]
can you screen record this issue? and try to change home settings in settings, apps, Gear icon, home app

**Comment by amirzaidi** [comment]
Settings -> Apps -> Default Apps -> Launcher/Homescreen -> TouchWiz

**Comment by andy0105781** [comment]
Tried that and still wont go off.looking like a factory reset

**Comment by pablomoises** [comment]
Even if I was not continuously asked to choose which launcher to use when pressing Home (other devices will ask until you set selection as default), I had not problems to change launcher on settings/apps/defaultapps on Samsung S8

**Comment by RikKoedoot** [comment]
maybe try to install another launcher, then press home, then the menu will pop up again, you select the launcher you want and then you delete the launcher you just downloaded
