### ISSUE TITLE
Motorola icon layout always 4 wide

### ISSUE THREAD

**Issue by peterdcrees** [amirzaidi/Launcher3#24]
Installed and working on Moto X Style .
App drawer spacing is way too large.  
On Google Pixel app drawer is 5 icons across by 6 down.
On Moto X it's only 4 across by 5 down with large white space  between icons:

![Screenshot](https://user-images.githubusercontent.com/24588234/27120700-70ad5dee-5106-11e7-96fa-bd014cf790f8.png)

**Comment by RikKoedoot** [comment]
Same problem on moto g4 plus

**Comment by jleslie97** [comment]
On the s8 I get a 5*6 grid. But because of the aspect ratio there is probably enough room for a icon inbetween each space. Good work though getting the pixel features ported :D

**Comment by Aphoe1** [comment]
Similar issue on HTC M8 with 4 icons across. Think issue affects phones with display 5 inches and under.

**Comment by peterdcrees** [comment]
@Aphoe1 The Moto X has a 5.7" 1440 x 2560 screen at 520 ppi so there is a lot of space to fit another row and column.

**Comment by dpavani** [comment]
The issue with motorola stock ROMs is another apk, LauncherConfig.apk. It is it that configure the 4x4 grid. Afaik, you just have to delete it (if you have root). Otherwise, there is no way around.

**Comment by victormunduruca** [comment]
Isn't there a way to not consider LauncherConfig.apk on those devices? In simillar fashion to custom launchers

**Comment by karthikmohan** [comment]
5x5 grid with @amirzaidi launcher. I'm on 7.1.1 and its easy to reduce dpi from settings.
So i guess it is not a bug anymore. and btw great work @amirzaidi .

For your kind info. I'm using a non rooted Moto X Play. All stock.


![screenshot_20170618-121246](https://user-images.githubusercontent.com/25052382/27257800-9a494840-541f-11e7-8c4b-60bfb3b70f89.png)
![screenshot_20170618-121254](https://user-images.githubusercontent.com/25052382/27257799-9a481790-541f-11e7-9d88-faef2e12ce99.png)

**Comment by victormunduruca** [comment]
@roguenemesis I've tested this before, on 7.0 and it didn't work even on real high dpi!

**Comment by amirzaidi** [comment]
Tried 1.5?

**Comment by victormunduruca** [comment]
Yes, it worked fine! forgot to delete the comment :)

**Comment by victormunduruca** [comment]
Thank you!
