### ISSUE TITLE
Change default icons in launcher

### ISSUE THREAD

**Issue by bigblueberrie** [amirzaidi/Launcher3#240]
I downloaded the latest update of Launcher3 but it seems the stock android icons disappeared and have been replaced with the phone's default icons. Is there anyway I can replace them.

**Comment by RikKoedoot** [comment]
can you please send a screenshot so I understand what you mean

**Comment by bigblueberrie** [comment]
![screenshot_20170916-173726](https://user-images.githubusercontent.com/32005462/30511163-c04bde0e-9b05-11e7-8612-9ec13ff3d9b0.png)

**Comment by bigblueberrie** [comment]
Used to have stock android icons for dialler, contacts etc. Using Huawei p10 if that helps.

**Comment by amirzaidi** [comment]
Did you install a theme from the Huawei theme store?

**Comment by bigblueberrie** [comment]
Nope, didn't install anything else other than the updated Launcher3 earlier.

**Comment by amirzaidi** [comment]
I find it very weird that you used to have the stock icons before as I don't have any icons hardcoded in the launcher.. must be a system wide theme somewhere

**Comment by abdullahibneat** [comment]
Do you have any custom ROM installed? Judging from [this](https://i.gadgets360cdn.com/large/p10_main1_1487840496547.jpg?output-quality=80) screen I found online it appears there are no Android Stock icons by default on the device.

**Comment by bigblueberrie** [comment]
Fascinating, I managed to fix it. Apparently the earlier releases allow you to apply the Huawei theme (in my case, a theme with stock android), but the new release blocks it. So applying the theme, reinstalling the older version and then installing the latest version helps. Cool!

**Comment by bigblueberrie** [comment]
![screenshot_20170917-114010](https://user-images.githubusercontent.com/32005462/30517803-089210a6-9b9d-11e7-98e5-8e57f3d1e267.png)
