### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#241]
New icon for Google Play Games Please

**Comment by abdullahibneat** [comment]
As the original Pixel Launcher does not include any icon pack, RPL won't include it either. Also, what is the issue with the Play Games icon? It looks fine to me: https://photos.app.goo.gl/Uk6YBYqFlydIi2fq2

**Comment by userNeptune** [comment]
in mine it is not circular

**Comment by userNeptune** [comment]
https://photos.app.goo.gl/QMo9OHe972WN6wwq1 as?

**Comment by abdullahibneat** [comment]
Have you updated to the latest version? Have you tried clearing the cache?

**Comment by userNeptune** [comment]
version 2.1, yes I already cleared the cache

**Comment by ghost** [comment]
@MrLuckas uninstall and reinstall the app, that works for me.

**Comment by userNeptune** [comment]
Did not work
