### ISSUE TITLE
Google app feed

### ISSUE THREAD

**Issue by Ksu74** [amirzaidi/Launcher3#243]
Google app is supposed to have several feeds, one "normal" and one for "upcoming". When using some launcher, this is gone. Nova have it, Google Now launcher don't. This launcher don't. I tried with several accounts also, but don't get two feeds. The same moment I change launcher to for example older version of pixel launcher official found on APK mirror, I get feeds back. Please fix.

**Comment by RikKoedoot** [comment]
can you please be more specific and show us some comparison screenshots?

**Comment by Ksu74** [comment]
![nexus2cee_screenshot_20170816-232927](https://user-images.githubusercontent.com/32089297/30588130-dd071e1e-9d35-11e7-9a12-f6852e29e6de.png)
![27129472-5b68afc6-50fa-11e7-9795-15f21db6dab8](https://user-images.githubusercontent.com/32089297/30588126-d8cbbe22-9d35-11e7-8567-a767a2243d03.png)

**Comment by Ksu74** [comment]
First pic is what it should be like.Second pic is how it is on some launchers,including this one.

**Comment by RSNYC** [comment]
I'll.z xcc now from ccgtxedh mjdfsgr.ffscjc

**Comment by Ksu74** [comment]
As far as i know the Google Now launcher, Lawnchais launcher and this launcher have this problem. The only launcher i have tested this to work on is Pixel launcher and Nova. On them you have two tabs on the bottom,one for everything and one for upcoming. This isnt Google problem,but something with the launchers.If i change launcher the tabs is gone the same second.When i change back to pixel or nova,they come back again right away.So this have to be launcher problem.

**Comment by LinuxLlama** [comment]
You can't control what Google shows. It's Google's fault. Nova Launcher and others have gotten this feedback and that's the response.

**Comment by sosiger** [comment]
For me, the feed says "_Can't reach your feed at the moment_" the reason is probably my phone but this issue is annoying because when I have this launcher installed the "upcoming" page disappears even in the google app.

**Comment by RikKoedoot** [comment]
this is a problem with launcher with Google now. if you don't use a launcher with Google now it will return in the Google app, after deleting data of app

**Comment by baruchin** [comment]
[Check this out](http://www.androidpolice.com/2017/06/14/ever-happened-googles-dual-tab-feed-upcoming-update/) 
I think this answer the question of why in some devices or launchers.

**Comment by Ksu74** [comment]
Well, for me the feeds come back the same moment I go back to the pixel launcher again. Only this launcher, lawnchair and Google now launcher make this problem for me.
