### ISSUE TITLE
App drawer

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#244]
## Description
App drawer gray color, differences between Launcher3 and Pixel Launcher. Here the comparison.

![drawer](https://user-images.githubusercontent.com/31294663/30605469-6c681d7a-9d2b-11e7-8fd9-34369a706c58.png)

* Device: Nexus 6P
* Android version: 8.0.0
* Launcher version: 2.1
* Rom: -

**Comment by RikKoedoot** [comment]
good post

**Comment by abdullahibneat** [comment]
If you know coding in Java, you can try to push your code with the right grey shading to the repository and wait for Amir to accept/reply.

**Comment by amirzaidi** [comment]
Is this the Oreo version of Pixel Launcher?
