### ISSUE TITLE
App drawer blue bakground

### ISSUE THREAD

**Issue by eturk1** [amirzaidi/Launcher3#245]
App drawer has blue background, not light grey, can't read text.

![screenshot_20170920-223701](https://user-images.githubusercontent.com/525280/30680771-5c767c96-9e56-11e7-85c7-fbd610cdac98.png)

## Environment
* Device: Samsung Galaxy S2 tablet 2016
* Android version: 7.0.0
* Launcher version: 2.1
* Rom: stock

**Comment by abdullahibneat** [comment]
Try clearing cache and rebooting your device.

**Comment by RikKoedoot** [comment]
this is a known issue, read #112

**Comment by abdullahibneat** [comment]
@rickkode I think you linked the wrong issue

**Comment by eturk1** [comment]
#112 is about "suggestions" in app drawer

**Comment by Rishoj** [comment]
This is a duplicate of #122, not #112.
