### ISSUE TITLE
Navigation buttons barely visible on the Galaxy S8.

### ISSUE THREAD

**Issue by cyberon** [amirzaidi/Launcher3#246]
On the Gallery S8 the navigation buttons are always gray, making them extremely hard to see on some wallpapers,
![screenshot_20170922-032234](https://user-images.githubusercontent.com/683597/30727018-695521ce-9f46-11e7-92be-a9a6fd78b27c.png)
 is there any chance to fix it?

**Comment by cyberon** [comment]
Nova Launcher has this issue fixed, Action Launcher and GNL don't.

**Comment by pablomoises** [comment]
+1 with same dificult to see navigation buttons on S8

**Comment by powduh** [comment]
Looks the exact same on LG Stylo 3 plus on Metropcs running rooted stock room. Older versions didn't have a color change at the bottom of the screen... Is it possible to fix this?

**Comment by Bicet** [comment]
I have the same exact problem on my S8, and so i made an overlay for it.
You can grab it here: http://www.cloudfarm.it/white-navbaricons.apk
Install it and reboot your phone, I don't know if it will work on LG.

**Comment by cyberon** [comment]
Bicet won't this slow down the phone?

**Comment by powduh** [comment]
It isn't exactly the navbar buttons I would change. I'd rather the background for the navbar be transparent so the wallpaper actually extends through like on my stock launcher. I'll post pictures to show what I mean when I get a chance.

**Comment by powduh** [comment]
[<a href="https://ibb.co/dF1N3w"><img src="https://preview.ibb.co/focvOw/Screenshot_2017_10_14_15_21_30.png" alt="Screenshot_2017_10_14_15_21_30" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>freeimagehost</a><br />](url)[<a href="https://ibb.co/cCzTAb"><img src="https://preview.ibb.co/dU96wG/Screenshot_2017_10_14_15_22_15.png" alt="Screenshot_2017_10_14_15_22_15" border="0"></a>](url)

If you notice, in the picture of the pixel launcher, the navbar background is transparent, however it isn't as seamless as the stock launcher. The pixel launcher from nougat didn't have this issue. I was just hoping it could be worked out in this version also.

**Comment by Bicet** [comment]
> Bicet won't this slow down the phone?

Not that I know, give it a try, you can always uninstall it!

**Comment by possum-enjoyer** [comment]
Hey Bicet i've tested it with my note 8 runnig 7.1. it works perfect thank you.
