### ISSUE TITLE
Round icon request

### ISSUE THREAD

**Issue by fenglipop29** [amirzaidi/Launcher3#247]
The google apps icon in nexus 6p are all square. I can't change these icons. Only pixel can do that. Is it possible to make round icons just like pixel's?

**Comment by remiquezada** [comment]
Go to setting by tapping and hold home screen.  There's an option to change icons from default to round.

**Comment by fenglipop29** [comment]
Got it. Thanks!

**Comment by sergeysova** [comment]
@fenglipop29 close issue

**Comment by ghost** [comment]
Hola! Algunos iconos redondos empiezan a verse borrosos, como por ejemplo: Play store, Google maps, documentos de Google, etc, podrían corregir eso?

**Comment by RikKoedoot** [comment]
@thezayko English please
