### ISSUE TITLE
Did app suggestion bar in the app draw got removed?

### ISSUE THREAD

**Issue by m4au312** [amirzaidi/Launcher3#248]
![screenshot_20170925-202019](https://user-images.githubusercontent.com/32263337/30804095-6e0e4a88-a22f-11e7-985d-ad0ee10fcc11.png)
I am on V2.1, thank you!

**Comment by t1m0thyj** [comment]
It's not in 2.1, but if you download the latest test build from the developer's Telegram channel (https://t.me/appforks), it has the feature added back. It works a little differently from Google's version, it only adds apps to the list when you open them from the app drawer.

**Comment by abdullahibneat** [comment]
If you had a look at other issues, i.e. #112, you would have found out the above information. Please search before raising unnecessary issues.

You may close this issue if you're happy.
