### ISSUE TITLE
Request. All Circular icon

### ISSUE THREAD

**Issue by carloszapruder** [amirzaidi/Launcher3#249]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
This is not possible, as the launcher fetches the round version of the icon from the different apps. The system does not use any mask to cut out default icons.

If you want a circular icon for a specific app ask the developer of that app to include it with future builds.

**Comment by carloszapruder** [comment]
Thank you for the answer. Keep up to work, i love this launcher.
