### ISSUE TITLE
Is icon pack support coming? 

### ISSUE THREAD

**Issue by siez** [amirzaidi/Launcher3#25]
Some icons are too "kitkat" like - Contacts, Messaging, Updater.

**Comment by amirzaidi** [comment]
Don't count on it. I did just port the Pixel icons for everyone though, so if you use the Google Apps you'll have the same icons.

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/issues/4
If you have a great idea for icon pack support then add it here.
