### ISSUE TITLE
Daily Wallpaper feature not working

### ISSUE THREAD

**Issue by kuberrohilla** [amirzaidi/Launcher3#250]
Daily wallpaper feature of google's wallpaper app is not working. Wallpapers are not changing daily even when i have turned it on. It was working fine with the version 1.5. I am using Android M. I have tried re-installing your launcher and wallpaper's app as well, that didn't help.

**Comment by abdullahibneat** [comment]
Unless someone else can confirm this, You'll have to wait for tomorrow so I can check whether it changes the wallpaper automatically or not. Could you share your device model and android version please?

**Comment by kuberrohilla** [comment]
Device - Asus Zenfone 2 ZE551ML
Android Version- 6.0.1

**Comment by abdullahibneat** [comment]
On Nexus 5X, android Oreo, it changed the wallpaper by itself. Can you try rebooting your device and see if that changes the wallpaper?

**Comment by kuberrohilla** [comment]
Oh...i changed it already. Will try it out tomorrow.

**Comment by kuberrohilla** [comment]
Restarting the phone didn't help
