### ISSUE TITLE
How to Set Weather

### ISSUE THREAD

**Issue by Anbhuthiagarajan** [amirzaidi/Launcher3#251]
How to Set Alarm in this launcher and how to set weather widget

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
1. Nothing to do with the launcher: the alarm can be set from your Clock application.

2. If you long-press on the home screen, and then select widget at the bottom, look for the clock widget and drag to the home screen.

**Comment by RikKoedoot** [comment]
@abdullahibneat is right and please next time use the layout for the issue
