### ISSUE TITLE
App icons

### ISSUE THREAD

**Issue by benzeyf** [amirzaidi/Launcher3#254]
Hello!
When some applications are updated, the pixel icons change to regular icons. Application shortcuts are missing.

OS 7.1.1
Android One device

**Comment by RikKoedoot** [comment]
try clearing cache of the launcher

**Comment by benzeyf** [comment]
no solution

**Comment by RikKoedoot** [comment]
@benzeyf hmm, strange

**Comment by benzeyf** [comment]
Example, the Google Translate app icon that looks round now is have a regular icon. I tried the same with lawnchair.

**Comment by RikKoedoot** [comment]
try reinstalling, or deleting data of launcher
