### ISSUE TITLE
Can't show Google Now

### ISSUE THREAD

**Issue by shangmaumau** [amirzaidi/Launcher3#255]
## Description

When updated Google App 7.12.22.21 arm64, Google Now can not show again.

## Expected Behavior

Update Google App to version 7.12.22.21.

## Actual Behavior

Can not right slide.

## Steps to Reproduce

1. Open Google Play Store for Android.
2. Check my Apps.
3. Update Google App to the Latest version.
4. Back to Launcher3 main page, can not slide to right to show Google Now.

## Environment

* Device: Redmi Note 4 mido.
* Android version: 7.1.2, Lineage OS 20171001.
* Launcher version: 2.1.0
* Rom: Lineage OS 14.1 for mido.

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
Have you tried clearing cache for the launcher? Did you have the Google page before? Have you tried reflashing manually the GApps (nano or higher)?

**Comment by shangmaumau** [comment]
The issue has solved, I don't know why, but I can slide right to Google Now now.
