### ISSUE TITLE
Phone and Contacts app icons

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#256]
So my phone has stock Google Phone and Contacts apps. But they're somehow not really official Google apps? It's kinda hard to explain but the thing here is their app icons are still the old Phone and Contacts icons (KitKat style). They won't update on Play Store because again, Motorola app weirdness. They aren't really Google apps, rather clones of those apps which aren't getting updated.

THE REQUEST: Add Google Phone and Google Contacts icons in the launcher so that whatever Phone and Dialer icons are on the phone, they'll be Google styled automatically.

**Comment by RikKoedoot** [comment]
I have the same issue, they are the aosp ones I guess and those aren't getting updated by Motorola, but I don't think amir will add this to the launcher, would like it tho

**Comment by abdullahibneat** [comment]
Might be because I'm on Nexus 5X, android Oreo, but my icons look all right to me... https://photos.app.goo.gl/79j8BHFPf4jOzH5n1

**Comment by nikkomercado** [comment]
@abdullahibneat Yeah, it's because your Phone and Contacts apps get updated via Play Store. The point is my device's Phone and Contacts don't get updated leaving the icons old style.
