### ISSUE TITLE
Animation Issue - From Google Now and press "Back" key

### ISSUE THREAD

**Issue by wpkfol** [amirzaidi/Launcher3#257]
## Description
There is a animation issue when from google now (swipe left) and pressing the "back" key. 

## Expected Behavior
I believe the animation should be the same as pressing the "home" key

## Actual Behavior
When the "back" key is pressed, the animation is like closing closing an app

## Steps to Reproduce

1. Swipe left to Google Now
2. Press "back" key

## Environment

* Device: OnePlus 5
* Android version: 7.1.1 / Oxygen OS 4.5.10
* Launcher version: 2.1
* Rom: Stock Rom

**Comment by nikkomercado** [comment]
I think the expected behavior is nothing happens when pressing back.

**Comment by RikKoedoot** [comment]
@nikkomercado well it's expected to go to last activity, and now that's the launcher

**Comment by korbendalos** [comment]
Reproduced on my device as well:
Samsung galaxy note 5
Android 7.0
Launcher version 2.1
Stock rom

**Comment by coditva** [comment]
Can confirm.
Moto E4 Plus, 7.1.1

**Comment by amirzaidi** [comment]
This must be because of a Google App update, it started happening for me too, interesting..

**Comment by PR1D3S** [comment]
Now come on amir bro push some upgrade I m waiting for adaptive icons from last one and half month..
