### ISSUE TITLE
Like the pixel 2

### ISSUE THREAD

**Issue by hetulkatyal** [amirzaidi/Launcher3#259]
## Description

Can you please release an update to make it look like the pixel launcher on the new pixel 2 and pixel 2xl

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by AxiK101** [comment]
that will probably happen after official app leaks, expect future update

**Comment by ghost** [comment]
I am glad and I see that I posted this need, I would also like to see the pixel launcher as pixel 2

**Comment by NathanFrederick** [comment]
I would like to see the new pixel launcher as pixel 2 as well

**Comment by RikKoedoot** [comment]
please close this issue, this won't happen untill the real pixel launcher APK is available

**Comment by AxiK101** [comment]
oi people, we will have to wait for official apk of newest pixel launcher to be released like on apkmirror, so that the developers can make the modifications we need to get it on none pixel phones.

**Comment by acofalc** [comment]
i guess this is pixel 2 launcher apk? 
https://www.xda-developers.com/get-google-pixel-2-pixel-launcher-bottom-search-bar/

**Comment by hetulkatyal** [comment]
It's released, check xda

**Comment by dimitrieh** [comment]
isn't working yet (requires root), also would like to see the waves live wall paper included 😄 

plus if launcher 3 updates... all configs should stay right? :)

**Comment by NathanFrederick** [comment]
I installed the pixel launcher 2 update app it works on my phone and my phone is not rooted

**Comment by NathanFrederick** [comment]
I ment pixel launcher 2 APK

**Comment by AxiK101** [comment]
@dimitrieh dude no root required, also the new lwp have been ported today for Android 6+7, check out xda

**Comment by t1m0thyj** [comment]
The launcher on XDA works without root, but on the Moto Z Play the app drawer is 4 icons wide instead of 5 which wastes a lot of space, even though the home screen is 5 wide.
