### ISSUE TITLE
No dual tab on the bottom of Google Now feed.

### ISSUE THREAD

**Issue by cyberon** [amirzaidi/Launcher3#26]
Hi, on Action Launcher i was getting a dual tab on the bottom, now its a single feed.
![screenshot_20170614-120702](https://user-images.githubusercontent.com/683597/27129472-5b68afc6-50fa-11e7-9795-15f21db6dab8.png)

**Comment by SethuSenthil** [comment]
This should be fixed In the next update

**Comment by cyberon** [comment]
Still happening on v1.3.

**Comment by amirzaidi** [comment]
Try action launcher again, this seems to be a system-side change. Pretty sure there's no difference between the two with the tabs.

**Comment by RWOne** [comment]
It is server side, heck I just got search shortcuts on my now pane, and only on this launcher, on the stock Google now launcher, nada.

**Comment by RWOne** [comment]
And with the just released Google app beta update, lost search shortcuts icons again.

Wish they'd make up their minds .... ☺️
