### ISSUE TITLE
Animation of app drawer lag

### ISSUE THREAD

**Issue by naymapl** [amirzaidi/Launcher3#262]
Everything working well just except one thing. When you open app drawer animation is so lagging. But for example when you are on main svcreen and swipe left to google now animation is perfect. No idea what is wrong.

## Environment
Device: Xiaomi Mi A1 Android One
Android version: 7.1.2
Launcher version: 2.1.0
Rom: Stock Rom

**Comment by RikKoedoot** [comment]
this is normal, lower end devices lag more, and I thibk (not sure) that mi a1 is lower end device

**Comment by naymapl** [comment]
You're wrong. This phone has snapdragon 625, 4gb ram and 64gb ROM. Have no issues with others launchers.

**Comment by jleslie97** [comment]
@naymaeu Clearing the launcher data sometimes helps. 

Also accessibility features may need to be disabled as they have to constantly interrupt the CPU so you can receive consistent accessibility, for when you need them. so turn this off in settings and retest. 

This app cannot be installed on an unrooted pixel device. Android 1 smartphones and their launcher may have some similar conflicts as they are similar to the pixel launcher.

If you only want the Google drawer and pixel bar/weather widget. nova with the companion apk (APK mirror not on the play store) and pixel widget. Is an excellent alternative. hope that helps.

**Comment by kuberrohilla** [comment]
Go to the Developer Options and scale down the Animator duration scale to 0.5x. It helped in my case.

**Comment by amirzaidi** [comment]
Check if you have any Accessibility services like a password manager enabled, those are known to cause lag

**Comment by crisgdo** [comment]
I have a mi a1 and its own app drawer has lag. It's a bug.

**Comment by crisgdo** [comment]
I disabled enpass on accessibility and it works to me. thank you @amirzaidi Amirzaidi

**Comment by bb2k** [comment]
Disabling enpass in accessibility also worked for me
