### ISSUE TITLE
I hope The pixel 2 update comes soon 

### ISSUE THREAD

**Issue by NathanFrederick** [amirzaidi/Launcher3#263]
Add pixel 2 update I like the New pixel 2 launcher i tried Nova launcher and made my screen look like the pixel 2 it's awesome  I like it better then the original pixel launcher don't get me wrong original pixel launcher is awesome but I prefer pixel 2 launcher the new launcher

**Comment by nikkomercado** [comment]
Yes.

**Comment by RikKoedoot** [comment]
this will come when the real pixel launcher gets uploaded on a site like APK mirror, untill then use Nova I guess, please close the issue
