### ISSUE TITLE
Weather does not show on home screen

### ISSUE THREAD

**Issue by madmax2** [amirzaidi/Launcher3#264]
## Description
Followed the suggestion of how to get weather to show on homescreen
but it does not show..

## Expected Behavior
weather should show on home screen

## Actual Behavior
Still shows the date on the home screen.

## Steps to Reproduce

1.Enable location
2.Enable Location > google >permissions > location 
3.Refresh Google Now feed twice.
4.Made sure the weather card is on the Google Now feed and it is showing on the feed.

## Environment

* Device:Oneplus one
* Android version:8.0
* Launcher version:2.1
* Rom: aosp_bacon-8.0.0-20170930.agentfabulous.zip
https://androidfilehost.com/?w=files&flid=211773
https://forum.xda-developers.com/oneplus-one/orig-development/rom-aosp-oreo-oneplus-one-t3666741

## Logcat

```
your log here
```

**Comment by RikKoedoot** [comment]
this is strange, you tried everything that is needed

**Comment by nikkomercado** [comment]
You need an internet connection and wait for hours. Weather won't show up immediately. Wait for it.

**Comment by madmax2** [comment]
@nikkomercado I do have an internet connection and connected by wifi..
I have been waiting for a week now since installing it.

**Comment by nikkomercado** [comment]
@madmax2 Try setting Location to 'High accuracy'.

**Comment by madmax2** [comment]
@nikkomercado high accuracy is already enabled

**Comment by nikkomercado** [comment]
@madmax2 Have you tried reinstalling the launcher? Or rebooting your device?

**Comment by madmax2** [comment]
@nikkomercado I will try this..
the problem is the weather does show in the google now feed, it is just not updating in the home screen widget..
so something is wrong..

maybe if amir read this, then would more about the technicality of what is going on..

==
what phone and android rom are you using?

Do you still have the original launcher 3 v8.0.0 (from lineage os) on your system along with this pixel launcher3?

how did you install the launcher apk?

**Comment by madmax2** [comment]
@nikkomercado Okay I try what you said but it is still not showing the weather on the home screen

**Comment by amirzaidi** [comment]
Try changing your system language and Google app's language to English (US), it breaks for me when I set it to a not supported country

**Comment by madmax2** [comment]
where is the setting to change language for both options?

For the system, I found and change it to this
System > Languages & Input  > Languages > English (United States)

For google apps languages I found this..
Open google app,
Click on Hamburger icon > settings > Search Language > English (US)

Please confirm if both of these changes are correct and the language settings you are talking about?

NOTE: I applied those two settings but still not getting any weather info on the home screen.

**Comment by madmax2** [comment]
@amirzaidi I change the settings to language  English (US ) as mention in my previous post
but the weather is still not showing on the home screen..

please let me know if those settings are the correct settings that I needed to change.

if this is correct changes then it is not working

Can you please debug this issue further?

**Comment by amirzaidi** [comment]
Do you get the weather notification and the weather card in your Google Now feed?

**Comment by madmax2** [comment]
@amirzaidi Yes.
it does show the weather card and notification in google now feed

It is just not updating in the widget.
Still shows the date.

**Comment by madmax2** [comment]
@amirzaidi Any idea what else I can try to fix this problem?

**Comment by amirzaidi** [comment]
It might be the ROM? Idk if you have the time for it you should try an older ROM, maybe the weather intent isn't being broadcast properly.

**Comment by madmax2** [comment]
@amirzaidi I just installed the new pixel 2 launcher and I can get the weather showing..
so there is something wrong with this launcher not working with my Oreo rom.

**Comment by kengraWin** [comment]
good
