### ISSUE TITLE
Google Allo app icon

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#265]
Google Allo icon (and apps with icons alike) shouldn't get the circular border thing around it. 

See image:
https://photos.app.goo.gl/oxrrabCbDu1qSy7H3

Expected behavior:
Make it however Pixel displays the Allo (and alike) icon on the Pixel Launcher.

**Comment by abdullahibneat** [comment]
Well, Allo's app has a teardrop icon, not a circular icon, so the white border is expected. However, with the teardrop icon I expected it to be like the Phone app, Message app and Chrome app, without any border. This is not the case, as white border is present even with teardrop shape: https://photos.app.goo.gl/XE7uly6uzU2xedG52

**Comment by AxiK101** [comment]
the white plate etc is designed by google and that's the way they want it to be. this launcher does not support icon packs so you will get stock icons

**Comment by nikkomercado** [comment]
@AxiK101 Then how can you explain this Pixel screenshot: https://venturebeat.com/wp-content/uploads/2016/10/google_pixel_messaging_apps.png?fit=1600%2C850&strip=all&w=640

**Comment by amirzaidi** [comment]
This is expected behaviour, blame Google for being f$@!tarded by giving Allo this icon.. check a Google Pixel and you'll see it also has this stupid icon.

@nikkomercado that screenshot is outdated, Allo was recently updated with the 'adaptive' icon
