### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#266]
Never again will update  :frowning:

**Comment by t1m0thyj** [comment]
The project isn't abandoned, the developer is just busy with university right now (#238).

In the meantime, you can download the latest test builds from their Telegram channel: https://t.me/appforks

**Comment by amirzaidi** [comment]
Well, sorry for my absense, but university comes first now, I'm still working on other stuff in my free time but it's so little and spread apart that I can't provide a new big update. I like where 2.1 is, it's very stable and the little issues that do exist are so minor and only on specific devices. Once I have the time to make sure a new version is as stable as 2.1 I'll dedicate more time for sure.

**Comment by userNeptune** [comment]
ok, update that I'm talking about and the new pixel launcher :sweat_smile:

**Comment by NathanFrederick** [comment]
I can't wait the new pixel 2 big update as well
