### ISSUE TITLE
weather widget constantly appears on the notification bar

### ISSUE THREAD

**Issue by fenglipop29** [amirzaidi/Launcher3#267]
It's very annoying Pixel launcher forced to put the weather widget on notification bar.  I can't find a way to turn it off. Every time I slide it away, about two hours later it appears again. Any solutions?

**Comment by abdullahibneat** [comment]
What weather notification? I never saw any on Nexus 5X and RPL.

**Comment by fenglipop29** [comment]
Like this.
https://drive.google.com/open?id=0B7hVDtMBrZI0OGdZWVdYYkhURm8
https://drive.google.com/open?id=0B7hVDtMBrZI0N1JXNk5OZUt6SkE
Can't make it stop appearing.

**Comment by abdullahibneat** [comment]
Try with [these](https://superuser.com/questions/802804/disable-google-now-weather-notifications-only) solutions.

**Comment by t1m0thyj** [comment]
Personally I think this is a feature, not a bug, because I like having the weather in my notification bar. I wouldn't have a problem if this was made optional, but would be disappointed if it was removed.

**Comment by amirzaidi** [comment]
Well it's not done by my Launcher but it's done by the Google app..

**Comment by fenglipop29** [comment]
Well, yeah. I reset the Google feeds, and click "not interested in weather" or something, and it's not showing anymore.
