### ISSUE TITLE
CHOOSE TO ENABLE/DISABLE WHEATER WIDGET FROM HOMESCREEN

### ISSUE THREAD

**Issue by TaWa82** [amirzaidi/Launcher3#268]
Hi, the launcher is amazing, very functional, slim and fast on my nexus 6p. I was wondering if there was a possibility to implement it with a spell that lets you choose to enable or disable weather widget on the home screen bar. Unfortunately, as many says, it does not update automatically and is not functional, and i prefer many others. It would be convenient to be able choose to view only the date. Tks

**Comment by amirzaidi** [comment]
Disable weather updates in Google Now and it will disappear from the home screen as well.

**Comment by TaWa82** [comment]
Hi Amir, thank you for your kind and quick response. How can i do this?  I have already disabled the google feed because I do not need it and I do not use it, in fact it would be nice to disable the entire sliding board on the left side of the home (even if it is not a big deal). So I already have all the cards of the feed disabled. I do not see other settings regarding the weather in the google now general settings now.

**Comment by madmax2** [comment]
@TaWa82 if you are gonna disable the feed and the weather then what is the point of installing the pixel launcher?
Might as well just use the default launcher on your system..

**Comment by TaWa82** [comment]
Hi, pure aesthetic ....... in my nexus 6p google now launcher updated with terrible graphics and icons..... I appreciate google experience and wanted to try a launcher similar to pixel, maintaining google settings. Nova or other alternative launchers are valid but too heavy, just something as simple and slim as the AMIR launcher, which works perfectly and stable in my phone. Of course, I still solved my problem reactivating the feed and manually selecting the weather, then turning it off. With a last refresh the weather widget has disappeared.
So thanks again to Amir
