### ISSUE TITLE
Can not open apps settings

### ISSUE THREAD

**Issue by RonnieBlaze** [amirzaidi/Launcher3#269]
When ever i try to open the apps settings it seems to be opening the settings from the default launcher.

Nexus 6p running stock 7.1.2

**Comment by flipflop97** [comment]
I also can't open settings on my laptop running 7.1.2. But instead of opening different settings, the settings icon doesn't even show up.

On my Nexus 5X on 8.0.0 the settings are working fine though.

**Comment by abdullahibneat** [comment]
I might be wrong, but maybe the setting button triggers the settings of the default launcher. Can you try setting RPL as default launcher and see if it works?

**Comment by RonnieBlaze** [comment]
abdullahibneat,  I think you are right it is opening the default launcher settings that i think it is opening also..

And i have tried setting RPL as the default... but that i have not tried yet is making RPL a system app.
