### ISSUE TITLE
Cant install, App not Installed

### ISSUE THREAD

**Issue by tinchox1717** [amirzaidi/Launcher3#270]
Can anyone help me ?

i cant install the launcher, i download the last and previous launcher and it say App not Installed.

im on nitro 8 last build , just did a clean install with gapps 8.0

i cant get the dots or the icons shape, this rom have pixel launcher but i dont think that work, i cant find pixel launcher on notification special access

**Comment by amirzaidi** [comment]
You'll have to completely remove the orginal Pixel Launcher.
