### ISSUE TITLE
Google calendar on dock, don't update the number of the day.

### ISSUE THREAD

**Issue by carloszapruder** [amirzaidi/Launcher3#278]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by abdullahibneat** [comment]
You mean the Google Calendar Icon not updating the icon to reflect the calendar day? It works for me on Nexus 5X, Android Oreo and RPL 2.1
![screenshot_20171021-160550](https://user-images.githubusercontent.com/7048592/31853032-eb4ea1b0-b679-11e7-96f7-d036fa4a2498.png)

> Please do fill out the form when posting new issues. The from is designed to narrow down the problem to a specific set of devices, thus helping the developer find a fix quicker.
