### ISSUE TITLE
No drop shadow on the date widget

### ISSUE THREAD

**Issue by jonairma** [amirzaidi/Launcher3#279]
I notice there's no drop shadow on the date widget. But there is shadow on the weather widget.
Can someone help me? I prefer the date widget rather than the weather widget

I tried decompiling the apk but don't know which xml to edit to enable the date shadow :P

**Comment by amirzaidi** [comment]
Could you send me a screenshot of the official Pixel Launcher and from this launcher?

**Comment by jonairma** [comment]
Sure, here you go.

AmirZ:
![screenshot_20171027-152024](https://user-images.githubusercontent.com/33144052/32094786-2d9dc1bc-bb2b-11e7-8e3d-b951f961d2f1.png)

Google:
![screenshot_20171027-093547-2](https://user-images.githubusercontent.com/33144052/32094801-377f82ba-bb2b-11e7-89ca-fb663e870e16.png)
