### ISSUE TITLE
Can't import to Android Studio

### ISSUE THREAD

**Issue by cMoney667** [amirzaidi/Launcher3#28]
I am trying to import the project into Android Studio and it's telling me that the Gradle settings are not configured. It says to click 'OK' to use the Gradle wrapper but when I do that it comes back as corrupted. Please help, I am new to android and want to get my feet wet and try to help with this project.

Thanks in advance

**Comment by Trak-X** [comment]
You are using a new AS version and you need to update the gradle plugin. Same happened to me.

in the build.gradle file change :

repositories {
        jcenter()
        //mavenCentral() - comment this and add the jcenter above 
    }

dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3' - update the gradle plugin as per your needs
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.0'
    }

**Comment by cMoney667** [comment]
@Trak-X Thank you, that was it! it's working now!!

**Comment by amirzaidi** [comment]
Use the compat branch, that's the branch where I've been building. The master one is to keep compatiblity with AOSP ROMs that want to import the commits
