### ISSUE TITLE
5 grid for oppo find7 omnirom

### ISSUE THREAD

**Issue by BosESouNDZA** [amirzaidi/Launcher3#280]
## Description

it show 4 grid in homescreen can you make it 5 grid on Omnirom 7.1.2 OPPO find7 android nougat

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:OPPO FIND7
* Android version: 7.1.2
* Launcher version:2.1.0
* Rom:Omnirom 7.1.2

## Logcat

```
your log here
```

**Comment by mlleemiles** [comment]
Change DPI.
