### ISSUE TITLE
Implementation of the translucent now tab and new shortcuts( with merged notification dots).

### ISSUE THREAD

**Issue by silentgurdian** [amirzaidi/Launcher3#281]
I found the translucent new Google now tab is working with the modded Pixel launcher 2. I figure since launcher3 is kept absolutely same as Pixel launcher updates to new versions are coming soon. I was just wondering if this translucent page could be implemented in the current Pixel launcher version and also the new shortcuts style of Pixel launcher 2. I don't really want the new launcher as much but a few features are definitely better so if they could get implemented to the current look it would be amazing. Also since this isn't a bug I don't know how to use the given format and thus I am writing it out without the format.

**Comment by gcladores** [comment]
https://forum.xda-developers.com/android/apps-games/app-rootless-pixel-2-launcher-google-t3688393

**Comment by silentgurdian** [comment]
I used this one but what I am saying is if these two features and the other new ones could be implemented with the current launcher3 appearance.
