### ISSUE TITLE
Adding Keep widget crashes the launcher

### ISSUE THREAD

**Issue by slabua** [amirzaidi/Launcher3#282]
## Description
When trying to add a Keep widget (any of the 2 types available) the launcher crashes.
Probably the issue arose after an update of the Keep app, or I simply didn't notice the issue long before.

## Expected Behavior
Selecting the Keep widget from the list should add the widget on the home screen properly.

## Actual Behavior
Adding the Keep widget results in the launcher crash, and consequent reload.

## Steps to Reproduce
1. tap and hold in any empty area of the screen
2. select the icon to add a widget
3. select any of the available Keep widget
4. follow the steps to configure the widget
5. the last step results in the launcher crash and no widget is added

## Environment
* Device: Nexus 5
* Android version: Android 6.0.1-M4B30Z
* Launcher version: 2.1.0
* Rom: Stock Rom

**Comment by abdullahibneat** [comment]
Working fine for me on Nexus 5X, Stock Android Oreo 8.0, RPL 2.1 for both widgets...

EDIT: Also made sure Keep was updated to the latest version.

![screenshot_20171104-142642](https://user-images.githubusercontent.com/7048592/32406220-44409484-c16c-11e7-966e-65c9d73073a4.png)

**Comment by slabua** [comment]
@abdullahibneat thanks for testing it, I also cleared the launcher's data and tried to add the widget again, but the problem still persists for me.

**Comment by abdullahibneat** [comment]
What exact version of Keep do you have? Mine is 4.0.411.05.40

EDIT: According to apkmirror, since you have a Nexus 5 (arm x86) the latest version available to you is 4.0.411.05.30 .... Did you have this issue before? If not, can you try an older version of Keep, such as [this](https://www.apkmirror.com/apk/google-inc/keep/keep-3-4-841-03-release/google-keep-3-4-841-03-30-android-apk-download/)?

**Comment by slabua** [comment]
@abdullahibneat I have 4.0.411.05.30

**Comment by slabua** [comment]
The widget works on the Google Now Launcher and Microsoft Launcher as well. My dpi is 380, if it matters.

**Comment by abdullahibneat** [comment]
I would suggest to wait for the developer... he might guide you better.

**Comment by slabua** [comment]
@abdullahibneat thanks no worries, I thought to share my experience here :)

**Comment by amirzaidi** [comment]
Can you please try the older version? And provide me with a logcat for the crash?

**Comment by slabua** [comment]
@amirzaidi same thing happened with version 2.0.2.

I created the logcat with the following 3 steps (not sure whether that's the correct way):

1. adb logcat -c
2. trying to add the widget to the launcher until the crash
3. adb logcat -d > logcat.txt

[logcat.txt](https://github.com/amirzaidi/Launcher3/files/1447278/logcat.txt)

**Comment by amirzaidi** [comment]
That is one weird crash, could you try if this happens in the 1.5 version? What about using an older Google Keep version, does that work?

**Comment by slabua** [comment]
@amirzaidi with 1.5 version it works fine, and same version of keep.

**Comment by carloszapruder** [comment]
Excuse me, how i can obtain the stock icons in the screenshot...i have a huawei p9.

**Comment by abdullahibneat** [comment]
You need an icon pack. However, to reflect the stock pixel launcher, RPL does not include any icon pack.

**Comment by amirzaidi** [comment]
Reopen if the bug persists
