### ISSUE TITLE
Cannot find settings for changing Icon shape

### ISSUE THREAD

**Issue by uttarayan21** [amirzaidi/Launcher3#283]
## Description

As per the screenshots provided there should be an option to change the icon shapes and a few other settings but I have only one setting to allow homescreen rotation

+Plus I also integrated the app to system and it also didn't work

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: ZUK Z2  Plus
* Android version: 7.1.2
* Launcher version: 2.1
* Rom: Paranoid Android 7.3.0-DEV

## Logcat

```
here is the logcat
https://pastebin.com/xTxSZmWf
```

**Comment by RikKoedoot** [comment]
Changing the icon shape is not available in 7.x.x, only on oreo

**Comment by uttarayan21** [comment]
Oh thanks! And here I was thinking something might be wrong with the ROM.
