### ISSUE TITLE
Only one setting on Android 8 (Nexus 5X)

### ISSUE THREAD

**Issue by barreira** [amirzaidi/Launcher3#285]
"Allow Homescreen rotation Current display setting doesn't permit rotation"

**Comment by amirzaidi** [comment]
Are you sure you're on Android 8? Try clearing Launcher3's data

**Comment by barreira** [comment]
SOLVED

Yes, I was 100% sure I was on 8.0.0.

What I did was install all the security updates I could, restart the phone, delete the app's cache (I actually reinstalled it afterwards) and it began working as it should have. The installing loading screen froze before finishing even though I could go to the home screen and see that the launcher was indeed installed.
