### ISSUE TITLE
Picture widget makes crash the launcher

### ISSUE THREAD

**Issue by OLDR1CK** [amirzaidi/Launcher3#286]
When I set a picture in the picture widget it crashes the launcher forever , I had to download it again so it "solves" the problem , until I re-do it

 I didn't saw something similar anywhere 

## Description

When I set a pic in the picture display widget it crashes the launcher , the only way I found to fix this is to reinstall the launcher.

## Expected Behavior

The pic I chose should display normally

## Actual Behavior

The launcher crashes forever even if the image I wanted to display is not on the screen . I can't use this launcher anymore unless I re-download it.

## Steps to Reproduce

1.hold the main screen until the widget option appear
2.search for the picture display widget
3.put it on the screen
4.choose a pic
Once you chose it the launcher crashes

## Environment

* Device: Huawei P10 Lite
* Android version: 7.0
* Launcher version: 2.1.0
* Rom: Stock Rom(I'll be honest I searched for it and I didn't found it , sry)

**Comment by amirzaidi** [comment]
Can you post a logcat?

**Comment by OLDR1CK** [comment]
Well I don't know how I can get one , I guess I'll search

**Comment by mlleemiles** [comment]
Aquire adb, turn on USB debugging on your device, connect and run "adb logcat -v time > log.txt" (without quote)
