### ISSUE TITLE
Cannot uninstall the launcher after install

### ISSUE THREAD

**Issue by rfdnl** [amirzaidi/Launcher3#288]

**Comment by amirzaidi** [comment]
Change your default launcher back to another one

**Comment by ghost** [comment]
Changing the default launcher back to another one ain't a solution to this if somebody needs to uninstall the app from the device. Please provide a solution ASAP!

**Comment by amirzaidi** [comment]
There is no solution to this, this is just how Android works, you can't uninstall the launcher you are using, so switch back to another launcher (like the one preinstalled on your phone) and then delete it
