### ISSUE TITLE
Provide an option in launcher setting to disable/enable big date on top homescreen

### ISSUE THREAD

**Issue by asadise** [amirzaidi/Launcher3#289]
## Description
In version 2.1, the launchee3 improve when Google now app where not exists (or disabled). I want to propose new item in setting that allows to disable/enable date on top of Home screen.

**Comment by bushman1** [comment]
Nice idea an option to do away the widget

**Comment by amirzaidi** [comment]
I'm not adding any toggles because of the translation issues, I need to make sure it works nicely in every language..

**Comment by asadicse** [comment]
Can I delete the BIG date widget from apk file of launcher3 with  tools like apkefitor? (Like changing a file in this apk)
