### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by frabarl** [amirzaidi/Launcher3#29]
Your ported Pixel Launcher is perfect, compliment, but there is, on my LG Nexus 5x, a problem. There isn't weather icon near the clock. Please, can you resolve this problem? I want too the weather icon, in this way your ported Pixel Launcher will be really perfect man!

**Comment by antoxa2584x** [comment]
Settings > Widget > Enable
Or check Location permission for launcher app

**Comment by frabarl** [comment]
I'm very sorry, can you repeat what I have to do? Thanks again

Il 14 giu 2017 4:04 PM, "Anton Artemov" <notifications@github.com> ha
scritto:

**Comment by thomasjpaterson** [comment]
Yeah i am having the same issue. However, Awesome APK!

**Comment by michael-mccoy** [comment]
Had the same issue. Try turning on/off location and swiping down Google now feed to refresh. https://www.reddit.com/r/Android/comments/6gn8f9/comment/dis6wz0

**Comment by frabarl** [comment]
Thanks a lot. Just in this moment I reset all Google Now Feed and now
weather icon works perfect! Thankssssss!!!! ❤️❤️

Il 15 giu 2017 12:31 AM, "Michael" <notifications@github.com> ha scritto:
