### ISSUE TITLE
Pixel search bar

### ISSUE THREAD

**Issue by NathanFrederick** [amirzaidi/Launcher3#291]
amirzaidi Can you please add White QSB Connector to search bar again or add a option to switch between transparent and white QSB Connector i like the white QSB Connector better

**Comment by NathanFrederick** [comment]
Can someone answer my question please

**Comment by RikKoedoot** [comment]
The older builds had this, but most people wanted the transparent one

**Comment by NathanFrederick** [comment]
Right

**Comment by amirzaidi** [comment]
Yep, but this is irrelevant for the 8.1 version coming up ;)

**Comment by NathanFrederick** [comment]
Is there going to be another update for this launcher

**Comment by NathanFrederick** [comment]
When is the 8.1 version coming up for this launcher
