### ISSUE TITLE
I SAD LIKE A SAD BOY IS ME IS A SAD ME

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#293]
Amir is no make a Pixel new launcher I am a sad me is so sad and no I no forgive I wait so many long year many many and I mad and sad angry human being like it is only a launcher why is so long no code learn how? I smart too much is me like a bag bag. Big forgile had me lunch yesterday I ated a hotdog no mustard and Amir still no launcher I want to die today.

**Comment by bushman1** [comment]
You have lived too long. You should have die yesterday.  Anyway merry christmas

**Comment by ghost** [comment]
Github got cancer too. Nice ._.

**Comment by anirudhgupta109** [comment]
tf did I just read and why did I ;-;

**Comment by nyancrimew** [comment]
@amirzaidi I think this has been fixed with the 8.1 update, consider closing this :wink:
