### ISSUE TITLE
Not working on Kitkat 4.4

### ISSUE THREAD

**Issue by tusharsoni08** [amirzaidi/Launcher3#294]
Hi, Could you please make sure does this Rootless Pixel Launcher 2.1 will work for Android Kitkat 4.4 also? Since I've Parsing package error.

**Comment by RikKoedoot** [comment]
This probably won't happen, just get a custom rom dude

**Comment by tusharsoni08** [comment]
@rickkode From where can I get that custom ROM?

**Comment by amirzaidi** [comment]
I won't try to backport the launcher to the 4.4 APIs, that is simply too much work. I try to stick to AOSP
