### ISSUE TITLE
New pixel² launcher bugs

### ISSUE THREAD

**Issue by AxiK101** [amirzaidi/Launcher3#297]
Blue folder bug in xperia devices (xa ultra).
Side panel working on Samsung fix!!😋
Search bottom google bar not showing
Blue accesent color missing
At a glance widget missing
Round icons missing
Most used apps missing

Keep up the good work dev!😉

**Comment by AxiK101** [comment]
![](https://i.imgur.com/S3kb9JL.jpg)

**Comment by AxiK101** [comment]
![](https://i.imgur.com/S3kb9JL.jpg)

**Comment by AxiK101** [comment]
If possible please add a switch for side panel to disable it

**Comment by bushman1** [comment]
Where to find apk for this?.

**Comment by P3draum** [comment]
Have link for downloaded?

Em ter, 16 de jan de 2018 12:23, bushman1 <notifications@github.com>
escreveu:

**Comment by bushman1** [comment]
P3draum,  no still no link

**Comment by amirzaidi** [comment]
> Blue folder bug in xperia devices (xa ultra).

Yes, I need to figure out how to override OEM changes

> Side panel working on Samsung fix!!😋

What?

> Search bottom google bar not showing

Added in new version

> Blue accesent color missing

What?

> At a glance widget missing

Added in new version

> Round icons missing

Added in new version

> Most used apps missing

Thinking about how to go about this one, this time around

@AxiK101 I'm not adding the switch, because disabling the feed breaks the google search bar animation

**Comment by AxiK101** [comment]
Blue accesent color is meant for replacing the cyan/green color in app drawer slider with the blue one from pixel phones.
Also it whould be nice to add the Google Product Sans font in at a glance widget (and in ui of the launcher if possible), and backport some of the quickshortcuts on 7.0 maybe?
On latest CI version i noticed that all my icon packs are hidden in app drawer... A bug maybe🤔?
Finally i miss the gesture of slide down to revil notifpanel and a double tap to lock screen..

Many thanks for your efforts 😎

**Comment by AxiK101** [comment]
@bushman1 it's the ci builds from telegram channel

**Comment by AxiK101** [comment]
![](https://i.imgur.com/oOXjC9s.jpg)

**Comment by AxiK101** [comment]
Ok, latest version fixes blue color and blue folders but there is still the blue/teal background on widget drawers
![](https://i.imgur.com/7dD8fQO.jpg)
![](https://i.imgur.com/thiPoDe.png)
![](https://i.imgur.com/ag6Dwn0.png)

**Comment by amirzaidi** [comment]
Which Android version are you on? 8.0?

**Comment by amirzaidi** [comment]
Could you PM me know Telegram (@mirai) so we can resolve the blue drawer?

**Comment by bushman1** [comment]
@AxiK101 big thanks.

**Comment by bushman1** [comment]
At a glance widget not showing calendar events on s7 nougat. Any help?

**Comment by den-ko** [comment]
I've found a problem with an embedded widget with a date and weather. Don't know how to call it correctly. When I delete an event in the Google Calendar it still shows it. Clicking at it shows an 'event not found' pop-up and it looks like it tries to open it but all I have is a blinking white page.

**Comment by amirzaidi** [comment]
On lollipop and marshmallow it takes some time to go away, because the Google App for whatever reason doesn't update it until a few minutes later on those android versions

**Comment by den-ko** [comment]
@amirzaidi I have 8.1. Then on oreo the same

**Comment by P3draum** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "CONTRA o cardápio de LUXO do
Supremo Tribunal Federal" e queria saber se você pode ajudar assinando
também.

A nossa meta é conseguir 300.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/C4WYdw5QKY

Obrigado!
Pedro

**Comment by Carbon-Zero** [comment]
What version of Google podcasts are you using?
