### ISSUE TITLE
App Drawer has aqua-blue background. Unsure why

### ISSUE THREAD

**Issue by alinuxfan** [amirzaidi/Launcher3#298]
Verizon Samsung S8 and my app drawer is an aqua-blue background. I tried changing the theme but it doesn't change the app drawer background. How do I change it?

**Comment by alinuxfan** [comment]
Screenshot: https://imgur.com/a/8R2RQ

**Comment by LiverBlow** [comment]
This has been fixed in the latest build (available in the telegram channel)

**Comment by alinuxfan** [comment]
Downloaded via telegram. Uninstalled and reinstalled. Blue issue is fixed.
