### ISSUE TITLE
New pixel launcher 3.0 bug

### ISSUE THREAD

**Issue by OLDR1CK** [amirzaidi/Launcher3#299]
When I try to install it it says that I can't because the file is corrupted ! Any clue toward that ?

**Comment by msahil432** [comment]
May be there was a download error, download again.
Or there is an existing pixel launcher, uninstall that and try installing again.

**Comment by OLDR1CK** [comment]
Both things don't work , it still says it is corrupted :'/

**Comment by Denishaziri** [comment]
Yes me too but If you have root delete old launcher and copy the launcher in system app and restart your device it will work

**Comment by OLDR1CK** [comment]
Ok it worked ! Thx
