### ISSUE TITLE
Can't install on 8.0 dp3

### ISSUE THREAD

**Issue by marioconsalvo** [amirzaidi/Launcher3#3]
After a long wait in the installation page, appear "App not installed" message. Nexus 5x android O dp3.

**Comment by amirzaidi** [comment]
Could you give me some logs?

**Comment by RazGame** [comment]
I'm running Android O at Nexus 6P, all works

**Comment by kartheek4u** [comment]
Nexus 6p Android O DP3. Doesn't work for me either. During the installation itself I get an error App cannot be installed

**Comment by co5m0** [comment]
Try to install via adb too and this is the error "Failure [INSTALL_FAILED_VERSION_DOWNGRADE]". 
[log.txt](https://github.com/amirzaidi/Launcher3/files/1069620/log.txt)

**Comment by amirzaidi** [comment]
If that is what happened then it means the Pixel Launcher is already installed. You will have to completely remove it to use this.

Seeing as com.google.android.apps.nexuslauncher/.NexusLauncherActivity is in your ActivityRecords I'm pretty sure you still have it installed.

**Comment by co5m0** [comment]
yep, it works !!! thanks mate

**Comment by fvmsantos** [comment]
hey @amirzaidi 
sorry, but where do I find ActivityRecords?

thanks!
