### ISSUE TITLE
Navigation Bar not transparent

### ISSUE THREAD

**Issue by msahil432** [amirzaidi/Launcher3#300]
A great job bro, only thing bothering me is this white transparent navigation bar. Can you please fix this or provide a workaround for it? I tried substratum but launcher kept force closing, may be it was due to hardcoded colors as you said.
I am on RR 5.8 N 7.1.2, arm v7.
Thanks 
https://m.imgur.com/aLMOOAz

**Comment by amirzaidi** [comment]
I don't provide support for custom ROMs, and this is obviously a RR issue.

**Comment by msahil432** [comment]
Ok bro
