### ISSUE TITLE
No dark theme!

### ISSUE THREAD

**Issue by Denishaziri** [amirzaidi/Launcher3#301]
First thank you very much for this moded launcher but Why did you remove the dark theme ?! now the background its white  back the dark the please

**Comment by amirzaidi** [comment]
I didn't remove the dark theme, use a dark wallpaper and you will get the dark theme

**Comment by Denishaziri** [comment]
No i swear there is no more the option ( use dark theme ) it was there in the version 2.1 but now its gone maybe you forgot to add it holding an icon and now the shortcuts are in white and the app drawer white i like the dark more :) but its okay i hope you add this in the next release thank you

**Comment by amirzaidi** [comment]
There was no dark theme option in 2.1, you might be confused with paphonb's APK edit

**Comment by Denishaziri** [comment]
! Ehw interesting really 😮😐 im going back in 2.1 and i tell you there is that option

**Comment by Denishaziri** [comment]
https://www.youtube.com/watch?v=6lWry4eGu8Q

Look at this amir its uploaded from me today just to show you there was an option costomizations and use dark theme

**Comment by amirzaidi** [comment]
@Denishaziri that is not mine.. that is paphonb's edit. He used my 'Rootless Pixel Launcher' name which caused the confusion :/
