### ISSUE TITLE
Launcher 3.0 ANIMATION ISSUE

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#304]
I'm having the SAME animation issue I've had with the Rootless Pixel Launcher apk from XDA. My device: Moto G4 Plus. 
Here's a video of the issue (check description to see explanation): https://youtu.be/z1YuV3tcV5Q

**Comment by mlleemiles** [comment]
Have you tried reboot after the installation?

**Comment by nikkomercado** [comment]
@mlleemiles Yes. I tried everything I could.

**Comment by Denishaziri** [comment]
Turn off the animations in developer options or change the option to 5x faster animation and it will work fine

**Comment by nikkomercado** [comment]
@Denishaziri That's not the point. The point is it isn't normal.

**Comment by nikkomercado** [comment]
Plus, I'm fine with 1x. I don't want fast animations.

**Comment by rslh** [comment]
Yup. I'm having a similar issue. I have 2 OP5T and one phone is fine but the other the animation when swipe up for app drawer is slow/sluggish. I compared the 2 settings and they're identical.

**Comment by rslh** [comment]
@nikkomercado I have my animation to 1.5x and on the phone that's been running smoothly, previously I loaded Clean Master and 'cleaned' my internals and it was never sluggish. Just now I installed it on the affected phone and cleaned all junk files, did a Phone Boost and Battery Saver routine and now the slow animation is gone!!! It's a long shot but try it on your phone and see if it works.

**Comment by nikkomercado** [comment]
@rslh Watch the video, people. The problem isn't the animation being slow. It's the animation being different and weird! Instead of an app normally sliding down when going home, the screen turns black then the launcher appears with some sort of weird animation. I repeat: ANIMATION ISN'T SLOW. IT IS DIFFERENT FROM THE NORMAL ANIMATION.

**Comment by rslh** [comment]
@nikkomercado Which version do you have? https://github.com/amirzaidi/launcher3/releases I find 3.1 missing some key features and the 3.2 mod version has what I wanted; e.g., Customize settings. https://www.apkmirror.com/apk/paphonb/rootless-pixel-2-launcher-mod/pixel-launcher-2-8-1-0-4348501-modded-3-2-release/pixel-launcher-8-1-0-4348501-modded-3-2-android-apk-download/ Good luck.

**Comment by nikkomercado** [comment]
@rslh Does it matter? All of them probably have the same bug.

**Comment by amirzaidi** [comment]
Offtopic: don't use Clean Master, @rslh, it's just an adware app that does nothing useful

I think it has something to do with the launcher being pushed out of memory. How much RAM does your phone have?

**Comment by rslh** [comment]
@amirzaidi Yeah, agreed on these app cleaning apps with false placebo effect. 6GB is what I have.

**Comment by amirzaidi** [comment]
Optimization is coming for 3.2

**Comment by nikkomercado** [comment]
@amirzaidi Thank God.

**Comment by nikkomercado** [comment]
@amirzaidi Oh, crap. I didn't see your question. My bad. My phone has 3GB RAM.
