### ISSUE TITLE
Google app bug!!

### ISSUE THREAD

**Issue by HT-Soft** [amirzaidi/Launcher3#306]
When i swipe from left to open google app it takes more space than my screen and everything is cut off behind the screen.
I have screnshot contact me on whatsapp - +91 7814006851

**Comment by nikkomercado** [comment]
Happened to me. All you need to do is force stop the app and clear cache. That fixed it for me.

**Comment by nikkomercado** [comment]
Do this to the launcher. Not the Google app.

**Comment by HT-Soft** [comment]
Just turning off/on google app in launcher settings worked for me.
