### ISSUE TITLE
Legacy Icons Masking

### ISSUE THREAD

**Issue by archit9169** [amirzaidi/Launcher3#307]
Can you add masking for legacy icons.

https://github.com/nitrogen-project/android_packages_apps_Launcher3/commit/ee6de1ed37c5a539a1e6325c1c2f576bf4068d94

It does require a switch preference in settings tu turn on or off this feature. But you can just turn it on permanently.

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/commit/0257cca1020968dd46c4aa2d014d24d9993878cc

I actually disabled that myself because I hate legacy icon masking, many icons will be a box in a box. I mentioned it in the Reddit thread
