### ISSUE TITLE
App shortcuts not working

### ISSUE THREAD

**Issue by ewjy** [amirzaidi/Launcher3#308]
On my Nokia 8, the expected app shortcuts didn't show when long-pressing the icon:
![screenshot_20180126-211836](https://user-images.githubusercontent.com/11014565/35441621-28664074-02df-11e8-97e7-dfc7afb39d37.png)
While it's working on the stock Launcher3:
![screenshot_20180126-212058](https://user-images.githubusercontent.com/11014565/35441637-3ccedc60-02df-11e8-90e3-081fbf650226.png)
Can you please help me fix it? Thank you.

**Comment by amirzaidi** [comment]
Set my launcher as the default launcher first.
