### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by RikKoedoot** [amirzaidi/Launcher3#31]
On my moto g4plus the g tab is way to big, I have my dpi set to small, if I change it to normal, it is good size, but I don't like normal dpi, is it possible to be changed?[
![screenshot_20170614-162921](https://user-images.githubusercontent.com/29402532/27137743-f5048172-511e-11e7-8612-d57a49c2e784.png)
](url)

**Comment by amirzaidi** [comment]
Motorola seems to have some weird package that overrides the launcher, please add it to this post:
https://github.com/amirzaidi/Launcher3/issues/24
