### ISSUE TITLE
Issue with calendar icon

### ISSUE THREAD

**Issue by michael1900** [amirzaidi/Launcher3#311]
Hey. So the problem with calendar icon is still there. I mean this launcher missing the refresh of the icon pack. The calendar icon doesn't change every 24 hours but only if i apply the icon pack again. So in this last case the icon pack update itself and so on..

Obviously there is not problem with Nova launcher and the same icon package.

Please fix this if you can. Thanks

**Comment by amirzaidi** [comment]
I fixed this in the alphas and will release it later today on the releases page

**Comment by amirzaidi** [comment]
Fixed in 3.1
