### ISSUE TITLE
App drawer search bar looking weird

### ISSUE THREAD

**Issue by hugolinhares** [amirzaidi/Launcher3#312]
First, congratulations and thanks for the update. The search bar look weird in my Moto Z play.

Screenshot: https://ibb.co/ij4qmw

**Comment by amirzaidi** [comment]
I'm on it: https://github.com/amirzaidi/Launcher3/commit/9907493cbeef228d48199aac0143badb305d5ca6
Thanks for reporting

**Comment by amirzaidi** [comment]
Should be fixed on 3.1
