### ISSUE TITLE
Add functions Force round icons and Force colored Google logo on search bar

### ISSUE THREAD

**Issue by gargullia** [amirzaidi/Launcher3#313]
Add functions like in this application [modded-3-0-1](https://www.apkmirror.com/apk/paphonb/rootless-pixel-2-launcher-mod/rootless-pixel-2-launcher-mod-8-1-0-4348501-modded-3-0-1-release/rootless-pixel-2-launcher-mod-8-1-0-4348501-modded-3-0-1-android-apk-download/)
**Force round icons** and **Force colored Google logo on search bar**

**Comment by gargullia** [comment]
@paphonb

**Comment by amirzaidi** [comment]
This is not paphonb's launcher. If you want those features use his Pixel 2 Launcher

**Comment by gargullia** [comment]
@amirzaidi You misunderstood me. I would like to see this functionality in your launcher. And @paphonb asked about the committee. Open it please issues.

**Comment by otisidev** [comment]
I just installed the app, it's amazing. Am yet to see any bug. Thank you so much.

**Comment by amirzaidi** [comment]
@gargullia I understood you but I've put in the FAQ I don't like adding customization options like that. I don't mind you using paphonb's launcher if you prefer having those options
