### ISSUE TITLE
At a Glance only shows Celsius units

### ISSUE THREAD

**Issue by skintask** [amirzaidi/Launcher3#314]
I have an issue with At a Glance widget. It doesn't follow my option in Google to use Farenheit units. Anything I'm doing wrong? Is there another option to change it?

**Comment by Ayushtwentysix** [comment]
Try this.  
Search weather in Google search.
Then choose Farenheit unit from the interactive weather interface.
Hope it works...

**Comment by skintask** [comment]
I already have it in Farenheit. I tried to change it to Celsius and back to Farenheit and it doesn't change.
________________________________

**Comment by skintask** [comment]
It seems it was a problem with Google. It fixed itself. Thanks anyway!
