### ISSUE TITLE
Google feed broke and no weather at glance 

### ISSUE THREAD

**Issue by Ayushtwentysix** [amirzaidi/Launcher3#316]
Everything worked perfectly till this afternoon. Both Google feed & weather were showing. Now everything is gone.
I downloaded google version 7.19.19.21.arm ,
after this all issues started.
Now when i revert back to previous version of google, still issue is not resolved.
But when I go to factory version of Google 6.12.25.21.arm.

**Comment by coolprateek** [comment]
I'm having the same problem too
