### ISSUE TITLE
Google feed broke and no weather at glance 

### ISSUE THREAD

**Issue by Ayushtwentysix** [amirzaidi/Launcher3#317]
Everything worked perfectly till this afternoon. Both Google feed & weather were showing. Now everything is gone.
I downloaded google version 7.19.19.21.arm ,
after this all issues started.
Now when i revert back to previous version of google, still issue is not resolved.
But when I go to factory version of Google 6.12.25.21.arm, then Google feed is working fine but weather is not shown.

**Comment by kuberrohilla** [comment]
My google feed and weather at glance is also broken. If i try to refresh my feed, it says can't reach your feed. Google app is updated. Everything was running smooth till yesterday.

**Comment by keetrock46270** [comment]
![screenshot_20180127-135855](https://user-images.githubusercontent.com/29511789/35476278-5ce82142-036a-11e8-9cef-5522730aaa40.png)
Same issue here

**Comment by michael1900** [comment]
Please post a screenshot of problem

Edit: I have feeds but not weather there. I don't know why

**Comment by Vengance09** [comment]
I have the same issue. Just installed Linage OS 14.1 on LG G3 with this launcher. Everything working expect the weather information on the home screen. Weather is turned on in Now cards and Location is on high. 

Google app version is 7.18.50.21 ram
Launcher version is 3.1

**Comment by nikkomercado** [comment]
I have the feed on my Google feed too but the weather on At A Glance isn't there.

**Comment by keetrock46270** [comment]
Feeds are back this morning, not sure if the error was associated with the newest update or if there was an issue on Google's side. Thanks fir all the hard work on this Amir.

**Comment by amirzaidi** [comment]
Google was having problems, I did nothing
