### ISSUE TITLE
APKs in releases/ all have the same versionCode

### ISSUE THREAD

**Issue by IzzySoft** [amirzaidi/Launcher3#319]
Your APKs in `releases/` always have `versionCode:1`. Could you please take care to increase that with each newer version? Otherwise Android does not recognize them as updates, but rather considers them all being the same version.

Thanks in advance!

**Comment by amirzaidi** [comment]
I do this intentionally so people can go back to an older version without reinstalling

**Comment by IzzySoft** [comment]
But that makes it impossible to be notified on updates if one e.g. uses an F-Droid repo for that – one always had to check manually then. Some user [asked me](https://gitlab.com/IzzyOnDroid/repo/issues/6) to make your app available via my repo (see [here](https://apt.izzysoft.de/fdroid/index/apk/com.google.android.apps.nexuslauncher)) – but with the `versionCode` always being the same 1) I cannot pull your updates automatically (they would be ignored), and 2) even if I'd take care for that manually, the user(s) would have no benefit from it as the F-Droid client won't ever notify them on updates.

So unless you're opposed to have your app available that way, can we find some compromise? I could e.g. think of a second `.apk` being attached (I can tell my auto-updater what to pick or what to ignore if there's a definite pattern in the filename). If you decide for that path, maybe it could also skip the `ApplicationDebuggable` flag :wink:

**Comment by JonnyTech** [comment]
@amirzaidi please reconsider your decision. Going back to a previous version may be a rarity whereas moving on to updated builds is much more common. Having automatic notifications via @IzzySoft's f-droid repo saves users having to check manually. Maybe have the app automatically backup its settings regularly or with each update, that way if a build is broken then uninstalling and reinstalling a previous version would give the user an option to import one of the dated backups.

**Comment by dadycool3** [comment]
I like the app. Please go on like this.

**Comment by amirzaidi** [comment]
I'll consider finding a compromise later. The problem is that I jump between projects so often I doubt I'll provide any kind of regular updates for one. I do this for fun in the little free time I have. If someone wants to fork it and make it a full fletched launcher project (another Lawnchair for example) then go ahead, the code is free to use

**Comment by IzzySoft** [comment]
@amirzaidi if there are no "regular updates", there's no need to "go back to an older version" either – wouldn't you agree? :wink:

And "rare updates" (I see them come in pairs here: two in Januare, then two in August before) make it rather hard for users to figure when it would be worth checking. A burden my repo wants to take from their shoulders.

Of course we understand this is "just a hobby" (and ask me about projects! I know exactly what you mean). So we don't expect daily updates. You set the speed for your projects, of course. Glad you consider finding a compromise, looking forward to that!

**Comment by IzzySoft** [comment]
Any news on this, @amirzaidi ? I just updated manually to 3.5 *today* – while it was already available for a full month (didn't notice as I had to check manually). So users relying on my repo will have missed it as well.

**Comment by amirzaidi** [comment]
F-Droid won't ever include my app because it uses the same package name as the real Pixel Launcher (which I will not change for compatibility and feature reasons). I often ask users to roll back to older versions for regression tests when they find a bug, and this would be a painful task if they had to reinstall every time, especially if the bug is related to a setup they have. So, I probably won't update the versionCode, sorry

**Comment by IzzySoft** [comment]
There's always [my repo](https://apt.izzysoft.de/fdroid/) for things like that. But well, I'll of course accept your "no". I'm not using your app myself, so I have no pressure. Others might see it in a different light (see above), so be welcome to approach me if you change your mind.
