### ISSUE TITLE
search bar cut off on essential phone due to the notch

### ISSUE THREAD

**Issue by 6876942** [amirzaidi/Launcher3#321]
The search bar is cut off on the essential phone (https://www.essential.com/) in portrait mode. I am using version 3.1.

**Comment by 6876942** [comment]
Every other launcher I've tried has the search bar below the camera so I imagine this is fixable.

**Comment by amirzaidi** [comment]
Even 8.1 launchers? This is a very tough problem to solve because this positioning is hardcoded by Google

**Comment by 6876942** [comment]
How can I tell if a launcher is an 8.1 launcher? If it's by the appearance then I haven't seen another one that works on my phone. I guess it can't be fixed anytime soon, hopefully one day.

**Comment by amirzaidi** [comment]
8.1 launchers have the jumpy effect when you scroll, and the fading mist at the bottom of the home screen

**Comment by hundeva** [comment]
I did fix this for Lean Launcher a while ago, not sure if it is still an issue here, if yes, [this commit](https://github.com/hundeva/Lean-Launcher/commit/d7ef940686798a21e9974be7373854174b8da161) might help a bit!

**Comment by amirzaidi** [comment]
Thanks @hundeva, I think this should fix it then:
![capture](https://user-images.githubusercontent.com/2102185/38456291-636aa04e-3a83-11e8-8b66-5ddc767fd8d3.PNG)

I hope some Essential tester can test this for me in the alpha builds on https://t.me/appforks

**Comment by amirzaidi** [comment]
They reported that it works well :)
