### ISSUE TITLE
Google logo in Google now

### ISSUE THREAD

**Issue by sushruth** [amirzaidi/Launcher3#328]
This is the only thing that feels different from Pixel 2 launcher

Launcher3 : 

![luncher 3](https://i.imgur.com/H59o8gF.png)

Pixel 2 launcher :

![pixel 2 launcher](https://i.imgur.com/fBPM79z.jpg)

Can you fix it?

**Comment by amirzaidi** [comment]
This is a Google A/B test.. Google decides who gets which logo. I have no control over this unfortunately
