### ISSUE TITLE
Option to turn off "Ok Google" on the home screen.

### ISSUE THREAD

**Issue by mooshake13** [amirzaidi/Launcher3#330]
So, i have turned off "Ok Google" activation from the settings within Google search and assistant but the phone is still listening and responds to Ok Google on the home screen. 
A toggle to turn that off in this launcher would be nice because I don't want my microphone listening to me all the time. Why? 1- Privacy, 2- battery
P.s. I'm using a Nexus 6P, running on 8.1 Oreo.
Thanks!

**Comment by amirzaidi** [comment]
I think it's done automatically by the Google App when you connect for the Google Now Feed, I don't start this listening myself

**Comment by mooshake13** [comment]
Yeah, I guess.
Thanks for the swift reply. I'm no Dev, but would it be possible for you to perhaps look for a way to disable it or give the user control over ok/hey Google Voice command? 
I was on Nova prime until I stumbled across this and I absolutely admire the sort of work you've done with this launcher. 
Keep up the good work Amir!

**Comment by amirzaidi** [comment]
Try denying microphone permissions to the Google App

**Comment by mooshake13** [comment]
I could, but then I do use the assistant by long pressing the home button to setup my appointments. It's okay if the microphone is always on. Thanks for the reply even though I closed the issue. Keep up the great work.
