### ISSUE TITLE
Small performance issue compared to pixel laucnher

### ISSUE THREAD

**Issue by r4dius** [amirzaidi/Launcher3#331]
Hi, I've been trying the launcher for some days on my oneplus3t but there's seems to be some lag at startup that's not on the original pixel launcher, it's something like 1 or 2 seconds which would not be a problem if it was just only on the first start but for some reason after using other apps for some time and returning to the launcher it "reloads" (or restart) with the same 1 or 2 seconds delay,
I first thought it was something usual with the new launcher but I just tried the original 8.1 pixel apk and don't have the same issue, it starts faster and I couldn't see it "reload" after some use of the phone or maybe it was just too quick.
Does any one know about this small issue ? Could it be related to the google now that I can't get with the original one (I'm not rooted) or any other thing ?
As a side question would it be possible to "port" the rootless google now thing to the original app (would be enough for my use ^^) ?
Thanks for your time btw it's really a nice peace of work :)

**Comment by amirzaidi** [comment]
> Could it be related to the google now that I can't get with the original one (I'm not rooted) or any other thing ?

Yep, it's waiting for the Google interface to connect. I didn't have this either until I added the Google Now feed, and testing shows that the real Pixel Launcher does this too when you install it with root as a system app (so you get the now feed).

> As a side question would it be possible to "port" the rootless google now thing to the original app (would be enough for my use ^^) ?

Look for "paphonb pixel launcher", he did exactly that

**Comment by mlleemiles** [comment]
Can confirm OG pixel launcher does it too. Back when I was using the coast live wallpaper and 7.1 OG pixel launcher, I saw the wallpaper reset itself from time to time.

**Comment by r4dius** [comment]
Hi, thanks for the answers I was not sure if paphonb's was something like this one with mods or mods on the original launcher :), I've been using paphonb's for 2 days and while it's slow to start too I've not seen any "reload" of the app after some use when switching apps to desktop, I'll be retrying yours to check it was not something with my phone at the time :)
