### ISSUE TITLE
Launcher bug while in call

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#336]
While in a call on LG V30 switching back to Pixel Launcher from call app went a broken state. 

![capture _2018-02-01-10-44-54](https://user-images.githubusercontent.com/35972809/35691327-ced82172-073d-11e8-9a6b-d8e7943ab4ff.png)

![capture _2018-02-01-10-45-06](https://user-images.githubusercontent.com/35972809/35691315-c76faf68-073d-11e8-8b95-79c67ae90452.png)

**Comment by amirzaidi** [comment]
Which dialer app is this?

**Comment by ghost** [comment]
LG v30 stock dialer.

**Comment by amirzaidi** [comment]
Does this happen on the real Pixel Launcher? Does this still happen on 3.3?

**Comment by ghost** [comment]
Nope close case. Only happened once on 3.1.

On Mar 25, 2018 6:28 AM, "Amir Zaidi" <notifications@github.com> wrote:

Does this happen on the real Pixel Launcher? Does this still happen on 3.3?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amirzaidi/Launcher3/issues/336#issuecomment-375963292>,
or mute the thread
