### ISSUE TITLE
[Solved] No cards in my google now panel

### ISSUE THREAD

**Issue by rafiee** [amirzaidi/Launcher3#339]
When I swipe righht, there is no card in my feed panel. I flashed AOSiP 8.1 and tried with Pico and Micro Gapps.  Do i need to install google now launcher before installing pixel launcher rootless 3.1 ?
thanks

**Comment by x2k13** [comment]
Do you have the Google App installed (as system app)?

**Comment by rafiee** [comment]
Yes. thanks for your reply.
Problem Solved: I had problem with my Google app.
