### ISSUE TITLE
Add background to statusbar on lollipop

### ISSUE THREAD

**Issue by vojta-horanek** [amirzaidi/Launcher3#34]
There is a weird search bar text padding in the app drawer. It woul also be great if you could add some background to status bar in api < 23
(Both of these issue exist in non edited pixel launcher)
OS=5.0.2

Screenshot:
http://imgur.com/a/ky20r

**Comment by amirzaidi** [comment]
Can you check the latest Telegram test build? I think I fixed it

**Comment by vojta-horanek** [comment]
Yes it's all fine now

**Comment by amirzaidi** [comment]
Reopened? Is it not fixed in 2.1?

**Comment by vojta-horanek** [comment]
Sorry, for reopening but I have to correct myself, the padding is fine now but the status bar color isn't

**Comment by amirzaidi** [comment]
That's an API limitation, I cannot get around that. Dark status bar icons didn't exist on Android 5

**Comment by vojta-horanek** [comment]
Yes I know coloring the status bar icons on lollipop is impossible, but I ment something like this: http://imgur.com/a/coGwq - Screenshot from Lawnchair launcher https://github.com/Deletescape-Media/Lawnchair
