### ISSUE TITLE
Implement hiding apps and per app icons

### ISSUE THREAD

**Issue by ssakuh** [amirzaidi/Launcher3#343]
Great features yet to be added, solves incomplete icon-packs that result in unaesthetic experience.
Notice that it would be cool that certain apps are hidden from app drawer and not from search.

**Comment by mlleemiles** [comment]
Yet to be added? I think not.. This completely defeats the purpose of this launcher.

**Comment by ssakuh** [comment]
why would it defeat the purpose of this launcher?🤔

**Comment by JonnyTech** [comment]
From this project's readme:

> My launcher is a close to AOSP launcher that only changes the necessary code to allow for small extensions and backporting to older Android versions. If you want a more feature packed launcher use Nova, Action or Lawnchair. It is focused on simplicity and rock solid stability. Bug reports go above all else, and almost every feature request will be denied.

Please close this issue.
