### ISSUE TITLE
Can't create home screen shortcuts

### ISSUE THREAD

**Issue by abu129954** [amirzaidi/Launcher3#347]
Can't create home screen shortcuts it is saying no space on home screen when the home screen is empty and one more issue weather is not being shown in at a glance. 
Experiencing these issues on my Huawei p10 lite running  EMUI 5.1 on top of Android 7.0 . Please fix these issues or give a solution.

**Comment by amirzaidi** [comment]
Did you resolve this?

**Comment by abu129954** [comment]
no, actually I went in app info and cleared app data and both the issues
have gone after the app restrarted
