### ISSUE TITLE
Samsung 5x1 Widgets don't show up

### ISSUE THREAD

**Issue by baadnewz** [amirzaidi/Launcher3#348]
As title says some samsung Touchwiz  widgets don't show up (mainly those which are 5x1): Device maintenance, weather widgets (only the 3x3 is available) . And yes since Samsung Experience 9 (Oreo update) weather isn't exclusive to Touchwiz  and device maintenance widget never was specific. 

If I were to guess i think is related to the widget requiring 5 in width and for some reason it thinks the launcher offers only 4 

As additional info I can add that with latest version of Nova (5.5.3) they can be added and used.

**Comment by amirzaidi** [comment]
Do they show up if you use a lower DPI?

**Comment by baadnewz** [comment]
The minimum allowed is 320 (default is 360) and they still don't show.

However when I tried ruthless fork I had to change in ruthless's settings to 6 columns in home screen to make those Samsung widgets show

**Comment by amirzaidi** [comment]
Smallest width is the opposite of DPI, try using a higher smallest width until the widget shows up

**Comment by baadnewz** [comment]
Increased it to 420 and got the widgets showing
