### ISSUE TITLE
APK appears to be corrupt

### ISSUE THREAD

**Issue by stephensuarez** [amirzaidi/Launcher3#349]
Can't install on Samsung s8+

**Comment by dadycool3** [comment]
Sure you can from apkmirror

**Comment by stephensuarez** [comment]
Appreciate the reply, and apologies for not knowing...but where can I find that link?

**Comment by mlleemiles** [comment]
Make sure to uninstall any pixel launcher on your phone first

**Comment by stephensuarez** [comment]
That worked...thanks. 

Is there any way to maintain apps on home screen while upgrading?

I don't see much difference between this and the last version....
