### ISSUE TITLE
Terrible scaling of home page and small icons in app drawer menu for Samsung Galaxy Tab S2 9.7inch Tablet

### ISSUE THREAD

**Issue by justin13888** [amirzaidi/Launcher3#350]
My Samsung tablet is running on nougat 7.0 but there is a huge gap between the squished icons and the app drawer where there is the favourite apps.

**Comment by justin13888** [comment]
Edit empty space in between is for more icons but there is still no option to change the grid and the icon sizes

**Comment by amirzaidi** [comment]
Check 3.3 for tablet profiles
