### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by LeyendaV** [amirzaidi/Launcher3#351]
I installed the stable 3.1 version couple of days ago, and after the testing I can confirm that my battery life had been cut down on several hours. 

I have a Motoroka XT1562 with Nougat 7.1.1

**Comment by mooshake13** [comment]
According to my tests, that battery drain is probably attributed to the live clock icon. 
I compared battery usage by the launcher on my Nexus 6p in the  battery section and it clearly used more battery when compared to a 3rd party icon pack. 
I'd suggest you download the pixel icon pack from the play store and try it for yourself. Cheers!

**Comment by LeyendaV** [comment]
Could be, but at least not for me. My clock icon is not dynamic, always shows 10:10:30 and never moves. The only live icon is the Google Calendar one, and the app is factory installed so I always had it on my phone.

I'll keep checking. Didn't installed anything since the launcher, and I'm preventing any update for my apps.

**Comment by amirzaidi** [comment]
Thanks for the tip, I disabled the code for it in the latest alpha for Lollipop/Marshmallow/Nougat (because there are no adaptive icons anyways) and I hope this will indeed improve the battery drain problems for those versions
