### ISSUE TITLE
Weird tint on long press at homescreen for live wallpapers.

### ISSUE THREAD

**Issue by jameil** [amirzaidi/Launcher3#353]
![screenshot_20180212-142905](https://user-images.githubusercontent.com/36410267/36098995-505b5d24-1001-11e8-98b7-0b0860e480f5.jpg)
Long press for normal wallpaper.

![screenshot_20180212-142846](https://user-images.githubusercontent.com/36410267/36099014-640a4df8-1001-11e8-8fe3-8a1a1a39ad04.jpg)
Long press for live wallpaper (tried with different live wallpaper apps too)

**Comment by amirzaidi** [comment]
It's based on the live wallpaper preview image which might not be accurate

**Comment by jameil** [comment]
That sucks 😕. Does it make any sense to disable it for live wallpapers?

**Comment by amirzaidi** [comment]
I wanted to do that but then people will complain that that is bugged.. so I decided to keep it enabled for the preview
