### ISSUE TITLE
Strange text overlap on my Google now feed

### ISSUE THREAD

**Issue by mooshake13** [amirzaidi/Launcher3#354]
![screenshot_20180213-112323](https://user-images.githubusercontent.com/35949479/36135513-9ae6062c-10b1-11e8-8c95-9df45d4ba1ba.png)
So, everything was fine until this morning when I noticed the text overlapping in my Google now feed. I tried clearing cache but that didn't help. What could it be? Google pushing out some new update or should I clear data too and find out whether the feed is back to normal?

**Comment by amirzaidi** [comment]
yeah it's a Google app problem, the launcher doesn't influence those layouts at all

**Comment by mooshake13** [comment]
It's gone with the new Google app update. Thanks man!
