### ISSUE TITLE
Lag on Nexus 6P Android Oreo 8.1

### ISSUE THREAD

**Issue by Princevader** [amirzaidi/Launcher3#358]
Lag on Nexus 6P Android Oreo 8.1. Thanks.

**Comment by lobster1** [comment]
Yes, can confirm this lag

**Comment by mooshake13** [comment]
Same. But it's not very common. I've only experienced lag when the phone gets hot. I reckon it's the throttling that was needed for the Snapdragon 810 chipset that causes it.  🤔
The particular SOC was known for running hot and Google pushed out a 2.1 version of it with some fixes.

**Comment by Princevader** [comment]
Noted. Thanks :)

**Comment by amirzaidi** [comment]
Optimization coming in new 3.2 release, stay tuned

**Comment by Princevader** [comment]
Wow, thanks. More power. 🙂

**Comment by Polomman** [comment]
Nice

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by oliveru** [comment]
Looking forward!
