### ISSUE TITLE
Pixel Launcher new pill look.

### ISSUE THREAD

**Issue by cyberon** [amirzaidi/Launcher3#36]
Hi, the latest Pixel Launcher has a new looking shade on the pill (it's lighter), take a look.
![screenshot_20170518-070033-300x533](https://user-images.githubusercontent.com/683597/27154424-ee400d6a-514c-11e7-9a72-2d097d5bf343.png)

**Comment by amirzaidi** [comment]
I know, but I think it is ugly so I kept it in the N style

**Comment by RikKoedoot** [comment]
You can make it a toggle too

**Comment by amirzaidi** [comment]
I'll probably add it when I'm going to port the O Launcher, for now I'll leave it as it is.
