### ISSUE TITLE
Messed up feed 

### ISSUE THREAD

**Issue by RuthlessRuler** [amirzaidi/Launcher3#360]
![screenshot_20180216-043322](https://user-images.githubusercontent.com/20885012/36285820-1f73e26a-12d3-11e8-99b6-109a8063171b.png)

Feed looks messed up sometime when swiped to fast. Please fix this issue.

**Comment by 11sword11** [comment]
Im to have this issue. Please fix this..

**Comment by RuthlessRuler** [comment]
Okay, since you mentioned that this is not the app's fault and that of Google App, please close this issue.
