### ISSUE TITLE
Won't display shortcuts

### ISSUE THREAD

**Issue by risangbaskoro** [amirzaidi/Launcher3#363]
When i long press the app, it doesn't show the shortcut. It only shows a widget options and and an app info tab.

**Comment by Polomman** [comment]
It is unstable

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by amirzaidi** [comment]
Coming soon for older Android versions in 3.2

**Comment by michgauz** [comment]
Hello,
I have seen some app with shortcuts and android Android 7.0 (Play Store for exemple)
I don't know how to make it works with my app.

It's a static shortcut android and works well with 7.1 for exemple.

Any idea ?

Thanks

**Comment by amirzaidi** [comment]
It needs to be well defined in the shortcuts.xml, and not loaded through programmatic code

**Comment by michgauz** [comment]
Thanks but I have already done this.
I have figured out that exported=true was essential on target Activities to make it work.
Now It's OK.

Thanks
