### ISSUE TITLE
Version 3.2 on apkmirror ?!

### ISSUE THREAD

**Issue by BlueBlueBlob** [amirzaidi/Launcher3#365]
http://www.apkmirror.com/apk/amirzaidi/rootless-pixel-launcher/rootless-pixel-launcher-3-2-release/rootless-pixel-launcher-3-2-android-apk-download/

**Comment by homebrewGT** [comment]
I got that email too, but i don't see any update here...

**Comment by BlueBlueBlob** [comment]
I've just checked signature. It's the same. Weird

**Comment by amirzaidi** [comment]
Lol someone uploaded an alpha.. it's not yet ready

**Comment by BlueBlueBlob** [comment]
Haha nice an update is coming ;)

**Comment by amirzaidi** [comment]
- this is proof for Axi K that I'd like the alpha 3.2 to be removed for the time being

**Comment by AxiK101** [comment]
Done
