### ISSUE TITLE
Dark theme doesn't work with daily wallpapers 

### ISSUE THREAD

**Issue by kuberrohilla** [amirzaidi/Launcher3#366]
If i set a dark wallpaper manually then the dark theme is applied. But if the same wallpaper is set when the daily wallpaper feature is on then the dark theme isn't applied. Is that a bug?

**Comment by deepaksp** [comment]
For me google feed dosnt apply black theme on android 7.1 custom rom

**Comment by kuberrohilla** [comment]
I am on Android 8.0 stock rom on Mi A1

**Comment by amirzaidi** [comment]
Dark Google Feed is only available on Android 8, it's a Google App limitation.
Live wallpapers like "Daily Wallpaper" indeed don't influence the theme, because the theme is loaded from the preview

**Comment by kuberrohilla** [comment]
So the dark theme won't be applied on live wallpapers and daily wallpapers. This is the expected behavior as on pixel devices and not a bug?

**Comment by amirzaidi** [comment]
Yep. It CAN be applied on live wallpapers if the preview is accurate, but it won't automatically switch the theme when the live wallpaper/daily wallpaper changes
