### ISSUE TITLE
Error in LineageOS Build

### ISSUE THREAD

**Issue by princeofgiri** [amirzaidi/Launcher3#367]
`ninja: error: '/home/ridon/ridon/system/out/target/common/obj/JAVA_LIBRARIES/android-support-dynamic-animation_intermediates/classes.jack', needed by '/home/ridon/ridon/system/out/target/common/obj/APPS/Launcher3_intermediates/with-local/classes.dex', missing and no known rule to make it
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
`

any clue?

**Comment by amirzaidi** [comment]
Looks like you're missing the android support dependency. I only tested CAF and know it works there
