### ISSUE TITLE
Please include icon pack feature from Deletescape-Media/Lawnchair

### ISSUE THREAD

**Issue by yashptel** [amirzaidi/Launcher3#37]
Please include icon pack feature from Deletescape-Media/Lawnchair

**Comment by fishears** [comment]
I second that request. I'm all for sticking with stock PL features but even now most of my icons are rounded squares and I crave uniformity in my life ;)

**Comment by RikKoedoot** [comment]
Or for Samsung users, Just forse it to not use the square circle icons, but the default icons for the apps
