### ISSUE TITLE
google now swipe to dissmiss

### ISSUE THREAD

**Issue by zeeshanrasool91** [amirzaidi/Launcher3#371]
HI dear, i loved your work it is working flawlessly, just one issue its kind of irritating for me,
The only thing which is not working is google now cards swipe to dismiss behavior.

**Comment by amirzaidi** [comment]
This is something Google removed, and I cannot add it back

**Comment by zeeshanrasool91** [comment]
Nope Google Now Launcher has this feature, I used it,


When i install your app first it was working finebut after sometime it wasn't working and google now home Launcher ui changed




Regards:


Zeeshan Rasool







On Sat, Feb 24, 2018 at 1:28 AM +0400, "Amir Zaidi" <notifications@github.com> wrote:












Closed #371.

**Comment by amirzaidi** [comment]
Google Now Launcher hasn't been updated to support the new feed.

**Comment by zeeshanrasool91** [comment]
Okay Buddy By the way great work, i would love it if it is possible for you to add this feature, other wise i love this apk it is awesome




Regards:


Zeeshan Rasool







On Sun, Feb 25, 2018 at 3:54 AM +0400, "Amir Zaidi" <notifications@github.com> wrote:












Google Now Launcher hasn't been updated to support the new feed.

**Comment by nomius** [comment]
Hi,
Launcher3 is awesome, thanks for it.
Is it possible to be something else causing the swipe gesture to go away.
This is working using previous versions of launcher3 and also in nova.

Thanks in advance and best regards.

**Comment by amirzaidi** [comment]
Google just straight up removed it in the new feed versions, the only way to get it is to use the old feed which I won't do
