### ISSUE TITLE
Enlarged grid size with 3.2

### ISSUE THREAD

**Issue by mlleemiles** [amirzaidi/Launcher3#373]
Device is Sony Xperia Z5 Compact, 4.6 screen at 720p. Originally 4 columns now 5 columns, which is very clustered on a small screen device. Your launcher offers much better experience than official one with 4*5 grid size on my device. Thanks to the developer!

**Comment by michgauz** [comment]
Same here with my Honor 8.
Thanks spending your time on this project ! :)

**Comment by mlleemiles** [comment]
In the end I have to use fork version to adjust grid size without changing my dpi.
