### ISSUE TITLE
Bubble bounce on swipe up

### ISSUE THREAD

**Issue by vishalsonawane1811** [amirzaidi/Launcher3#376]
Can you also fix bubble bounce on swipe in next release on pixel launcher.

**Comment by skintask** [comment]
Have this issue too.

**Comment by suphon-t** [comment]
What is the "bubble bounce effect" you're talking about? Please explain.

**Comment by vishalsonawane1811** [comment]
When swipe up the app list bounce. That little effect. Later I got to know
it is the effect has on pixel launcher too.
Launcher is working smoothly.😊

**Comment by vishalsonawane1811** [comment]
Hey,

I just signed the petition "People of India who know what he deserves and
how much capable he is: SREESANTH BAN UPLIFTMENT" and wanted to see if you
could help by adding your name.

Our goal is to reach 6,783 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/Qc2DYrnxsF

Thanks!
Vishal
