### ISSUE TITLE
4 favorite icon

### ISSUE THREAD

**Issue by bogante** [amirzaidi/Launcher3#38]
Can you please make the favorite bar icon to 5? For 480dpi devices.

**Comment by amirzaidi** [comment]
No, lower your DPI slightly if you want five icons. Changing your DPI is possible on any device from Android 6 onwards.

**Comment by mirakzen** [comment]
you can edit in res/xml/device_profiles.xml

**Comment by mirakzen** [comment]
screenshots
https://s23.postimg.org/urix8t04b/Screenshot_20170616-100455.png
https://s2.postimg.org/9qjhrqqih/Screenshot_20170616-100510.png
https://s14.postimg.org/5d31s1v9t/IMG_20170616_100933.jpg

**Comment by amirzaidi** [comment]
I know you can but that will mess it up for other devices too.

**Comment by mirakzen** [comment]
I wrote it for @bogante, 'cause it depends on the person's preferences...
And he can build his own apk with different number of icons, like me. :)
