### ISSUE TITLE
Launcher gets pushed out of RAM too quickly, causing animation issues

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#381]
The same animation issue from previous versions is still present: https://youtu.be/z1YuV3tcV5Q
(Read video description for explanation.)

But the new 3.2 is noticably smoother than 3.1 though. And the weird animation happens a bit less frequently compared to previous versions.

WHAT I HAVE DISCOVERED:
When Google Feed is disabled, the animation issue is POOF gone. Hmmmmm...

**Comment by amirzaidi** [comment]
Then it's definitely a RAM problem. Your phone is force closing the app because it uses "too much" memory according to the phone.

**Comment by amirzaidi** [comment]
Thanks to my optimizations it uses less memory on 3.2, and the Google App accounts for most of the memory use

**Comment by nikkomercado** [comment]
@amirzaidi Is it still possible to make the launcher more optimized? Like super super super super optimized
