### ISSUE TITLE
Spacing issue in the app drawer in V3.2

### ISSUE THREAD

**Issue by kuberrohilla** [amirzaidi/Launcher3#383]
I am using Mi A1. With the new Version 3.2, the space between the 2 rows in the app drawer is too much. Attaching the screenshot for V3.1 and V.3.2 respectively. 
![v3 1](https://user-images.githubusercontent.com/32300989/36791080-d3761a60-1cbc-11e8-87cb-e2886af19171.png)
![v3 2](https://user-images.githubusercontent.com/32300989/36791081-d3ae2c0c-1cbc-11e8-93ba-1a7e0d924917.png)

**Comment by amirzaidi** [comment]
I did this deliberately because many people were complaining about how crammed together the icons are. Decrease your DPI a bit to get back the old 5x5

**Comment by ngdinhtoan** [comment]
@amirzaidi Thanks for great launcher.
I also have same situation with Moto Z2 Play. It would be nice if there is a setting to set icon grid to 5x5 or 5x6.

**Comment by kuberrohilla** [comment]
Yes exactly. But increasing the smallest width dpi value is a temporary solution. For my device,  363 dp got me 6x6 and also the trimmed out date issue was resolved.
