### ISSUE TITLE
Google adaptive icons

### ISSUE THREAD

**Issue by currall** [amirzaidi/Launcher3#385]
Can you enable adaptive icons on lollipop+? I noticed that in the Google icons pack you made that there were some adaptive icons elements, just wondering if this could be used in backporting adaptive icons on older versions.

**Comment by amirzaidi** [comment]
No and no, backporting adaptive icons requires a lot of ugly hacks to make the phone think it's running as Oreo, I've looked at the code for it and won't add it for stability reasons
