### ISSUE TITLE
Icon issue and feature request 

### ISSUE THREAD

**Issue by 9vmm** [amirzaidi/Launcher3#386]
First of all im new on github sorry for any mistake i made.
Very very thanks for this great launcher 👍. 
Im having an issue on round icons, some apps does not support round icons so they showup like android logo. Can you please add option to turn on or off round icons. And can you also add a feature to hide icons in launcher.

**Comment by amirzaidi** [comment]
Can you send a screenshot of those apps?

**Comment by grabinat** [comment]
Hiding icons is indeed the only feature I miss.
I accidentally open several times a day the wrong calendar or contacts app.
The launcher is really great and it really feels like an stock launcher. But every time I open the wrong app I get remembered it is an Samsung full of bloatware.

**Comment by amirzaidi** [comment]
Apply an icon pack like Google Icons, then you get access to the "Edit" menu where you can hide apps

**Comment by Bilbom** [comment]
How to enable notification badges on launcher3 Go version ??

**Comment by amirzaidi** [comment]
@Bilbom Wrong issue thread and it's disabled on the Go version.
Reopen if the main problem persists.
