### ISSUE TITLE
Theme Switch

### ISSUE THREAD

**Issue by currall** [amirzaidi/Launcher3#387]
Sorry if I sound ungrateful, but I have used this launcher constantly since v1.2, and with 3.0 it needed a theme switch instead of relying on the wallpaper. I like my dark wallpaper and do not want to change it so I can use the light theme when other launchers have a toggle for this.

Thank you if you add this.

**Comment by Dijimi** [comment]
Agree. I really like the launcher, but I don't like random theme color choice.

**Comment by amirzaidi** [comment]
I'm working on a workaround, but I'm not breaking the auto wallpaper extraction.
