### ISSUE TITLE
Missing icons - apps get removed from the app drawer and homescreen

### ISSUE THREAD

**Issue by LeyendaV** [amirzaidi/Launcher3#388]
When I turn off-on or restart my phone, some icons simply disappear not only from the main screen but also from the menu.
The apps are still installed on the device, but you can't access to them.

The apps that ALWAYS are gone are:
- Foursquare
- Soundcloud
- Shaman / Shazam Encore
- Truco Blyts
- BlazBlue Revolution Reburning
- Pokémon GO
- Makimono
- 漢字 学習

The apps that SOMETIMES are gone are:
- Instagram
- LINE
- Facebook Messenger (but the Lite version seems to be stable)
- Telegram
- Skype

**Comment by amirzaidi** [comment]
Are these installed on a SD card?

**Comment by LeyendaV** [comment]
Some of both groups ("always" and "sometimes") yes, others no. I thought the same at first.

**Comment by tysonseable** [comment]
I had this issue too

**Comment by amirzaidi** [comment]
Any pattern you noticed for which apps disappear?

**Comment by tysonseable** [comment]
It seems that apps not covered by my icon pack disappear the most.

**Comment by tysonseable** [comment]
I'm turning off my icon pack today to see if this resolves the issue and my new issue I just opened. I'll give out an update tomorrow.

**Comment by tysonseable** [comment]
Oh yeah. The second I turned off my icon pack, all of my apps came back. I forgot how many I had on my phone!!

**Comment by amirzaidi** [comment]
Can you search for these apps with the search bar in the app drawer when they are hidden?

**Comment by tysonseable** [comment]
I don't know right now, but disabling the icon pack fixed the issue.

**Comment by tysonseable** [comment]
The new update seemed to fix the issue. I haven't had any apps dissapear.

**Comment by amirzaidi** [comment]
Make sure that no apps are on the SD card if this comes back, SD cards are problematic
