### ISSUE TITLE
Galaxy S8 immersive mode shows navigation bar dot on homescreen

### ISSUE THREAD

**Issue by Danny616** [amirzaidi/Launcher3#389]
I don't know why but immersive mode is enabled on the launcher which causes the hide/show button on the far left of the nav bar to appear unlike on the native launcher the S8 comes with, which doesn't have the hide/show button on the nav bar when the launcher is applied

**Comment by amirzaidi** [comment]
I found how to disable the dot but lawnchair users threw a fit when it was disabled because they wanted to hide it.. might be better to keep the ability to hide it
