### ISSUE TITLE
Tablet Support

### ISSUE THREAD

**Issue by Grafcube** [amirzaidi/Launcher3#391]
App drawer lags on my tablet. Search bar icon disappears in landscape mode. Icons are too small with respect to screen size.

**Comment by amirzaidi** [comment]
Try the latest build, 3.3.

**Comment by Grafcube** [comment]
I tried 3.3 but the issue doesn't seem to be resolved.
- App drawer and google feed are extremely laggy.
- Search bar disappears in landscape mode.
- Icons are too small for tablet screen (7 inch).
- It drains my battery faster.
- At a glance is not showing my calendar events.

**Comment by amirzaidi** [comment]
Search bar and icon size are addressed, calendar events only show up for the next 30min, lag is caused by an underpowered device

**Comment by Grafcube** [comment]
Thank you for your help.
