### ISSUE TITLE
Double Screen Lock not working in V30

### ISSUE THREAD

**Issue by bhawanisajad** [amirzaidi/Launcher3#393]
LG V30 has functionality to turn off the screen when double tapping over it. But after installing this launcher, double tapping screen off does not work.
However when screen is already off, double tap does wake up the display.

**Comment by bhawanisajad** [comment]
Double tapping on Screen Lock not working in V30

**Comment by bhawanisajad** [comment]
This issue I faced with version 3.2

**Comment by ghost** [comment]
Double tap on screen is only implemented in LGs browser. However you can still double tap that status bar on top of screen and turn off screen.

**Comment by bhawanisajad** [comment]
Thanks
