### ISSUE TITLE
Nothing Works Except Google Feed

### ISSUE THREAD

**Issue by Randomblock1** [amirzaidi/Launcher3#394]
When using the latest compiled release, it doesn't load anything except Google Feed, which works perfectly fine. The search bar doesn't show up, the app drawer, home screen, nothing. Long-pressing doesn't even work.

Device info:
* Device: BLU R1 HD
* Android 6.0
* Pixel Launcher 3.2

**Comment by amirzaidi** [comment]
Reopen if this is still an issue to you, this seems to be a weird isolated case
