### ISSUE TITLE
Issue with grid

### ISSUE THREAD

**Issue by TheShark27** [amirzaidi/Launcher3#396]
Hi,
I love your launcher, but the 3.2 release has set a 5x4 grid as default. I like having 5 icons on the dock, but the drawer is now a mess: the icons are too close to each other, and the labels are only 7-8 characters long.
See this screenshot: https://imgur.com/a/1l49b
I have a 5 inches phone, with a 720p resolution, and the default on the most launchers is a 4x4 grid.
I have seen you won't add any grid resize options, but it would be nice to have a bigger grid for this dpi.
Thanks

**Comment by amirzaidi** [comment]
The majority wanted this look when possible, you can go back to 4x4 by increasing your DPI
