### ISSUE TITLE
Feature Request - Display Un-condensed Font

### ISSUE THREAD

**Issue by D1g1talEntr0py** [amirzaidi/Launcher3#397]
I really appreciate all the hard work that went into this project. It works great. I even get the traffic updates in the "At a Glance" widget. Something that I haven't seen work in any of the forks.

One thing that I think would be a great improvement would be to not have the default font condensed. That way the home screen and app drawer fonts would match the rest of the system.

Thanks again for this great launcher!

**Comment by amirzaidi** [comment]
I probably won't change this or add a setting

**Comment by D1g1talEntr0py** [comment]
I understand. Thank you
