### ISSUE TITLE
Icon Pack support

### ISSUE THREAD

**Issue by MrPerezident10** [amirzaidi/Launcher3#4]
Sorry if I'm going against what you said about it being simplistic, but I would really like icon pack support. That's why I never used the original pixel launcher. This would be my all time favorite launcher if it did.

**Comment by MrPerezident10** [comment]
Pixel launcher + icon pack support = 👌

**Comment by FixNinja** [comment]
Icon pack support will really make this perfect.

**Comment by amirzaidi** [comment]
https://github.com/Deletescape-Media/Lawnchair

Check this out if you want more features

**Comment by bappa555** [comment]
Icon pack support will be great
