### ISSUE TITLE
Nexus 6P still shows old navigation icons

### ISSUE THREAD

**Issue by git-itassistors** [amirzaidi/Launcher3#40]
My nexus 6P still displays the old navigation pane at the bottom with the old google now launcher icons and not the new little white icons

**Comment by RikKoedoot** [comment]
That's because the launcher has nothing to do with that, if you want to get it without root, try pixbar, or some free alternatives.

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v1.4

Could you guys try this? It should have the round icon support!

**Comment by amirzaidi** [comment]
You can change this using navbar apps, pixbar or a similar overlay for your navigation bar. I'm not going to add that into the launcher.
