### ISSUE TITLE
Create experimental P-pr1 version

### ISSUE THREAD

**Issue by elsondione** [amirzaidi/Launcher3#401]
Rebase to <a href="https://android.googlesource.com/platform/packages/apps/Launcher3/+/refs/tags/android-p-preview-1">tags/android-p-preview-1</a> when AOSP source is updated

download link apk
https://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-p-4623511-release/pixel-launcher-p-4623511-android-apk-download/

**Comment by amirzaidi** [comment]
That p-preview-1 tag is not complete and won't ever be updated. We'll have to wait until the r1 release of Android P in August. And no, I am not going to decompile the P Pixel Launcher without using P Launcher3 sources, I tried that for Oreo and I nearly became insane: https://github.com/amirzaidi/Launcher3/commits/o-p2-wip
