### ISSUE TITLE
Issue with Widgets on Motorolas G5/G5S/+

### ISSUE THREAD

**Issue by rotvaldi** [amirzaidi/Launcher3#405]
Most Motorolas have this common widget on middle:

https://dl.xda-developers.com/4/1/2/1/8/4/7/Circle_Clock_Widget_v6.jpg?key=nqyriuIXR5sor-F-A7ISBg&ts=1520691678

It makes tiny the widget impossible to edit the size.
You can have the widget too to try:

https://mega.nz/#!tg1xiBBT!pCV0PUNFvm7-OEEcVwrKWamdwqw2MwFzkQwXunW90hY

**Comment by amirzaidi** [comment]
This is not a bug but an artificial limitation Motorola has put on their widget.

**Comment by rotvaldi** [comment]
But yet I can Increase with other launchers and such

**Comment by amirzaidi** [comment]
Yes, those launchers removed the limitations manually. I know exactly how to remove the limits but I won't remove them, because Google doesn't intend for those limits to be removed

**Comment by rotvaldi** [comment]
:/ Your launcher is so good I just need it :(

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/blob/o-mr1/src/com/android/launcher3/AppWidgetResizeFrame.java#L123

Replace this line with
`mResizeMode = AppWidgetProviderInfo.RESIZE_BOTH;`

Then compile and you'll have the behaviour you want.
