### ISSUE TITLE
Display Google App after restart its impossible to swipe on the left

### ISSUE THREAD

**Issue by rotvaldi** [amirzaidi/Launcher3#406]
Display Google App after restart its impossible to swipe on the left, I must redo again and try to not restart the phone.

**Comment by nikkomercado** [comment]
Me too

**Comment by amirzaidi** [comment]
Are you guys on the Google App Beta? If yes, roll back to stable

**Comment by gmull70** [comment]
I'm having this issue as well. I got rid of Google beta. Not sure what else to try

**Comment by gmull70** [comment]
Also when I can't type in the Google window at the bottom of the home screen

**Comment by amirzaidi** [comment]
That happens because of Telegram. I'm not kidding, the real Telegram messes something up with the Google App, try switching to Telegram X

**Comment by gmull70** [comment]
I don't use telegram

**Comment by alecbe** [comment]
Just installed latest Google update (not beta) and my devices are having this issue. No problem prior to the update.
Update:  Problem now seems to have disappeared???

**Comment by dbesoli** [comment]
I've seen this issue too along last weekend. The only solution is to disable/enable the google's app on the left. I'm not in Beta of google app and not using Telegram

**Comment by ngdinhtoan** [comment]
I have got same issue, and resolved by installing newest [Google Icons](https://github.com/amirzaidi/GoogleIcons/releases) app.
Maybe you guys can try if it helps.

**Comment by dbesoli** [comment]
I've installed last version of google icons since Amir launched on Forks Telegram Channel 5 days ago.

**Comment by ngdinhtoan** [comment]
uhh... I don't have Telegram, JFYI.

**Comment by amirzaidi** [comment]
Roll back to Google App 7.22.24 from APKMirror if you are having this issue

**Comment by securityboy** [comment]
Go to > More Settings > Toggle the 'Display Google app' radio button to off then on.  You have to do this with every update.

**Comment by gmull70** [comment]
Not seeing "more settings". I use the S7 edge from Sprint.

**Comment by amirzaidi** [comment]
The new update (3.5) should have fixed this I think?

**Comment by gmull70** [comment]
It did not fix the issue for me

**Comment by amirzaidi** [comment]
Reopen if this still is an issue on the latest launcher and Google App.
