### ISSUE TITLE
OnePlus Android 8.1 breaks search bar icon and other icons

### ISSUE THREAD

**Issue by ayrton2510** [amirzaidi/Launcher3#410]
Updated my OnePlus 5T to Android 8.1 today, and the search bar is broken. Not showing the google logo. Also it always lags when swiping for Google App.
![screenshot_20180311-084858](https://user-images.githubusercontent.com/16276452/37252944-8f78acc4-2509-11e8-8309-4650cfcf95c6.png)

**Comment by amirzaidi** [comment]
OnePlus issue, many are reporting it, hopefully OnePlus fixes it soon.

**Comment by aybouzaglou** [comment]
Having the same issue as well with the one plus 5t on 8.1

**Comment by amirzaidi** [comment]
Fixed on new Open Beta.
