### ISSUE TITLE
It does not support fuzzy search chinese application name

### ISSUE THREAD

**Issue by wang20150419** [amirzaidi/Launcher3#414]
such as:  Appname: 支付宝,  find: 宝, the result is NULL.

but LawnchairLauncher support.

**Comment by amirzaidi** [comment]
Can you try the latest build on Telegram? https://t.me/appforks

**Comment by wang20150419** [comment]
The latest version (from Telegram) also does not support fuzzy search for Chinese application names.

**Comment by amirzaidi** [comment]
I think the Launcher3 default algorithm only tries searching from the start of words, it's that way in English too. Does searching for the first character work?

**Comment by wang20150419** [comment]
searching for the first chinese character is ok.

**Comment by amirzaidi** [comment]
That's expected behaviour then, Google only allows searching from the start of words. Lawnchair might have changed the algorithm but I will keep it like this
