### ISSUE TITLE
Icon pack not applying launcher crashes.

### ISSUE THREAD

**Issue by sumitsk321** [amirzaidi/Launcher3#415]
In the previous builds icon pack is working fine but in the latest 3.3 version same icon pack is not applying and launcher crushes.
Android 5.1.1.near stock

**Comment by michaelangelo2525** [comment]
Ive downloaded 3.3 version and working perfectly with my note 8 :) 
Keep up the update dev!!!

**Comment by amirzaidi** [comment]
Give me a logcat of the crash @sumitsk321

**Comment by sumitsk321** [comment]
[logcat.log](https://github.com/amirzaidi/Launcher3/files/1802713/logcat.log)
I try again to apply the icon pack.the launcher start stuttering and after sometime icon pack is applied but it takes too much time to apply the icon pack.This time launcher does not crash.Sometimes it crashes and the icon pack is also not applied.

**Comment by amirzaidi** [comment]
That is one weird crash.. looks like something is wrong with your phone, it can't load a string that is hardcoded in the XML

**Comment by sumitsk321** [comment]
Now it is working fine. Thanks for looking into this.
