### ISSUE TITLE
Searchbar showing random icons instead of Google

### ISSUE THREAD

**Issue by Cornflex92** [amirzaidi/Launcher3#419]
I recognized with launcher version 3.3 that the Google searchbar is showing random icons from my homescreen instead of the grey or colored Google logo.
Device: OnePlus 5T
Android Version: 8.1.0

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/issues/410

**Comment by aybouzaglou** [comment]
Same here
