### ISSUE TITLE
Weather widget does not work

### ISSUE THREAD

**Issue by Dabrador** [amirzaidi/Launcher3#42]
I've tried everything...location off/on; refresh Google Now; turn off/on Google feed; Reboot device...nothing. The weather widget will not show, just the date.

**Comment by amirzaidi** [comment]
Is the weather properly showing in the Google Now feed?

**Comment by Dabrador** [comment]
That did it. I had answered No to weather updates within Google Now.  Changing it to Yes made the weather appear in the widget.

Thanks for your help.

**Comment by StalkAlex** [comment]
@amirzaidi  are you supporting weather instead of time on home screen? Now it shows only date, weather widget on left google now screen is working properly.
