### ISSUE TITLE
My adaptive icon shows up round on Pixel phones, but not on Rootless Pixel Launcher

### ISSUE THREAD

**Issue by casolorz** [amirzaidi/Launcher3#421]
I added an adaptive icon to my app. It works fine on Pixel and Pixel 2. But on a Nexus 6 with the rootless pixel launcher it doesn't work. I can see other round icons on the Nexus 6 so it is working for other apps. 

My manifest looks like this:

      <application
            android:name=".MyAppclass"
            android:allowBackup="true"
            android:hardwareAccelerated="true"
            android:icon="@mipmap/ic_launcher"
            android:label="@string/app_name"
            android:largeHeap="true"
            android:theme="@style/MyTheme">

And on `mipmap-anydpi-v26` I have `ic_launcher.xml` that looks like this:

    <?xml version="1.0" encoding="utf-8"?>
    <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
        <background android:drawable="@drawable/ic_background_icon"/>
        <foreground android:drawable="@drawable/ic_foreground_icon"/>
    </adaptive-icon>

What am I missing?

Thanks.

**Comment by amirzaidi** [comment]
Does your Nexus 6 run Oreo? Adaptive icons only work on Oreo

**Comment by casolorz** [comment]
7.1.1 
That is odd because I see round icons for almost every app when using this launcher, and if I switch to the "Google Now Launcher" then those same apps don't have round icons.

**Comment by amirzaidi** [comment]
You need to add a manual roundIcon drawable using the roundIcon attribute in your application.
