### ISSUE TITLE
Icon Not Rounded

### ISSUE THREAD

**Issue by christahir** [amirzaidi/Launcher3#422]
Hi Amir,
I had MIUI 9 with dev ROM latest version which is Oreo 8.0.
Am using Xiaomi Mi6

The launcher failed to force the icons to round, I have set the icon shape to Round, but it failed. Unless I use icon pack to replace the icon. Is there any solution other than installing icon pack? Thanks

**Comment by amirzaidi** [comment]
Send a screenshot. And are you using Substratum? All OMS overlays break the round icon forcing.

**Comment by RuthlessRuler** [comment]
Well, some apps do fail to get round icons, and I think that's due to the app not having its custom round icon or whatever that is. For me the camera icon never gets round icon.

![screenshot_pixel launcher_20180315-041058](https://user-images.githubusercontent.com/20885012/37434811-ef8d07ae-2806-11e8-9a9d-d4be9f9632f8.png)

**Comment by christahir** [comment]
Hi,

I am using this ROM.
http://en.miui.com/download-326.html

![screenshot_2018-03-15-08-51-07-013_com android settings](https://user-images.githubusercontent.com/36660716/37440182-33d40968-282e-11e8-8008-1634fc1efb0e.png)
![img_20180315_084724_355](https://user-images.githubusercontent.com/36660716/37440169-27886dc0-282e-11e8-9cfc-449bdc4f3f82.jpg)
![img_20180315_084724_297](https://user-images.githubusercontent.com/36660716/37440170-27be8b1c-282e-11e8-9b8b-5d7097656012.jpg)
![img_20180315_084724_325](https://user-images.githubusercontent.com/36660716/37440171-27f67f0e-282e-11e8-9a14-dc2b47a339eb.jpg)

**Comment by christahir** [comment]
So, in order to round all icons, I use Pixel Icon Pack, but some can be editted to their original shape like Whatsapp or Camera

**Comment by amirzaidi** [comment]
Those apps don't have a round icon. I can't force round icons if the icons don't exist
