### ISSUE TITLE
No way to unhide an application in the app drawer (v3.3)

### ISSUE THREAD

**Issue by michaeloryl** [amirzaidi/Launcher3#423]
If you long press on an icon in the app drawer in Launcher3 **v3.3**, and then press on the edit icon (pencil) or select the edit menu option, you can choose to "hide app".  That works fine.

There does not seem to be a way to bring something back, though.

If the app's icon is not shown in the app drawer, then there is no way to long press upon it and edit it to put it back in the app drawer.

Perhaps if I had a shortcut to it already on the home screen I could do it there, but that is not the case.

Do I have to uninstall and reinstall the application to get it back?  I don't really want to do that.

**Comment by amirzaidi** [comment]
Search for it with the search bar

**Comment by michaeloryl** [comment]
@amirzaidi - I tried that before I posted.  It was my first thought.  It does not work.

I just hid a second app and now can't restore it, either.  The only way to get to the app is to find it in the Play Store or to search for it from the Google Search on the home screen.  But you can't do it from the app drawer, and the home screen search method doesn't give you a way to re-enable it in the app drawer.

If this is not the norm, then allow me to provide some hardware/software details that might help:

I'm running a OnePlus 5T.  Android 8.0.0.  OxygenOS 5.0.4.

**Comment by amirzaidi** [comment]
Disable your icon pack then enable it again. It's a bug caused by updating from 3.1 to newer without re-enabling your icon pack. After that you can search for them

**Comment by michaeloryl** [comment]
Yes, disabling the icon pack brought it back.  I have re-enabled it to hide the icon again, but it is now searchable.  Thanks.
