### ISSUE TITLE
Edit button doesn't work

### ISSUE THREAD

**Issue by RuthlessRuler** [amirzaidi/Launcher3#424]
The edit button for each app doesn't work.
![screenshot_pixel launcher_20180315-040313](https://user-images.githubusercontent.com/20885012/37434559-f700ceae-2805-11e8-874e-0e8bfd7e6bbe.png)

Also, the ability to set custom icons for individual apps will be great.

**Comment by amirzaidi** [comment]
That Edit isn't a button but a subtitle :/

**Comment by RuthlessRuler** [comment]
So can you add a edit button so we can change icon for particular apps, and we can change their name. 
Most of the Launchers have it now days, it will be great addition.

Also, why dont you add the new changes of Android P, heard on XDA its already ported to Oreo
