### ISSUE TITLE
Widget cuts out

### ISSUE THREAD

**Issue by adrianfdiratama** [amirzaidi/Launcher3#429]
Take a look at this 
![screenshot_20180316-205839](https://user-images.githubusercontent.com/37389971/37524681-2d1c4790-295d-11e8-9b74-20bfc124d8d8.jpg)

**Comment by amirzaidi** [comment]
Which version is this? What DPI are you using?

It's not even supposed to show events that are 3h in the future

**Comment by adrianfdiratama** [comment]
I'm on v.33. The DPI is 480.
I'm not using the at a glance on the Pixel Launcher instead of using 3rd party widget named Another Widget.

**Comment by amirzaidi** [comment]
Then it's Another Widget's fault.
