### ISSUE TITLE
Add to Home screen for websites doesn't work

### ISSUE THREAD

**Issue by aronfiechter** [amirzaidi/Launcher3#43]
When on Chrome I try to add a website to the home screen, all happens as it should (I get to choose the name, and after accepting a toast appears saying it was added), but when going to the home screen, nothing was added.

This is a big issue when it comes to progressive web apps, where adding a website link to the home screen provides an actual offline app (example: the Google I/O website).

**Comment by RikKoedoot** [comment]
Try the chrome bookmark widget for now, untill it's fixed

**Comment by amirzaidi** [comment]
Well the problem is that I can't reproduce this, please give me more info about your setup

**Comment by cheuer** [comment]
This isn't working for me either, using version 1.3 on Android O Preview 3 on a Nexus 6P.

**Comment by aronfiechter** [comment]
I just tried with the default launcher (Google Now Launcher) and it also does not work. It could therefore just be a problem of Chrome or Android O Beta.

My setup is: Nexus 6P, Android O Beta, version 8.0.0, Security patch level May 2017.

**Comment by RWOne** [comment]
Agreed chrome or O issue there.

I just tried on my Nexus 6 on 7.1.1 and it added the shortcut to an available spot on one of my homepages.

**Comment by aronfiechter** [comment]
I submitted feedback to Android O Beta.

**Comment by aronfiechter** [comment]
The issue is still present, and is present whenever the default launcher (in my case Google Now launcher) is not set as default.
If I have no default launcher set and I am on Google Now launcher (where I have some website shortcuts) and I try to tap them they say they are unavailable. When I set the default to Google Now launcher, the shortcuts work.
These website shortcuts are actually chrome app shortcuts.
Could it be that there are some extra settings to activate in order to be able to get chrome app shortcuts?

**Comment by amirzaidi** [comment]
New version coming tomorrow based on 8.0.0_r3 (well, I'm trying: https://github.com/amirzaidi/Launcher3/commits/o)
If that doesn't resolve it I'll see if I can figure out why this happens

**Comment by AxiK101** [comment]
Thanks, can't wait

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aronfiechter** [comment]
Works on latest debug release.
