### ISSUE TITLE
Hiding Android for Work apps from app drawer hides the original app instead

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#431]
I am using the Island app by Oasis Feng to be able to use two accounts simultaneously on any app. Two entries of an app would show up in app drawer, one of which has Android for Work badge. I want those with badges to show up only in home screen so I made shortcuts for them. Now when I hide those in app drawer (to remove clutter), the original app is the one that became hidden, the one with badge stayed.

**Comment by amirzaidi** [comment]
Can you contact me on Telegram? https://t.me/mirai

I want to do some Android Work tests so we can properly resolve this, but I don't have an Android Work license/account

**Comment by ghost** [comment]
@amirzaidi I don't have an Android for Work account, either. Island can enable Android for Work without an account, but with root (at least on my phone, AFAIK some devices just need adb commands without root).

**Comment by amirzaidi** [comment]
Can you test if everything works fine on the latest 2 Telegram alphas? https://t.me/appforks

**Comment by ghost** [comment]
It does work for both versions. It can now distinguish between the original and Work app. But it has a bug. When I try to hide an original app, it still shows up in search, which is good because I can open it from there. But when I try to hide Work app, it doesn't show up in search. I have to clear data of the launcher.

**Comment by amirzaidi** [comment]
Can you check the new build?

**Comment by ghost** [comment]
It works now. Thanks. Is this unreleased version OK for daily use, though?

**Comment by amirzaidi** [comment]
Well if you find any bugs be sure to report them to me, if it weren't for this report it might've never been fixed
