### ISSUE TITLE
Icon Shape

### ISSUE THREAD

**Issue by bappa555** [amirzaidi/Launcher3#432]
First of all thank you for this app with customized pixel launcher.
Can you please add an option to remove icon shape.
I am using a Nokia 6 device which use circular icon shape by default and I like the icons without any shape. Have tried some icon pack but don't like that.
So it will be great if you can add this option to use icon without any shape.

Thank you.

**Comment by amirzaidi** [comment]
Unfortunately this is not possible anymore because of the way adaptive icons work on Android 8 and higher. They always have a background
