### ISSUE TITLE
Icon/DPI change

### ISSUE THREAD

**Issue by bcet1** [amirzaidi/Launcher3#434]
HTC 10, updated from v3.0 of the launcher to 3.3, and lost a row of icons. Is there any way to get them back?

At a Glance also no longer shows weather.

![image](https://user-images.githubusercontent.com/37730009/37861463-ec27b30c-2eff-11e8-8a39-02cf1a89e453.png)

![image](https://user-images.githubusercontent.com/37730009/37861464-fbc89e3e-2eff-11e8-8efc-485faadfb5a4.png)

**Comment by amirzaidi** [comment]
Yep, change your "display size" in your phone's settings. I removed the row for your display size because many people were complaining about text overlapping with icons and other weird bugs caused by the cramped layout
