### ISSUE TITLE
Network stats not showing on status bar

### ISSUE THREAD

**Issue by muhammadx2k** [amirzaidi/Launcher3#436]
Everything is fine, but when I open the app drawer the network status bar not showing because it's white. The clock and H+ text become black so I can see these. But the network chart is white so it is not visible. This issue was from the first release but not solved in new releases. I believe it will be fixed in next release. Thank you.

**Comment by muhammadx2k** [comment]
Here is a screenshot for your understand - https://drive.google.com/open?id=11ZVULwcOoi3JLz3cyRsw8WUbnS6v_7oV

**Comment by amirzaidi** [comment]
Which phone/ROM is this

**Comment by muhammadx2k** [comment]
It's a very unpopular made in Bangladesh phone named STARK IGNITE V1 with Android 6.0 and I think it's on Android default rom. Also the device isn't certified by Google.

**Comment by amirzaidi** [comment]
I think I'm not able to fix this, it's a bug with your phone's OS
