### ISSUE TITLE
Suggestion - Backup and Restore

### ISSUE THREAD

**Issue by NTbacon** [amirzaidi/Launcher3#437]
Thank you for your hard work.

This launcher is amazing.

Just a suggestion - give a method to backup and restore desktop shortcuts and layouts.

Thus when you issue a new update as we follow you - we can quickly and easily do the update.

How difficult is this?

Thank you again.

**Comment by amirzaidi** [comment]
You should already be able to update without issues, just install the new APK on top. You don't have to delete the old one first, never did

**Comment by NTbacon** [comment]
Thank you :)
