### ISSUE TITLE
Most accesed Apps with duplicated items

### ISSUE THREAD

**Issue by dbesoli** [amirzaidi/Launcher3#439]
After one of the latest updates from the Telegram channel "appforks" I got Microsoft Solitaire duplicated

![image](https://user-images.githubusercontent.com/20066771/38020058-98f4c83c-3279-11e8-843c-d5534e8cd615.png)

**Comment by dbesoli** [comment]
About the list, I'm sure my most accessed apps aren't solitaire and fing but....
I open normally directly from launcher, whatsapp, telegram, gmail, chrome and Talon. And Huawei Wear and Fit only one time every morning. But this is not a pb to me because I don't use it...maybe because it doesn't contains my most used. :)

**Comment by amirzaidi** [comment]
Read the pinned message in the Telegram channel..

**Comment by amirzaidi** [comment]
And it shows the apps you launched from the app drawer most frequently, it's useless to duplicate the apps that are already on your homescreen

**Comment by dbesoli** [comment]
As you suggested, turning off and on the app suggestions in the settings fixed the issue about duplicates and now it shows a more reliable list
google photos, maps, mail, settings and whatsapp

sorry for no reading the pin
