### ISSUE TITLE
Long press actions not working

### ISSUE THREAD

**Issue by victormunduruca** [amirzaidi/Launcher3#44]
Device is a Moto z play on 7.0.0

**Comment by victormunduruca** [comment]
I saw in another issue that 7.1.1 is required for this. Is there any way of implementing this like nova? Awesome port by the way

**Comment by ghost** [comment]
@victormunduruca
So this launcher feature will not work on 6.0

**Comment by amirzaidi** [comment]
Won't work until you're on 7.1 or higher.

**Comment by ghost** [comment]
@amirzaidi 
Other modders made this work on older versions. versions of Android.. can't you use some of that code to implement the Quick Shortcuts to work with versions older than 7.1?

**Comment by amirzaidi** [comment]
It's not high on the priority list but I'll see what I can do later

**Comment by ankurk91** [comment]
![screenshot_20170616-084603](https://user-images.githubusercontent.com/6111524/27210476-6a545400-5270-11e7-9fd9-a13cf3831fb7.png)

Long press actions are the only reason that is stopping me to use this version of pixel launcher.

I am using [this](https://forum.xda-developers.com/android/apps-games/backport-pixel-launcher-o-3952143-t3608873) version and long press action works fine on my Moto G4 Play.

**Comment by madvinegar** [comment]
Ankurk91, long press actions may be working on other pixel launchers based on android O, but if you are not on android 7.1+, all you get as actions is "widgets" and/or "app info".

**Comment by ankurk91** [comment]
@madvinegar 
I am on android 6.0.1 and only "widgets" and "app info" appear for me. Thats ok.

What i am trying to show here is that **amirzaidi/Launcher3** launcher does not have this feature yet while [this](https://forum.xda-developers.com/android/apps-games/backport-pixel-launcher-o-3952143-t3608873) has this feature. This launcher was backported from android o dp2. 
OR
At least long press should works as "Google now launcher" which shows options to "uninstall" and "app info".

**Comment by madvinegar** [comment]
@ankurk91 
Yes, I understand and I agree with you. I am just saying that the ideal thing would be to have the proper long-press actions of each app, and not just the "widgets" and "app info".

If you just get the "widgets" and "app-info", it means almost nothing as you can just long press the app and drag it on the top of the screen to uninstall it, or find the info of it etc.

**Comment by madvinegar** [comment]
For example, see how many options you get on Twitter.
It means almost nothing to just get "widgets" and "app info"...
TBH I am more concerned about notification badges.

![screenshot_20170616-104553](https://user-images.githubusercontent.com/11718763/27217184-71c5607e-5281-11e7-94c9-74dc10dcc192.png)

**Comment by ravithoria** [comment]
Yup, missing app shortcut for 7.0 request to high priority
