### ISSUE TITLE
Pixel launcher crashing every morning

### ISSUE THREAD

**Issue by tysonseable** [amirzaidi/Launcher3#441]
My launcher crashes every morning and says it has stopped. I'm not sure if this issue is related to my icon pack or not. I'll turn off my icons and give an update tomorrow.

**Comment by amirzaidi** [comment]
Are you on the newest version? This was a bug in 3.0 that I thought I had fixed

**Comment by tysonseable** [comment]
Yes I'm on the latest version

**Comment by tysonseable** [comment]
And yes, disabling the icon pack fixed the bug

**Comment by amirzaidi** [comment]
Can you send me a logcat

**Comment by tysonseable** [comment]
How do I do that?

**Comment by amirzaidi** [comment]
Google it
