### ISSUE TITLE
Home Buttons Bar is White after Oreo Update - LG V30

### ISSUE THREAD

**Issue by bigdaddyral** [amirzaidi/Launcher3#442]
The bottom bar was transparent on the home screen until AT&T updated my phone to Oreo this morning, now it's white.

**Comment by amirzaidi** [comment]
Enable "18:9 fullscreen" mode for the launcher in your phone's settings

**Comment by bigdaddyral** [comment]
Hi Amir,

That no longer appears to be an option in my settings. Everything was fine
until the Oreo Update this morning.

Regards,
Raul

This email was sent from my phone, please excuse the spelling and
punctuation.

**Comment by bigdaddyral** [comment]
When I go to Settings > Display > App Scaling, Pixel launcher is not listed.

**Comment by monta990** [comment]
I have the same problem with my LG g6 h873 in android 8.0

**Comment by amirzaidi** [comment]
Fixed in alphas (on Telegram: @appforks)
