### ISSUE TITLE
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.android.launcher3 attempting to redeclare permission 

### ISSUE THREAD

**Issue by Iamasthme** [amirzaidi/Launcher3#444]
Whenever i try to install, it's giving error like this

Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.android.launcher3 attempting to redeclare permission com.google.android.apps.nexuslauncher.permission.QSB already owned by com.google.android.apps.nexuslauncher]

adb shell pm uninstall com.android.launcher3
Unknown failure (at android.os.Binder.execTransact(Binder.java:697))
Error while Installing APK

i am using pixel 2

**Comment by amirzaidi** [comment]
Pixel 2 needs to use the Magisk Module (with root) because this launcher can't coexist with the real Pixel Launcher
