### ISSUE TITLE
Google Feed stop working after lock

### ISSUE THREAD

**Issue by NTbacon** [amirzaidi/Launcher3#446]
Device: Samsung Galaxy s7
OS: Official Android 7.0
Security updates: all Official
Google up to date
Launcher version: 3.4 AOSP

Troubleshooting steps:
Enable and disable feed - started working again until screen lock.
Uninstall Google. Reinstall Google. No change.

Please help. I love this launcher and would like to pay for it once it's complete.

**Comment by NTbacon** [comment]
Sorry. Apparently i have to roll back to a previous version.  Google App 7.22.24?

**Comment by dbesoli** [comment]
Device: Huawei P9
OS: Official Android 7.0
Google up to date
Launcher version: latest from forks channel

I've seen this issue too along last weekend. The only solution is to disable/enable the google's app on the left.

**Comment by amirzaidi** [comment]
I would highly recommend that, yes

**Comment by amirzaidi** [comment]
Reopen if this still is an issue on the latest launcher and Google App.
