### ISSUE TITLE
Add support for alternate icons from icon packs

### ISSUE THREAD

**Issue by wouterroos** [amirzaidi/Launcher3#447]
Hi,

Recently switched from Nova Launcher to your launcher and I must say I'm impressed! It works really great and so far I haven't had any issues. One feature I would love to see is the ability to customize the icon per app, so that you can pick an alternate icon from one of your icon packs if that pack doesn't support that specific app. This would in my experience vastly improve the experience since you could then make all your apps have the same icon style. 

Thanks for the work so far!

**Comment by mlleemiles** [comment]
Have you tried Ruthless Launcher?

https://forum.xda-developers.com/android/apps-games/app-ruthless-pixel-launcher-based-t3755903

**Comment by wouterroos** [comment]
@mlleemiles Thanks for the tip, I tried this launcher and it looks quite good. However, I noticed that it also has a different 'style' regarding the Dockbar. I looked through the settings if I could get it to match this launcher, but no luck so far. Am I missing something or is this by design?

**Comment by wouterroos** [comment]
@mlleemiles Never mind, I read that you implemented the Android P style launcher in the last update. I installed a previous version which gave me the style I wanted. Any plans for a toggle in future versions?

**Comment by amirzaidi** [comment]
Closed in favour of https://github.com/amirzaidi/Launcher3/issues/508
