### ISSUE TITLE
Feature Request: New 2 Bubble Search Bar

### ISSUE THREAD

**Issue by lnaber** [amirzaidi/Launcher3#448]
I would really like to see the new search bar with the 2 bubbles. 
Until now, I've been using paphonb's launcher, but sadly, it doesn't support icon packs.

I've been using this launcher for about a week now, and I'm really enjoying it, but it would be nice if you could include the new search bar.

**Comment by amirzaidi** [comment]
I'm not going to mix the 8.1 and 9.0 launchers, when 9.0 sources are out I will rebase on that and add the new features.
