### ISSUE TITLE
Google app not working with icon pack

### ISSUE THREAD

**Issue by bappa555** [amirzaidi/Launcher3#449]
Google app page is not working when the launcher is used with third-party icon pack on Nokia 6 running on oreo 8.1

**Comment by Frontear** [comment]
Couldn't this be an issue with the icon pack not actually skinning the google app? Can you provide the name of the icon pack?

**Comment by bappa555** [comment]
​I have tried with MIUI 9 - Icon Pack by LeoMaz dev.​


*Thanking You,*


*Abhisek Pal*(M) +91 9830 200384

**Comment by amirzaidi** [comment]
Reopen if this still is an issue.
