### ISSUE TITLE
Icons label color is lighter on tablet than on smartphone

### ISSUE THREAD

**Issue by ekerazha** [amirzaidi/Launcher3#453]
In the app drawer, the icons label (the text below icons) is dark grey on my smartphone, but it is light grey (therefore more difficult to read) on my Samsung Tab S2 tablet.

Could it be an issue similar to Issue #122 ?

**Comment by amirzaidi** [comment]
Working on this for 3.5, try the latest alpha on https://t.me/appforks

**Comment by ekerazha** [comment]
Fixed in 3.5 alpha, thank you
