### ISSUE TITLE
Duplicate app suggestions on app drwaer

### ISSUE THREAD

**Issue by lrweck** [amirzaidi/Launcher3#454]
Hello, I'm seeing duplicate app suggestions on app drawer on v3.4. 
![screenshot_20180407-120250](https://user-images.githubusercontent.com/26086198/38456516-d9baeb0a-3a5b-11e8-8fd0-603a511db974.png)

**Comment by amirzaidi** [comment]
Read the warnings section on the reddit thread

This will only happen once when going from 3.3 to 3.4 and can be fixed by just using the launcher or disabling and enabling app suggestions
