### ISSUE TITLE
Duplicated recent app

### ISSUE THREAD

**Issue by mtebele** [amirzaidi/Launcher3#455]
I've found out that Slack app icon is duplicate in the most recent section.

Oxygen OS 5.0 (Android 8.0.0)
Pixel Launcher 3.4

![screenshot_20180407-163124 01](https://user-images.githubusercontent.com/4268555/38459651-cb902320-3a82-11e8-8746-46aa8ba4b718.jpg)

**Comment by Keith94** [comment]
#454
