### ISSUE TITLE
Swiping to open Google page on the left doesn't work

### ISSUE THREAD

**Issue by k3lt** [amirzaidi/Launcher3#456]
It worked at first but now it doesn't, swiping doesn't show the Google page.
Enabling / Disabling it in settings doesn't fix it, it's happening since v3.4, i'm not using icon pack.
Edit: After installing icon pack it suddenly started working..

**Comment by mlleemiles** [comment]
You need to restart your Google app

**Comment by amirzaidi** [comment]
Google app problem, has been fixed in Google app beta
