### ISSUE TITLE
Gradient on top of the screen

### ISSUE THREAD

**Issue by jakeyakut** [amirzaidi/Launcher3#458]
I love your launcher and it is almost perfect!
The sad thing is that annoying gradient highlight or whatever on the top of the screen which makes dark wallpapers look way uglier than they really are.
Any chance it can be removed?
![getattachmentthumbnail](https://user-images.githubusercontent.com/38212909/38495614-d236d826-3c2c-11e8-9f17-5dab4652b0f6.jpg)

**Comment by mlleemiles** [comment]
I don't see any using a dark wallpaper (l3go version). Is your screen lcd?

**Comment by jakeyakut** [comment]
Galaxy s8, so it's amoled

**Comment by jakeyakut** [comment]
It isn't there on the l3go version, but the grid is smaller

**Comment by amirzaidi** [comment]
Yes, it is already removed on the alphas :)
