### ISSUE TITLE
Google feed..!

### ISSUE THREAD

**Issue by bolltzain** [amirzaidi/Launcher3#459]
![](https://i.imgur.com/c7L7bw8.png)

Manufacturer : Motorola
Model : Moto C Plus
Product : lineage_panelli
Screen Resolution : 720 x 1280 pixels
Android Version : 7.1.2

**AWESOME LAUNCHER** please fix these issues given below:

Google feed stops working after I switch between recent apps. To enable it I have to go to the Launcher's settings again and again. Sometimes long press doesn't works at all.

See the attached screenshot.

Thanks for reading.:relaxed:

**Comment by mlleemiles** [comment]
Just restart Google app and I think you are good.

**Comment by wootts** [comment]
I have the same issue, I tried restarting app and phone. I jumped from 3.1 to 3.4. I'm now on 3.3 and all is well. So must be a bug in 3.4. thanks

**Comment by DanGLVK** [comment]
The newer versions of the google app are randomly breaking the google feed,the dev recommends users to downgrade to this version https://www.apkmirror.com/apk/google-inc/google-search/google-search-7-22-24-release/ as its the one before it started glitching out

**Comment by bolltzain** [comment]
@mlleemiles it helped. Thanks :relaxed:
