### ISSUE TITLE
Not working on P20 Pro Huawei

### ISSUE THREAD

**Issue by RubyRP1** [amirzaidi/Launcher3#461]
Bought a Huawei P20 Pro, and using yout launcher succesfully on my S9+ before. 

When it's installed and i change for your launcher, EMUI throw an error and pull away instantly your launcher. 

:/

**Comment by mlleemiles** [comment]
Post logcat so the dev can know what's wrong :)

**Comment by RubyRP1** [comment]
Hi, i don't know how to log cat precisely ;) But i found a way to make it works.
I installed the 3.4 version. Going to app, Pixel launcher, after that, parameters of the lauch screen, authorize notifications... After that it force close, just cancel, go to app, default app, and change Huawei Launcher with Pixel Launcher and it doesn't force close anymore...
