### ISSUE TITLE
Setting to hide search bar at the bottom?

### ISSUE THREAD

**Issue by orschiro** [amirzaidi/Launcher3#465]
Hey @amirzaidi love your launcher and use it on my Moto G2. :-)

Question. Could we add a setting to hide the search bar at the bottom?

Don't really need it and maybe it's useful for other users too!

Thanks!

![image](https://user-images.githubusercontent.com/170947/38731718-cdfe1124-3f1b-11e8-81a1-ca862258f2bf.png)

Tried turning off these settings:

![image](https://user-images.githubusercontent.com/170947/38731727-dbc30652-3f1b-11e8-9135-ef9f33739bfc.png)

**Comment by mlleemiles** [comment]
Use fork version like Lean or Ruthless Launcher. If you actually paid attention to dev's readme you wouldn't have asked this question.

**Comment by orschiro** [comment]
You're totally right! Sorry, I had only briefly skipped over the README. 

Please apologise the noise....
