### ISSUE TITLE
Open Source License missing

### ISSUE THREAD

**Issue by Paul23ok** [amirzaidi/Launcher3#466]
The open source license is missing, google says that if an app is redistributed and modified you need to keep the license and write the modifications you have made. Could you please do that?

**Comment by deletescape** [comment]
https://github.com/amirzaidi/Launcher3/blob/o-mr1/LICENSE

...

**Comment by amirzaidi** [comment]
He meant in the options menu, the real Pixel Launcher has an "open source licenses" section.

I just felt like it would be weird to keep their "open source licenses" in the app when I made this from decompiling their app (which is not something they would ever want you to do)
