### ISSUE TITLE
Can not swipe card away any longer

### ISSUE THREAD

**Issue by JostCrow** [amirzaidi/Launcher3#467]
Since version 3 I can no longer swipe the cards away any more. Should this still be possible or is it removed?

Android: 8.0.0
Launcher3: 3.4

**Comment by mincaeuro** [comment]
got the same problem
Android: 6.0.1
Launcher3: 3.4

**Comment by dbesoli** [comment]
this is duplicate of this https://github.com/amirzaidi/Launcher3/issues/371
and it's the normal behaviour for Google app
