### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [amirzaidi/Launcher3#468]
Hello I would like to contribute with a new icon and logo for your application I leave you the proposal if you want to use it I can send you all the files

![presentacion para github](https://user-images.githubusercontent.com/35604837/39030804-6217a2f6-4432-11e8-969a-f0c7055fc87e.png)

**Comment by amirzaidi** [comment]
It's cool that you have spent the time to make this, but I'm keeping the real Pixel Launcher icon for the real "Pixel Launcher experience"
