### ISSUE TITLE
Feature request: let the user choose to disable the google search bar

### ISSUE THREAD

**Issue by gabrielmulle** [amirzaidi/Launcher3#471]
### Problem Definition
Currently, there is no option to disable the google search bar.
There are some people who doesn't like and/or do not use that search bar.

### Suggested Solutions
It would be interesting to have an option in the settings to disable that, just like there are other options to disable other things (like at a glance, app suggestions, etc)

Thanks for this amazing app btw

**Comment by amirzaidi** [comment]
To make this possible at runtime would require far too many changes to the way the launcher works internally, the sizes are all hardcoded by Google.
