### ISSUE TITLE
Option to remove white gradient behind navbar

### ISSUE THREAD

**Issue by kistrand** [amirzaidi/Launcher3#473]
Hi, would it be possible to add the "remove white gradient" option for the navbar (and google search). It used to be there but not in version 3.4. Keep up the good work!

**Comment by amirzaidi** [comment]
It has never been there in my launcher and I won't add it, you can use a dark wallpaper to make it dark

**Comment by kistrand** [comment]
ok, fair enough. I remembered incorrectly then.
