### ISSUE TITLE
Weather widget not working - it is opening calendar instead (BUG)

### ISSUE THREAD

**Issue by gabrielmulle** [amirzaidi/Launcher3#476]
### Summary
The default widget at the top right corner is opening calendar instead of opening the weather.
[Screenshot](https://img.xda-cdn.com/QHgFF5VrbHCqmm75FXg4_ylN6Eo=/https%3A%2F%2Fcl.ly%2F3H052A1v3b2q%2FImage%25202018-04-13%2520at%252011.00.09%2520AM.png)

### Expected Results
When clicking it should open the weather app.

### Actual Results
When clicking, it is opening the calendar.

### Notes
- I'm using the version from 13 October 2017.
- I switched back to this old version because the new version is way heavier and slowed down my phone greatly.

**Comment by amirzaidi** [comment]
I won't provide anymore support for the old 7.1 and 8.0 versions, you can try the Android Go edition of the new launcher if you want something more lightweight.
