### ISSUE TITLE
Pixel Launcher stopped working message

### ISSUE THREAD

**Issue by TBM13** [amirzaidi/Launcher3#477]
In Samsung J2 (2015) (SM-J200M) (Android 5.1.1) appears a message that says Pixel Launcher stopped working, but the launcher works.

**Comment by TBM13** [comment]
I think that the Google App crash because i deactivated that option and the messages don't appear.
(Maybe it's because i use the BETA of the Google App)

**Comment by TBM13** [comment]
The stopped working message still appears but with less frequency.

**Comment by theqwertyipad** [comment]
@Truebamateo try installing a stable version of Google App (not the beta one), delete app data and cache :smile:

**Comment by TBM13** [comment]
Done, but the mesage still apears with or without the google panel option activated.

**Comment by TBM13** [comment]
I think the problem is of the Launcher

**Comment by amirzaidi** [comment]
Send me a logcat

**Comment by TBM13** [comment]
Sorry, how i do that?

**Comment by amirzaidi** [comment]
Reopen if you figured out how to get a logcat of the crash.
