### ISSUE TITLE
A feature about allowing users to control double click action was wanted

### ISSUE THREAD

**Issue by YanceyChiew** [amirzaidi/Launcher3#479]
Now once we users clicked at Launcher3 twice soonly, the screen lock would be triggered as default. 
But sometimes we are meanning to operate living wallpaper  or whatever other shit instead of to lock our screen, so I hope the Launcher3 app add a switch witch can disable double-click-lock-screen.

**Comment by amirzaidi** [comment]
There is no screen lock in the launcher and I will not add it
