### ISSUE TITLE
1.4 - Google now pane - failed to load cards

### ISSUE THREAD

**Issue by RWOne** [amirzaidi/Launcher3#48]
Nexus 6, stock 7.1.1, updated to v1.4, cleared cache and data on launcher for pixel icons, running fine, but now my feed pane has "failed to load cards". A problem occurred while loading cards.  

Cleared Google feed preferences and restarted, came back momentarily but then back.

Rebooted as well.

**Comment by amirzaidi** [comment]
Does it work in Google Now Launcher? Or Nova? The Google app itself?

**Comment by RWOne** [comment]
Ok, cleared Google app again, and back, with search shortcuts! Perhaps the app was getting changed server side giving me the load fails, don't know .....

All's well for now. Please close.
