### ISSUE TITLE
App icon change, Double tap home screen to screen lock

### ISSUE THREAD

**Issue by RameshGokamalla** [amirzaidi/Launcher3#480]
After applying an icon pack few icons remain to default system rounded icons as it is not packed (themed) in that icon pack. This is not looking good if we look at all icons in app drawer. I am requesting you to add a feature to change app icon manually from installed icon packs. And double tap on home screen to screen lock feature too..

**Comment by brutlern** [comment]
Yeah, KnockOn feature (LG phones) does not work to turn screen off (it works to turn screen on though).

**Comment by amirzaidi** [comment]
Copypaste from Telegram:

For people asking me why I am not implementing double tap to sleep, here is why.

First of all, live wallpapers let you play with them by tapping on them. The Pixel's Gooey wallpapers are fun to touch repeatedly. Mapping double tap to an action would break this functionality, and I'm not adding a toggle for it in the settings menu.

Even if I were to still continue with it and give up live wallpaper interaction, the next problem shows up: implementation. There are three ways to implement it, and not one of them is a good solution.

- Device admin lock
This is the easiest to implement, but disables biometrics like fingerprint scanning and face unlock.

- 5s black screen timeout
Many things can go wrong with this implementation. If you interact with the device during the 5 seconds after you double tap, your device might do random actions or not show any response at all. It can also ruin your screen timeout setting. Simply put, it's an unstable unpredictable method that will break in many ways.

- Root lock
This is a possibility but.. it doesn't feel right to implement it in "Rootless Pixel Launcher". I'll have to explain to people that my "Rootless" launcher requires root for all features.. I want to stay away from that one and keep feature parity as much as possible for everyone.

So, the best solution here is to simply not add double tap to sleep. If you desperately want an easier way to lock your phone and don't mind the compromises, you could use a Nova activity shortcut or something similar to lock the screen.

**Comment by brutlern** [comment]
I appreciate the reply and understand the issue. Thank you and keep up the amazing work you do.
