### ISSUE TITLE
Update 3.6

### ISSUE THREAD

**Issue by nirmal1998** [amirzaidi/Launcher3#482]
When will be the next update the last update was roughly a month before?

**Comment by alexan** [comment]
what feature is missing?

**Comment by nirmal1998** [comment]
Can add corner edge like pixel2xl ;)

**Comment by AngelBrSa** [comment]
Add an option to change color from dark, light or auto.

**Comment by Legacy2000** [comment]
Release the updated version

**Comment by Legacy2000** [comment]
Add an option to disable white gradient

**Comment by Molochay** [comment]
I'm still waiting for locking the phone with a double tap on the screen

**Comment by alexan** [comment]
are these features included in the official pixel launcher?

**Comment by Elegroth** [comment]
I'm personally just waiting on #498 which is already in the alphas.  No real features that I think are missing.

**Comment by thatchrismiller** [comment]
I'm using an LG G6. Just waiting for the app to run at 18:9, so there is not a black or white nav bar at the bottom of the home screen. I believe this is what #498 will fix.

**Comment by iamwilliamli** [comment]
Round corner added
