### ISSUE TITLE
Google feed's texts are missing

### ISSUE THREAD

**Issue by D-Merlin** [amirzaidi/Launcher3#484]
So today morning I opened the feed to face this issue where the texts of the cards were missing.just images.i tried restarting the launcher but nothing.
Cleared the cache restarted the phone but all in vain.
Help out!

**Comment by A930** [comment]
Same on my part, I believe the recent Google update changed something

**Comment by janbloemacher** [comment]
Yes same for me. Google version 8.3.7.21 broke the Google feed. Headlines and discriptions are missing

**Comment by gcladores** [comment]
Same here

**Comment by gcladores** [comment]
![screenshot_20180512-163414](https://user-images.githubusercontent.com/30974738/39955508-732d388a-5602-11e8-875d-4f5558f3e498.png)

**Comment by gcladores** [comment]
I think it's a Google App bug. Not the launchers fault. I checked the google app and there still no text
![screenshot_20180512-163648](https://user-images.githubusercontent.com/30974738/39955525-d5e93e06-5602-11e8-9706-c02620be10cc.png)

**Comment by janbloemacher** [comment]
Jus opt out of the Google beta program in the play store and it works again. They screwed up the newest beta somehow.

**Comment by lxieyang** [comment]
![screenshot_20180512-225324](https://user-images.githubusercontent.com/16089305/39963386-cc102414-5637-11e8-8ce9-ea1ebc147c80.jpg)

**Comment by amirzaidi** [comment]
Google server side issue, should be resolved
