### ISSUE TITLE
status bar gradient exposure for themes

### ISSUE THREAD

**Issue by bkr32** [amirzaidi/Launcher3#487]
Hi, great launcher, there's just a little issue thats been getting to me and thats the gradient in the status bar as shown in the screenshot, is it possible to expose it so themes can make it transparent?
thanks
![screenshot_20180515-191110__01](https://user-images.githubusercontent.com/7794407/40073046-6a6c9cf8-587e-11e8-9c76-cafadd165d98.jpg)

**Comment by jrmribeiro** [comment]
It looks to me that that's Android KitKat, I think the os itself governs the status bar, don't know if that's possible on a launcher to change

**Comment by bkr32** [comment]
@jrmribeiro android 8.0 or oos OB 27
doesn't occur on oneplus launcher so yes i believe it is possible

**Comment by amirzaidi** [comment]
I fixed this on the 3.5 dark theme

**Comment by bkr32** [comment]
Oddly can't find the dark mode toggle in 3.5 update 

![image](https://user-images.githubusercontent.com/7794407/40190637-11a804f0-5a08-11e8-80ef-cd75dc68cc1e.png)

**Comment by amirzaidi** [comment]
There is no toggle, it's set by default on dark wallpapers

**Comment by amirzaidi** [comment]
I forgot to mention, this is already a drawable that Substratum themes can override
