### ISSUE TITLE
Duplicated icons in the menu

### ISSUE THREAD

**Issue by MrMarmelade** [amirzaidi/Launcher3#489]
![screenshot_20180426-121030](https://user-images.githubusercontent.com/23004033/40189558-085e4b8a-59fd-11e8-902b-739ea96995da.png)

**Comment by ohsayan** [comment]
Yes that's happening to me as well

**Comment by dbesoli** [comment]
this is duplicated of this closed item: https://github.com/amirzaidi/Launcher3/issues/439
