### ISSUE TITLE
Google Feed Animation issue

### ISSUE THREAD

**Issue by niehaus1301** [amirzaidi/Launcher3#492]
Device: OnePlus 5T
OS: Official Android 8.1.0
Security updates: all Official
Google up to date
Launcher version: 3.5 AOSP

When I swipe to open the Google feed, I have this Animation issue. It occurs on my and my friends OnePlus 5T (never software update) https://photos.app.goo.gl/app4pZyob6N8sd2c9

But great work anyways! :)

**Comment by amirzaidi** [comment]
OnePlus bug that I can't fix unfortunately
