### ISSUE TITLE
LG G6 Oreo Navigation bar is not transparent

### ISSUE THREAD

**Issue by barti20112** [amirzaidi/Launcher3#498]

**Comment by monta990** [comment]
I have the same problem

**Comment by amirzaidi** [comment]
Fixed in alpha

**Comment by Elegroth** [comment]
Looks like this affects the LG V30 as well after the Oreo update.  I assume it's the same issue.

**Comment by Molochay** [comment]
I have same problem with lg g6 after installation 8.0 Oreo. Using 3.5 version
