### ISSUE TITLE
Can't install in 7.1.1

### ISSUE THREAD

**Issue by vishnudevk** [amirzaidi/Launcher3#5]

**Comment by amirzaidi** [comment]
Give me an adb logcat or I cannot help you. I've said before you have to delete Pixel Launcher before installing this.

**Comment by gargakshit** [comment]
When I install the apk, the phone says that the package seems to be corrupt

**Comment by faultysugar** [comment]
I uninstalled the Pixel launcher and this installed successfully.

**Comment by gargakshit** [comment]
Did this error appeared??? package seems to be corrupt. Running RR-N 3.8.3 on Yuphoria

**Comment by faultysugar** [comment]
Yes this file corrupt error did appear. After uninstalling the Pixel launcher, no more error.

**Comment by gargakshit** [comment]
Yes, it worked for me now...

**Comment by sergeysova** [comment]
Can't install on 7.1.2. APK is broken

**Comment by SethuSenthil** [comment]
It works perfectly, if you have pixel launcher or Google Now Launcher (installed separately, meaning it didn't come with those launchers already), you will need to uninstall them because the packages will interfere.

**Comment by sergeysova** [comment]
@SethuSenthil oh, thanks!
