### ISSUE TITLE
BUG - cannot install Rootless Pixel Launcher 2.1

### ISSUE THREAD

**Issue by gabrielmulle** [amirzaidi/Launcher3#500]
Message:
App not installed.
The package appears to be corrupt.

**Comment by theelog** [comment]
Have you already got another Pixel Launcher installed? I got a modded Pixel Launcher installed but needed to uninstall that first before I could install this one.

**Comment by gabrielmulle** [comment]
Thanks for the input, not sure but I think there's a more recent version installeed.
Will give this a try.
