### ISSUE TITLE
Questions about the google feed

### ISSUE THREAD

**Issue by gcladores** [amirzaidi/Launcher3#501]
![screenshot_20180525-180413](https://user-images.githubusercontent.com/30974738/40539054-25a6966c-6046-11e8-9efc-7d6f860d638c.png)

Howcome sometimes i have a google search bar at the top of my feed? And sometimes it doesn't show up?

**Comment by gcladores** [comment]
![screenshot_20180525-180728](https://user-images.githubusercontent.com/30974738/40539212-88949cec-6046-11e8-8fd4-9af4a3329768.png)

**Comment by AuRoyalty** [comment]
I've experienced the same thing, usually I have the search bar just after a reboot.

**Comment by amirzaidi** [comment]
Google A/B testing, I can't change it
