### ISSUE TITLE
Folder "+" button to add multiple apps at once

### ISSUE THREAD

**Issue by janbloemacher** [amirzaidi/Launcher3#504]
A lot of launchers have the feature that in a folder there is a button which you can click in order to add multiple apps at once.

I'd really appreciate it if this was possible

**Comment by amirzaidi** [comment]
Sorry but I probably won't add this as I would have to add a lot of additional logic and UI for it

**Comment by GeekyBoyHT** [comment]
Please we want productivity in this launcher
