### ISSUE TITLE
pixel launcher crash on HuaWei P20 Pro(EMUI 8.1) when it start

### ISSUE THREAD

**Issue by zoms** [amirzaidi/Launcher3#511]
Phone Model: HuaWei P20 Pro（CLT-AL00）
EMUI version: 8.1.0
Android version: 8.1.0
pixel launcher version:3.0-3.5
when I change default launcher to pixel launcher after install, it just crash and still default launcher. I've tried version 3.0-3.5, same error.the only version can run on P20 Pro is V2.1

**Comment by amirzaidi** [comment]
Grant all permissions to the app manually

**Comment by sascha224** [comment]
Same error on OnePlus 5T (Stock ROM, unrooted). Last recent build from telegram chat works without crashing. Same problem on forked projects like "Lean Launcher" or "Ruthless" since yesterday... a problem with an updated Google Framework?

**Comment by MaYiFei1995** [comment]
- 我是mate10，emui和android版本和你的一样，从google play上下载的，权限默认是都不允许，启动后崩溃。在应用设置里面选择了信任此应用后，能正常使用了，希望能帮到你。

 - My device is Huawei Mate10,  EMUI & Android version is same to yours. I got this application from google play. It crash when i select it to be my default launcher. Then i check permissions in SETTINGS, and found   no permission allowed! Finally, i choose 'trust this application' item and it works perfect. I hope this help.
