### ISSUE TITLE
LG V35 double tap home screen for screen off

### ISSUE THREAD

**Issue by tapr00t** [amirzaidi/Launcher3#518]
On the V35, the power button is on the back of the phone, making it inconvenient to turn off the screen when the phone is laying flat.  The solution in the LG launcher is to allow double tapping on empty space in the home screen to turn the screen off.  The pixel launcher only allows double tapping on the notification bar to do this.  Could you add a toggle in the options to turn on this behavior for any empty space on the home screen?

**Comment by amirzaidi** [comment]
- I won't add any toggle
- I wrote a post about this on Telegram:

For people asking me why I am not implementing double tap to sleep, here is why.

First of all, live wallpapers let you play with them by tapping on them. The Pixel's Gooey wallpapers are fun to touch repeatedly. Mapping double tap to an action would break this functionality, and I'm not adding a toggle for it in the settings menu.

Even if I were to still continue with it and give up live wallpaper interaction, the next problem shows up: implementation. There are three ways to implement it, and not one of them is a good solution.

- Device admin lock
This is the easiest to implement, but disables biometrics like fingerprint scanning and face unlock.

- 5s black screen timeout
Many things can go wrong with this implementation. If you interact with the device during the 5 seconds after you double tap, your device might do random actions or not show any response at all. It can also ruin your screen timeout setting. Simply put, it's an unstable unpredictable method that will break in many ways.

- Root lock
This is a possibility but.. it doesn't feel right to implement it in "Rootless Pixel Launcher". I'll have to explain to people that my "Rootless" launcher requires root for all features.. I want to stay away from that one and keep feature parity as much as possible for everyone.

So, the best solution here is to simply not add double tap to sleep. If you desperately want an easier way to lock your phone and don't mind the compromises, you could use a Nova activity shortcut or something similar to lock the screen.

**Comment by tapr00t** [comment]
Thanks for the detailed response.
