### ISSUE TITLE
Add photo as icon Option

### ISSUE THREAD

**Issue by fsponlineht** [amirzaidi/Launcher3#519]
Hi I think I have a idea that will make this launcher top launcher ever. My suggestion is that please add a option that can allow us to set an image as the icon of any app. I know working on this is hard but it is possible so please add this feature as fast as you can.

THANKS

**Comment by amirzaidi** [comment]
Yes and I have heard this "idea" a thousand times by now, but there is a very low chance of me implementing this so don't hold your breath.

**Comment by GeekyBoyHT** [comment]
Please make it happen that thousand people want this from you.
