### ISSUE TITLE
Use android O pixel launcher as base

### ISSUE THREAD

**Issue by madvinegar** [amirzaidi/Launcher3#52]
You could base your launcher on "android O" pixel launcher.
Preview 3 seems quite stable and probably the long-press actions and notification badges will work.

**Comment by amirzaidi** [comment]
They base it on top of the O Launcher3 whose source code hasn't been released yet. That means I have to port the entire app and fix a lot of obfuscation problems, something that will require far too much time. As soon as O officially releases and Launcher3 gets updated I will make an O version
