### ISSUE TITLE
Please join app search bar (on and off) and google search bar (on and off), thank you!

### ISSUE THREAD

**Issue by shui288** [amirzaidi/Launcher3#520]
Please join app search bar (on and off) and google search bar (on and off), thank you!

**Comment by amirzaidi** [comment]
Could you explain what you mean? You want to hide the desktop search bar when the Google App is disabled?

**Comment by shui288** [comment]
> 
![screenshot_20180712-193907](https://user-images.githubusercontent.com/21996944/42725463-4c9a38e4-8749-11e8-86d4-7f523c617ca9.png)一

**Comment by shui288** [comment]
> 
![1531582584640](https://user-images.githubusercontent.com/21996944/42725966-7d6a6184-8752-11e8-8125-5a6dc0e038b1.png)
![1531582641483](https://user-images.githubusercontent.com/21996944/42725967-7dd6dff8-8752-11e8-8c88-7d94fd5ee973.png)

Please  add  three  
thanks

**Comment by amirzaidi** [comment]
I'm not adding more options.
