### ISSUE TITLE
Icon settings disabled

### ISSUE THREAD

**Issue by GeekyBoyHT** [amirzaidi/Launcher3#531]
Some times in this launcher when i try to change icon, this option is disabled. Please fix this issue.

**Comment by GeekyBoyHT** [comment]
here is the Screenshot of this - 
![screenshot_2018-07-28-18-44-36](https://user-images.githubusercontent.com/37154299/43356958-603b8dcc-9297-11e8-859e-8808d4246e6b.png)

Persentage of error - 80%

**Comment by amirzaidi** [comment]
Not an issue - this means the icon pack didn't specify any icon for that app. There is no manual icon picking.

**Comment by rishib2514** [comment]
Is there any hope for manual icon picking?
Great work btw
I prefer this over Action and Nova launcher
Just because of it's fluid ui and has icon pack support

**Comment by GeekyBoyHT** [comment]
There is that app icon available in the icon pack. Please do something.
