### ISSUE TITLE
Dark theme gets applied even when the wallpaper is not dark enough

### ISSUE THREAD

**Issue by anjocerdena** [amirzaidi/Launcher3#535]
Since version 3.6, the threshold for applying the dark theme seems to have been lowered. Now, instead of getting the default theme on a neutral wallpaper, I still get dark folders, feed, search bar, and app drawer.

Screenshots of no-so-dark wallpapers getting the dark theme: https://imgur.com/a/YQdcUpi

**Comment by amirzaidi** [comment]
Can you try rebooting your phone and then applying the wallpaper again? Are you sure you did not select the dark theme in the settings?

**Comment by pabloppp** [comment]
I am facing the same issue

**Comment by amirzaidi** [comment]
Do you have the theme set to "Automatic"? Does manually overriding it with "Default" work?

**Comment by anjocerdena** [comment]
Yes, the theme is set to automatic (I tried the dark theme once, but set it back to automatic since). Indeed, manually setting it to default works as expected.

I've tried rebooting. BTW, I use the wallpaper app Walpy to automatically change wallpapers for me. Before the update, automatic theming worked just fine with that.

**Comment by amirzaidi** [comment]
Can you roll back to 3.5 and double check if that fixes it? You can change between versions without deleting the other one

**Comment by anjocerdena** [comment]
Yep, automatic works correctly when I rolled back to 3.5 just now. On 3.6, my current wallpaper got a dark theme. On 3.5, it's on the default theme as expected.

**Comment by amirzaidi** [comment]
Which phone and which Android version is this?

**Comment by anjocerdena** [comment]
I'm using a Nokia 7 plus on Android 8.1.0 with a July 1 security patch.

**Comment by amirzaidi** [comment]
Did you guys enable the dark theme in the settings of your phone?

**Comment by infinitytec** [comment]
Is there a toggle?

**Comment by rishib2514** [comment]
Yupp

**Comment by anjocerdena** [comment]
No, my phone does not have a dark theme under Settings.

**Comment by infinitytec** [comment]
None for me either.

**Comment by amirzaidi** [comment]
This is a really strange issue because it should take the system's theme at all times on 8.1.. I don't have a 8.1 or 9.0 device (only 8.0) to test this myself so I'd need someone else to check what is happening here :(

**Comment by amirzaidi** [comment]
It has been a while since 3.6 but can you guys check every build between 3.5 and 3.6 on Telegram in @appforks and see which build caused it to break?

**Comment by amirzaidi** [comment]
Actually I think I just figured out the problem, try this build:
https://my.mixtape.moe/wlfkgr.apk

**Comment by amirzaidi** [comment]
Fixed in new release.
