### ISSUE TITLE
Split Screen Mode

### ISSUE THREAD

**Issue by Yash8446** [amirzaidi/Launcher3#536]
Add support for split screen mode

**Comment by DanGLVK** [comment]
Its not possible,android does not allow a launcher to run in multiwindow/split screen,also why run a launcher in multiwindow/split screen?

**Comment by Yash8446** [comment]
I am using honor 7x. The screenshot using honor launcher is as follows

I am suggesting to impliment like this

https://drive.google.com/file/d/0BwqfQQ_lrlxWWVBkZUsyMmZ4Qm5EeDVvYTdBb3Q5RUhWQTM0/view?usp=drivesdk

**Comment by Yash8446** [comment]
I have one more suggestion. I am using Microsoft launcher. See the icons in
the launcher & also the background wallpaper blur.


Kindly implement the same in ur launcher.
