### ISSUE TITLE
Immediately crashes on 5.0

### ISSUE THREAD

**Issue by vojta-horanek** [amirzaidi/Launcher3#54]
The launcher crashes on start-up. (v.1.4)

**Comment by amirzaidi** [comment]
1. Test 1.0
2. Send me a logcat from the crash

**Comment by vojta-horanek** [comment]
1. 1.0 works
2. I'll send you as soon as I get home

**Comment by vojta-horanek** [comment]
I was able to return the log now, hopefully it's this error. I did it with some app. Tell me if there are any problems

Log:
6-16 14:40:25.406 D/Atlas (20692): Validating map... 06-16 14:40:25.409 W/WindowManager(848): Attempted to add application window with unknown token Token{34ba72c ActivityRecord{3291fedf u0 com.google.android.apps.nexuslauncher/com.android.launcher3.Launcher t1784 f}}. Aborting. 06-16 14:40:25.410 D/AndroidRuntime(20692): Shutting down VM 06-16 14:40:25.515 I/ActivityManager(848): Start proc com.google.android.gms.feedback for service com.google.android.gms/.feedback.FeedbackService: pid=20936 uid=10070 gids={50070, 9997, 2001, 3003, 1007, 3006, 1028, 1015, 3002, 3001, 1005, 3007} abi=armeabi-v7a 06-16 14:40:25.517 I/ActivityManager(848): Process com.qualcomm.qcrilmsgtunnel (pid 20137) has died 06-16 14:40:25.518 W/ActivityManager(848): Scheduling restart of crashed service com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService in 73484ms 06-16 14:40:25.530 E/AndroidRuntime(20692): FATAL EXCEPTION: main 06-16 14:40:25.530 E/AndroidRuntime(20692): Process: com.google.android.googlequicksearchbox:search, PID: 20692 06-16 14:40:25.530 E/AndroidRuntime(20692): android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@f1783b6 is not valid; is your activity running? 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:562) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:272) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at com.google.android.libraries.gsa.e.a.n.handleMessage(SourceFile:58) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at android.os.Handler.dispatchMessage(Handler.java:98) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at android.os.Looper.loop(Looper.java:135) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at android.app.ActivityThread.main(ActivityThread.java:5219) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at java.lang.reflect.Method.invoke(Native Method) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at java.lang.reflect.Method.invoke(Method.java:372) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898) 06-16 14:40:25.530 E/AndroidRuntime(20692): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 06-16 14:40:25.532 W/ActivityManager(848): mShowDialogs: false 06-16 14:40:25.532 I/Process (20692): Sending signal. PID: 20692 SIG: 9 06-16 14:40:25.548 D/WifiService(848): Client connection lost with reason: 4 06-16 14:40:25.550 I/ActivityManager(848): Process com.google.android.googlequicksearchbox:search (pid 20692) has died 06-16 14:40:25.551 W/ActivityManager(848): Service crashed 2 times, stopping: ServiceRecord{24819032 u0 com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.BroadcastListenerService} 06-16 14:40:25.589 W/ResourcesManager(20936): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources. 06-16 14:40:25.589 W/ResourcesManager(20936): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.

**Comment by amirzaidi** [comment]
What about the fallback 1.3 version, could you check if that one works? The one without app suggestions. I believe it might be related to the obfuscated code I pulled in for the app suggestions

**Comment by vojta-horanek** [comment]
Yup fallback 1.3 works fine

**Comment by amirzaidi** [comment]
> FATAL EXCEPTION: main 06-16 14:40:25.530 E/AndroidRuntime(20692): Process: com.google.android.googlequicksearchbox:search

Weird that the Google Search crashes instead of the Launcher.. what about 1.5? I have a feeling it might be related to the new Google Now version request somehow

**Comment by vojta-horanek** [comment]
Only the fallback 1.5 works
