### ISSUE TITLE
能不能增加隐藏app的功能

### ISSUE THREAD

**Issue by wupeng1211** [amirzaidi/Launcher3#541]

**Comment by mlleemiles** [comment]
It's already been added. Hold down app icon in app drawer and click on the edit button to reveal hide app option.

**Comment by wupeng1211** [comment]
@ @mlleemiles no  edit button  
![default](https://user-images.githubusercontent.com/6904999/43937869-f01ea686-9c92-11e8-9a4c-e60b934f3df0.png)
![_20180810114650](https://user-images.githubusercontent.com/6904999/43937892-1d6f98b6-9c93-11e8-91e8-5c16ad06fe4c.jpg)

**Comment by mlleemiles** [comment]
https://github.com/amirzaidi/Launcher3/releases

Download the latest release

**Comment by thatchrismiller** [comment]
I am using 3.7 and I'm not seeing any edit button either.

**Comment by wupeng1211** [comment]
3.7

**Comment by mlleemiles** [comment]
That's weird. I suggest rolling back to and older version first. Only the dev knows what's up.

**Comment by amirzaidi** [comment]
Use an icon pack first. I now agree it's weird behaviour but it's been a "feature" since 3.2 for various reasons. If you don't like any icon pack try my GoogleIcons

**Comment by wupeng1211** [comment]
要想安装 icon pack，谢谢大家
