### ISSUE TITLE
Feature request: double tap on home screen to lock

### ISSUE THREAD

**Issue by Sov3rain** [amirzaidi/Launcher3#545]
Oneplus did it with their custom launcher. When on your home screen, double taping on a empty space locks the phone and shut down the screen.

**Comment by TheAgamer554** [comment]
the way of blocking the screen requires either using amoled black pixels or disabling fingerprint and smart lock among other things (unless you have root)

**Comment by amirzaidi** [comment]
OnePlus's way is proprietary and doesn't work on other phones

**Comment by dpkg** [comment]
CyanogenMod/Lineage ports for the OnePlus One has this feature. Is it from their (OPO's) base image?

**Comment by vascanera** [comment]
1 year later, is there still no way of adding this to Rootless Pixel Launcher?
