### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by RikKoedoot** [amirzaidi/Launcher3#56]
To be sure, are the round icons only on 7.1? I have 7 and don't have them

**Comment by amirzaidi** [comment]
Update to 1.4 and clear app data. Now check Google Maps, Keep, Play Store etc. They should be round

**Comment by nikbra** [comment]
Hi I have 7.1 on Nexus 6p and version 1.4. But for example Keep ar not a round icon. Not Google maps either. And I have cleared cache in  (Storage --> Clear Cached Data).
Should I do something else ?

**Comment by amirzaidi** [comment]
Go to the Launcher3 in your apps list and clear its data

**Comment by nikbra** [comment]
@amirzaidi , thanks ! Worked
