### ISSUE TITLE
Research - swipe down for notifications?

### ISSUE THREAD

**Issue by RWOne** [amirzaidi/Launcher3#57]
Amir,

Couldn't find the thread on this, in a future release can swipe down for notifications be implemented?

It's a stock PL function, but wasn't sure if it could be ported what with swipe up for the drawer.

More of a question, not a request 😊

**Comment by amirzaidi** [comment]
Really? In what version did they add this to the Pixel Launcher?

**Comment by RWOne** [comment]
OMG, I need coffee... Sorry. Confusing it with fingerprint sensor swipe down.....

😯
