### ISSUE TITLE
Cannot change linked calendar app

### ISSUE THREAD

**Issue by Quiptix** [amirzaidi/Launcher3#572]
When I clicked on the date on Home screen, the launcher let me choose which calendar app to open. I want to change it, however I cannot find where / how to do it.

Issue?

Vincent

**Comment by DanGLVK** [comment]
clear you calendar app defaults,settings,apps,calendar,open by default or default

**Comment by Quiptix** [comment]
Thanks... You need to reset the wrongly linked app! But now it works!

Vincent van Wichen


Op ma 27 aug. 2018 om 14:04 schreef switchtegrax1 <notifications@github.com
