### ISSUE TITLE
google feed stops working after screen lock on 3.8.3 on EMUI

### ISSUE THREAD

**Issue by pdanpdan** [amirzaidi/Launcher3#575]
Hello.

After update to 3.8.3 Google feed works after starting the launcher or after reinstalling the bridge, but stops working after screen lock. Huawei p10 plus with emui 8, but it was working fine with 3.8.1 (except scroll to top)

**Comment by amirzaidi** [comment]
Whitelist the Bridge in your background app management, EMUI is killing it. I fixed a bug that made it always reload when you went back to the homescreen, but that "broke" it on EMUI.

**Comment by pdanpdan** [comment]
It's working as expected, thank you very much.
