### ISSUE TITLE
EMUI - Wallpaper management requires storage permissions to prevent crash

### ISSUE THREAD

**Issue by sakshatshinde** [amirzaidi/Launcher3#579]
When you try to use it, the smart recovery dialogue box pops up and says pixel launcher put your phone into a unstable blah blah and now it is recovered prompting us to uninstall the app. My device : Huawei Honor Play

**Comment by amirzaidi** [comment]
Needs manual storage permission or else Huawei's wallpaper manager crashes

**Comment by sakshatshinde** [comment]
I saw your reply on the play store comment of mine, sorry forgot to update this thread!
