### ISSUE TITLE
Where are download link?

### ISSUE THREAD

**Issue by diegomello-se** [amirzaidi/Launcher3#586]
Where are download link version 3.8.3?

**Comment by mlleemiles** [comment]
https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v3.8.3

**Comment by occidentalmachine** [comment]
On this page: https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v3.8.3
Click "Assets"
Then download .apk you're looking for.
