### ISSUE TITLE
Transparent theme is like Dark theme

### ISSUE THREAD

**Issue by TaWa82** [amirzaidi/Launcher3#609]
Hi
Themes available are automatic, predefined, light, dark and transparent. In my case between dark and transparent there's no difference. Both are dark. 
Oreo 8.1.0 - Nexus 6p

thanks in advance for help and courtesy

**Comment by zackaryry** [comment]
In one of his Reddit posts or somewhere it's clarified dark and transparent are very similar (as in the same dark scheme overall) but transparent allows you to see more of the wallpaper in the app drawer.

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/blob/o-mr1/res/values/styles.xml#L89

As you can see, transparent is just dark with the transparency maxed out and the status bar haze removed.
