### ISSUE TITLE
Is there any way to set the grid size regardless the LauncherConfig.apk? 

### ISSUE THREAD

**Issue by victormunduruca** [amirzaidi/Launcher3#61]
This issue is about the fixed 4 collummns grid layout, on Motorola devices, even though the dpi is enough to fit more icons. I was told it was because those launchers get the info from a certain "LauncherConfig.apk". Is there a way to depend only on the dpi? Thanks in advance

**Comment by amirzaidi** [comment]
Could you extract and send me the LauncherConfig apk using adb?

**Comment by RikKoedoot** [comment]
I also have a moto, does the APK differ between devices?

**Comment by amirzaidi** [comment]
Well if it also causes the 4 columns bug please send it to me

**Comment by victormunduruca** [comment]
Ok, where do I send it to you?

**Comment by victormunduruca** [comment]
Sent to azaidi@live.nl!

**Comment by dpavani** [comment]
@rickkode I believe it differs from device to device..  I saw on XDA forum for the Z2 Play, for this new device Motorola is using 5x5 grid. Maybe finally they got how bizarre is to have 4x4 grid on such big screens.

**Comment by amirzaidi** [comment]
I fixed it in a test build, will come to 1.5

**Comment by victormunduruca** [comment]
Great!

**Comment by victormunduruca** [comment]
Do you want me to test it?

**Comment by karthikmohan** [comment]
You can change the grid by altering the display size in the display setting page. I've posted the screenshots of what I've done. 
Link: https://github.com/amirzaidi/Launcher3/issues/24#issuecomment-309254009

**Comment by dpavani** [comment]
Yes, it's working perfectly

**Comment by victormunduruca** [comment]
@roguenemesis I've tested this before, on 7.0 and it didn't work even on real high dpi!

**Comment by victormunduruca** [comment]
Here it is, on 600 dpi, it is fixed. (I also tested other dpi settings, no satisfatory results)
![screenshot_20170618-154930](https://user-images.githubusercontent.com/17774103/27263699-3ed90880-5445-11e7-80e8-ea7b35188963.png)

**Comment by victormunduruca** [comment]
@amirzaidi It's working! thank you a lot!
