### ISSUE TITLE
Google Assistant panel is overlapped

### ISSUE THREAD

**Issue by ngdinhtoan** [amirzaidi/Launcher3#612]
Sometimes this issue happens, not always.

![screenshot_20181010-124704](https://user-images.githubusercontent.com/1740801/46716988-37e65900-cc90-11e8-9bad-f77fe3949832.png)

**Comment by amirzaidi** [comment]
Seems to be a bug with Google Assistant as I have had this happen on the real Pixel Launcher.

**Comment by ngdinhtoan** [comment]
So... I think I should close issue!
