### ISSUE TITLE
"Close all" button in Recent apps screen overlapping the recent app cards

### ISSUE THREAD

**Issue by eggsgent** [amirzaidi/Launcher3#620]
Environment: Samsung S9 G960F, Android 9 beta build

1. Open a few apps, then press the Recent apps button to see the Recent apps screen
2. Inspect the placement and look of the "Close all" button
![samsung experience home - close all button in wrong place and hard to see]

Actual result: "Close all" button in Recent apps screen overlapping the recent app cards
Expected result: "Close all" button should be easily visible and preferably under the app cards

(https://user-images.githubusercontent.com/7951056/48627025-c9459b00-e9b3-11e8-8c61-a31d6ead189c.png)

**Comment by suphon-t** [comment]
This doesn't have anything to do with the launcher. You should report it to Samsung instead.

**Comment by eggsgent** [comment]
> 
> 
> This doesn't have anything to do with the launcher. You should report it to Samsung instead.

It has something to do with the launcher, as it doesn't happen with Samsung's launcher, but this one, so reporting here first.

**Comment by eggsgent** [comment]
Fixed in beta 2 of Android 9 on Samsung S9.
