### ISSUE TITLE
Launcher crashing on Honor Play

### ISSUE THREAD

**Issue by pawangond** [amirzaidi/Launcher3#624]
After installing and setting it as default launcher it is crashing. And only message I get is system recovered from crash caused by Launcher. And automatically stock launcher is set as default launcher.
Device : Honor Play ( COR AL00)

**Comment by pawangond** [comment]
#Closed
Manually give permissions before setting it as default fixed the problem

https://github.com/amirzaidi/Launcher3/issues/579

**Comment by k245sem** [comment]
Yup, ik
