### ISSUE TITLE
"App isn't installed" when tapping on at-a-glance weather

### ISSUE THREAD

**Issue by josh2112** [amirzaidi/Launcher3#635]
Starting yesterday morning, when I tap on the weather portion of the at-a-glance widget I get a toast saying "app isn't installed". I can still access weather from a shortcut or the Google Now panel.

Things I have tried:
 - Reboot
 - Clear Rootless Pixel Launcher app cache
 - Uninstall and reinstall both launcher and bridge

My device: Samsung Galaxy 9+

I've been running Rootless Pixel launcher since I got the device (and ran it on my prior phone as well) and have never had this issue.

Any thoughts?

**Comment by Carbon-Zero** [comment]
What version of Google podcasts are you using?

**Comment by suphon-t** [comment]
@Carbon-Zero Please stop asking unrelated questions.

**Comment by josh2112** [comment]
@Carbon-Zero I don't use Google Podcasts nor do I see how that is relevant to a question about Launcher3 and Google Weather.  And based on your contributions to other issues in Launcher3 neither does anyone else.

**Comment by Carbon-Zero** [comment]
What about Google Jamboard?

**Comment by FlorianSW** [comment]
I've the same behaviour. Before the Google App with the pre-filled phrase "Weather" opened, which was a really handy feature.

**Comment by harrydrewer** [comment]
I am having this same issue. Nothing I have done has seemed to fix it. It has been happening to me for more than a week now.

**Comment by vcfvct** [comment]
Same here. Any solutions? ❓Also tried the CPL launcher which seems to have the same error. 
Have to place a weather widget on the desktop for now.

**Comment by Carbon-Zero** [comment]
What version of Google Podcasts are you using?

**Comment by ghost** [comment]
@josh2112 unistall all updates of Google now like described in this post: https://www.reddit.com/r/GooglePixel/comments/86ptep/where_did_my_weather_thing_on_my_home_screen_go/?utm_source=reddit-android

**Comment by josh2112** [comment]
> @josh2112 unistall all updates of Google now like described in this post: https://www.reddit.com/r/GooglePixel/comments/86ptep/where_did_my_weather_thing_on_my_home_screen_go/?utm_source=reddit-android

Thanks!  This plus a reboot worked. Steps:

1) Settings -> Apps -> find the "Google" app
2) Click the three dots in the upper-right corner and select "Uninstall updates"
3) Reboot

My only reservation is I wonder what current or future features I'm giving up by not having an updated Google Now app...

EDIT: This worked at first, then broke again a day later.

**Comment by sschlosnagle** [comment]
This is a known issue and is not unique to "Rootless Pixel Launcher".

If you install the Google "At a Glance" widget you will get the same error.

amirzaidi is aware of the issue and has said that he is working on a "fix":
https://github.com/amirzaidi/Launcher3/issues/632#issuecomment-482106597

**Comment by amirzaidi** [comment]
Try the new update.

**Comment by pedrosalgueiro** [comment]
> Try the new update.

Working great with the new version of Launcher and Bridge!
Thank you!!!

**Comment by perceival** [comment]
Unfortunately for me it's still the same.
Android 8
Google 9.88.5.21.arm64

**Comment by josh2112** [comment]
It works beautifully @amirzaidi ! Quick links:

Launcher:  https://github.com/amirzaidi/Launcher3/releases/latest
Bridge:  https://github.com/amirzaidi/AIDLBridge/releases/latest

Of course uninstall the existing launcher first if you've installed it from the store.
