### ISSUE TITLE
Weather isn't clickable anymore

### ISSUE THREAD

**Issue by perceival** [amirzaidi/Launcher3#636]
Since some time, although touching the date is invoking calendar, the same stopped to work for weather widget.
LG V30.

**Comment by perceival** [comment]
Already there

**Comment by Carbon-Zero** [comment]
What version of Google Podcasts are.you using?

**Comment by ghost** [comment]
@perceival try to remove all updates from Google app and reinstall them again like here: https://github.com/amirzaidi/Launcher3/issues/632#issuecomment-492338704
