### ISSUE TITLE
About drawer, works anywhere on the screen when I swipe.

### ISSUE THREAD

**Issue by hemansah** [amirzaidi/Launcher3#64]
Opening drawer by swiping up works anywhere on the screen, this makes the widget dead or not working, I tried the news & weather app in which I can't scroll the news feed, if I do it opens the drawer. Fix it please.
Thankyou for making this​ launcher.

**Comment by RikKoedoot** [comment]
I don't have this problem in 1.4, maybe you've downloaded 1.0 or 1.1

**Comment by hemansah** [comment]
Would you please​ give me the link of new version?

**Comment by ghost** [comment]
https://github.com/amirzaidi/Launcher3/releases

**Comment by hemansah** [comment]
I have downloaded that version 1.4 but it is showing 1.0 in details. Why?

**Comment by RikKoedoot** [comment]
because then it is easier to downgrade and look for bugs.

**Comment by amirzaidi** [comment]
If 1.4 is working fine for you please close the issue

**Comment by hemansah** [comment]
Sure... It's working fine now... Superb😉

On Jun 17, 2017 23:47, "Amir Zaidi" <notifications@github.com> wrote:

If 1.4 is working fine for you please close the issue

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amirzaidi/Launcher3/issues/64#issuecomment-309231363>,
or mute the thread

**Comment by hemansah** [comment]
Hello Sir, I want to say you something... May I ?
