### ISSUE TITLE
Google news pane not working

### ISSUE THREAD

**Issue by gavinremme** [amirzaidi/Launcher3#641]
![Screenshot_20190529-223947](https://user-images.githubusercontent.com/9905137/58608959-15c33a80-8263-11e9-8f43-21b2d575e0ce.jpg)
Having this issue on my OnePlus 5, and is causing the leftmost news pane to not show up.

**Comment by mudzaffarm** [comment]
can try install from here https://github.com/amirzaidi/AIDLBridge/releases/tag/v3
