### ISSUE TITLE
App pernissions

### ISSUE THREAD

**Issue by RikKoedoot** [amirzaidi/Launcher3#66]
Why are these app permissions needed?
![screenshot_20170618-134059](https://user-images.githubusercontent.com/29402532/27260411-f03935c4-542b-11e7-8942-af26fc6e75d1.png)

**Comment by amirzaidi** [comment]
These are the default permissions from Launcher3, I didn't change anything. You could leave them off and if you encounter issues I'll see what I can do

**Comment by RikKoedoot** [comment]
Oh okay, didn't know that

**Comment by dpavani** [comment]
I know that the location is needed to the weather info, right?

**Comment by amirzaidi** [comment]
I have it disabled and the weather still works.

**Comment by RikKoedoot** [comment]
Weather is done by Google app right?

**Comment by dpavani** [comment]
Yes, I tried it also. I just mentioned it because when I was using LOS, if I installed Pixel Launcher and did not set the permissions to location, I could not get the weather.
But maybe this is related to LOS then.
