### ISSUE TITLE
Swipe down to notification gesture.

### ISSUE THREAD

**Issue by cyberon** [amirzaidi/Launcher3#67]
A few months ago someone found on a teardown that Google was going to implement swipe down to notification gesture (Android Police), i know you are trying to fix bugs atm, but it's a really useful feature to implement. Thanks in advance.

**Comment by amirzaidi** [comment]
If they implement it so will I. I don't feel like the current implementation feels smooth enough so I'm not adding it until Google proves they can add it without it feeling weird.

**Comment by amirzaidi** [comment]
Added
