### ISSUE TITLE
Option to disable search bar

### ISSUE THREAD

**Issue by hydrargyrum** [amirzaidi/Launcher3#687]
I never use the search bar and neither in other launchers, so it consumes expensive screen real estate for nothing on my phone. Is there an option to disable it completely?

**Comment by ghost** [comment]
As stated in #626 there will never be an option to disable the search bar unless google adds it to their launcher. For the time being you can use one of the below apks that removes the search bar from the homescreen.

[Android Go](https://github.com/ngdinhtoan/Launcher3/releases/download/Pixel-v3.9-nosearchbar/Launcher3-l3go-optimized.apk)
[Android](https://github.com/Recaust/Launcher3/releases/download/Pixel-v3.9.1/Launcher3-aosp-optimized.3.9.1.WTD.apk)

Hope this is what you are looking for!

**Comment by hydrargyrum** [comment]
This ticket being a duplicate and a WONTDO, I'll close it, ok. Thanks for the (unfortunately sad) info, I now know I shall just move on.

However, I don't trust random APK files from uncurated sites, I don't want to install malware or underhanded cryptominers.
