### ISSUE TITLE
Icon lock

### ISSUE THREAD

**Issue by bharatb76** [amirzaidi/Launcher3#69]
Is there a way you could let the Desktop icons be locked so that it won't move when we accidentally swipe it away ?!! Been using the launcher in SGS7 edge for a few days and it is excellent. Thanks for fix on Knox fix. Would help if the Desktop icons be locked and also a way to apply theme.

Thanks.

**Comment by RikKoedoot** [comment]
He wants to keep it as stock as possible, so no themes, if you want icon
packs, try lawnchair

**Comment by bharatb76** [comment]
Ok. What about locking icons ? That is a fair ask !

**Comment by RikKoedoot** [comment]
That also isn't in pixel launcher, but amir is the one who does that, so I
can't say for sure

**Comment by amirzaidi** [comment]
@rickkode is right, I don't want to include anything not in the Pixel Launcher. This is not  "Amir launcher with a Pixel look", this is supposed to be "Rootless Pixel Launcher" and that's what I'm sticking with

**Comment by bharatb76** [comment]
Fair enough
