### ISSUE TITLE
App drawer issue on MIUI 8.2

### ISSUE THREAD

**Issue by bappa555** [amirzaidi/Launcher3#7]
Tried the app on MIUI 8.2, there is no app shown on app drawer. Everything else seems to working fine.

**Comment by amirzaidi** [comment]
Do you use something like multiuser or a secure extra workspace? If yes, could you try disabling it? I'll have fixes for multiuser support in 1.3. If it still doesn't work send me a full logcat

**Comment by bappa555** [comment]
Hi,
I'm not using multiuser or any extra workspace. How do I send you logcat?

**Comment by amirzaidi** [comment]
https://www.reddit.com/r/Android/comments/6gn8f9/rootless_pixel_launcher_port/dirlq9m/

**Comment by bappa555** [comment]
[ADB LOGCAT.txt](https://github.com/amirzaidi/Launcher3/files/1071518/ADB.LOGCAT.txt)
Hi, PFA loglac file.

**Comment by Harshit2k1** [comment]
Yes same problem with me...plz fix it...otherwise the launcher is good....but cant access apps other than 4 or 5 pre drawn apps

**Comment by amirzaidi** [comment]
It seems that MIUI is denying a few of the permissions for the app but I don't have a Xiaomi device to test it myself, could you guys check if there is any permissions that you can give it?

**Comment by akashmakesdesigns** [comment]
There is only 2 permissions one is show on lock screen and another is start in background both of 'em checked still facing the problem!

**Comment by bappa555** [comment]
Please find the attached list of permission which is already allowed .

**Comment by amirzaidi** [comment]
I believe I've found the issue, let me know when 1.3 drops later today if it works okay?

**Comment by hrithikb** [comment]
Getting same issue, we'll wait for v1.3, also a feature request, circle icon pack if possible.

**Comment by bappa555** [comment]
Issue is solved in 1.3. Thanks. Great job.
