### ISSUE TITLE
Hide Icons from App Drawer

### ISSUE THREAD

**Issue by haderz98** [amirzaidi/Launcher3#72]
Hi, would it be possible to add an option to toggle which apps are visible in the app drawer similar to the hide feature on Nova Launcher. This is just an idea as this launcher is designed to be a rootless port of the pixel launcher and therefore its users may not have root and not able to remove certain bloatware and system apps. Adding this feature would allow people to simply hide the horrible manufacturer and bloatware apps from the launcher giving a cleaner and more stock like appearance.

**Comment by RikKoedoot** [comment]
I like this idea, because some apps can't be disabled to hide them. Luckily I don't have bloatware (Moto)

**Comment by haderz98** [comment]
I know the Lawnchair Launcher by Deletescape has this feature but I much prefer this launcher as it is a lot cleaner and more like the Pixel Launcher.

**Comment by RikKoedoot** [comment]
Yeah, same opinion here

**Comment by amirzaidi** [comment]
> I know the Lawnchair Launcher by Deletescape has this feature but I much prefer this launcher as it is a lot cleaner and more like the Pixel Launcher.

And that is exactly why I don't want to include it. It's supposed to be 100% clean and adding any feature that's not in the Pixel Launcher feels like I'm ruining that cleanness feeling. You can disable apps using 'adb hide' on your PC if you suffer from bloatware.
