### ISSUE TITLE
Backport request: App shortcuts on Android 5 & 6

### ISSUE THREAD

**Issue by currall** [amirzaidi/Launcher3#73]
I think that a pixel style dock background on all lollipop phone and above would make the app even more realistic. Also app shortcuts would be very useful like Nova launcher. These features would make this app my favourite launcher.

**Comment by RikKoedoot** [comment]
Doesn't lollipop have frosted dock?

**Comment by rakshiths22** [comment]
Lolipop and also my moto g3 running marshmallow has no frosted dock.

**Comment by amirzaidi** [comment]
Try the latest Telegram test build please

**Comment by amirzaidi** [comment]
Done for Android 6.
