### ISSUE TITLE
Feature request: updates notification

### ISSUE THREAD

**Issue by valerionew** [amirzaidi/Launcher3#75]
Hi, 
I'm currently using this app as my daily driver launcher. Everything is fine, works perfectly. I just want to ask for a new feature.
It would be cool to receive a notification when an update for the launcher is available, or at least a "check for updates" button or something easier that checking manually on github. 
Will this be possible in the future? 
Thank you for your work!

**Comment by giacomocarrara** [comment]
A useful feature!

**Comment by TheOkayMan** [comment]
I second this request

**Comment by RikKoedoot** [comment]
That needs to be in the app

**Comment by VincentJoshuaET** [comment]
Follow Telegram/Subscribe/Star this project.

**Comment by RWOne** [comment]
Because rechecking the repository is hard?

I believe Amir's time could be better spent than to code this.

**Comment by RWOne** [comment]
Yes, see Vincent's post above mine, just as easy ...

**Comment by valerionew** [comment]
> Because rechecking the repository is hard?

@RWOne updating my launcher should not be my daily concern, right? Given that the updates are frequent, it would be an useful feature. 
Moreover, this would be some very reusable code I think. 

> Follow Telegram/Subscribe/Star this project.

@VincentJoshuaET I'm not a developer, i'm not very often on github. It wouldn't be a better solution than checking the repository, sorry. What is the Telegram thing? I use telegram quite often, maybe that would be a better short term solution, if the author wants to meet our request in the future. 

Guys, different people have different needs. This one is something that I need. By the comments on my request it seems that I'm not the only one, so what is all this about? 
If the author has time to do this, some of us will appreciate. 
I'm not forcing Amir to write this code, i'm just asking for a possible future feature.

**Comment by RWOne** [comment]
Frequent?

Um, no, not lately, and getting a watch notification is just the same as if it were in the app....

**Comment by valerionew** [comment]
@RWOne In 11 days, since 1.0 was released on github, we are at version 1.5. 
That's what i call frequent updates.

**Comment by VincentJoshuaET** [comment]
I'm not a developer too, but it's not hard to just check GitHub like I do.

**Comment by Testato** [comment]
In 2017, for a mobile app, have an automatic update fearure is a must for an app.

+1 for this feature request

**Comment by mirakzen** [comment]
fail...
in 2017 mobile apps have updates via markets
and...
this is max clear pixel launcher but you want not appropriate functions in unfinished project...

**Comment by RWOne** [comment]
Way to go, alienate the dev ... AKZen.

You have no clue as to WHY this app can't be in the market, don't you?

Even though the major blogs explained this while praising what has been done here.

The fail is yours.

I'm done in this thread with the trolls, if there's a new upload I'll know about it from watching the repo, you know for ANY repo.

**Comment by valerionew** [comment]
> You have no clue as to WHY this app can't be in the market, don't you?

Yes i do. I cannot speak for the other people involved here, but I do know why this isn't on the play store. If this it's not going to. be temporary, at some point this feature will be almost mandatory. 

> I'm done in this thread 

Bye . Thank you for your contributuion. 

> with the trolls

People who have different needs than you aren't trolls. Please accept different views. 

> I'm not a developer too, but it's not hard to just check GitHub like I do.

@VincentJoshuaET as i've explained above, my daily concern shouldn't be checking github for my launcher updates. This feature will be mandatory if this launcher will continue to exist. Sooner or later it should be added, why not now (I mean, in the near future)

**Comment by giacomocarrara** [comment]
Stop Flaming please, this guy was just suggesting an improvement to never miss an update. It can be useful or not, but it is only a suggestion. Please

**Comment by fonix232** [comment]
Guys, calm down.

I think a built-in update function is not necessary when we have so many alternative app stores. I believe it *should* be possible to make this into a full blown launcher and publish it to e.g. F-Droid (since it is indeed FOSS software, but depends on non-FOSS stuff, also using a reverse engineered library is... Not really the best definition of FOSS).

But let's not forget that @amirzaidi himself stated that he does not intend this to be an everyday driver, it's more like a generic "tutorial" of sorts so other devs can implement GNow easily.

**Comment by amirzaidi** [comment]
There's a "Version" setting in the settings menu that will open the GitHub releases link now

**Comment by valerionew** [comment]
@amirzaidi thank you, i've just downloaded the new release!
