### ISSUE TITLE
1.5 - Google Now pane - "Failed to load cards"

### ISSUE THREAD

**Issue by orphetov** [amirzaidi/Launcher3#77]
This may or may not be related to issue 48.

Nexus 5X, Android 7.1.2, Build N2G47W.

Updated to 1.5 from 1.3. Cleared App Data. The Google Now pane displays "Failed to load cards". I've tried clearing the search storage (Settings > Apps > Google > Storage > Manage Space > Clear Google Search Data) which fixes the issue temporarily (Note that it will require you to re-configure Now settings as well as re-train the personal "OK, Google" voice recognition settings). The "Failed to load cards" error will appear again once exiting from Google Now and returning.

Rebooting does not help either.

**Comment by RWOne** [comment]
Update Google app if available. That was root cause in my case.

**Comment by orphetov** [comment]
Good catch. I was running the beta version of the Google app (7.4.21). Leaving the beta program and reverting to 7.3.26.21 fixed the issue. Thanks!

Marking closed.

**Comment by RWOne** [comment]
Orphetov, don't know if you'll see this after closing, but I'm on that beta with no issues.

In my case I believe it was happening during a server side switch on my account to give me search shortcuts, which I now have for my feed ...
