### ISSUE TITLE
App info when tap & hold?

### ISSUE THREAD

**Issue by RemusGrigorescu** [amirzaidi/Launcher3#78]
When you tap and hold an app on the home screen it gives you the usual options at the top, "remove" and "delete", but it's missing "app info" option.

**Comment by RemusGrigorescu** [comment]
I meant "uninstall" not "delete", but you get it

**Comment by RWOne** [comment]
Clear cache and data, then re-setup.

No issues here on stock Nexus 6, all three options available on a long press of a home screen app.

**Comment by RemusGrigorescu** [comment]
I tried, but got no results. I also uninstalled and installed the app back and still nothing. Version 1.5 on a stock Nexus 5X

**Comment by RWOne** [comment]
Will have to see what others with your phone have, after clearing the app data and resetting up I would believe that should have corrected it ...

**Comment by weatherstorm** [comment]
I have the Nexus 5x running stock 7.1.2 using version 1.5 of the app and it works for me.

![screenshot_20170624-012917](https://user-images.githubusercontent.com/22601363/27506741-e877ac62-587c-11e7-8c92-8b09ef913f06.png)

**Comment by cyberon** [comment]
Also not working on my stock 6P.

**Comment by jagomf** [comment]
Just installed 1.5 on a Nexuws 5x with Android 7.1.2 and I am only getting **Remove** and **Uninstall** options. No **App info** option.

UPDATE: Tried clearing cache, data, reinstalling, etc, but still no **App info** option.

**Comment by Abrima** [comment]
For those having this issue, all you need to do is enable Developer Options in the Settings app. It will for some reason appear, and it will disappear again if you disable the options.

**Comment by jagomf** [comment]
That worked! Thanks

**Comment by Abrima** [comment]
No problem :)

**Comment by RemusGrigorescu** [comment]
That solved the issue for me too, thanks.

**Comment by ravithoria** [comment]
No luck using developer option on Moto g4 plus 7.0

**Comment by RikKoedoot** [comment]
I have same phone, works for me

**Comment by amirzaidi** [comment]
Enable developer options and then clear the app's data, should work
