### ISSUE TITLE
Widgets resizing and not interacting

### ISSUE THREAD

**Issue by GabrielAlbq** [amirzaidi/Launcher3#8]
The launcher is not recognizing the correct widget 1X1, instead it recognizes as 2X2 or 2X1 so when I put it into the home it gets big and I cannot resize it. Could you look into that? Also i can't interact with any widget. Tried a lot of widgets and none of them seems to be interacting.

**Comment by amirzaidi** [comment]
I cannot reproduce this, please give me more info. Device, OS, DPI, screen size, what widgets are you testing.

**Comment by GabrielAlbq** [comment]
Galaxy Alpha, Android 5.0.2, in build.prop it says LCD density is 320, 4.7", clock by google,app cache cleaner, brightness, Samsung's flashlight, shazam, they are not interacting with touch. Clock by google and app cache cleaner they do have normal size but the rest, doesn't

**Comment by GabrielAlbq** [comment]
Any news?

**Comment by amirzaidi** [comment]
No, sorry but I've been working on other features. Once the Launcher is polished enough I'll see if I can figure out what's happening. Do you have a 4x4 or 5x5 grid?

**Comment by GabrielAlbq** [comment]
5X5, I don't think I could change that. Any widget that you place at homescreen you can interact with it?

**Comment by GabrielAlbq** [comment]
Installed update now, tested widgets interaction and it is working, now the only thing that remains is 1X1 widgets being recognized as 2X2 widget.
