### ISSUE TITLE
Set wallpaper by the google photos application does not give the option to set for the lock screen.

### ISSUE THREAD

**Issue by JamesBalbo** [amirzaidi/Launcher3#80]
When selecting an image to set as wallpaper by the google photos application it does not give the option to set also for the lock screen. In the other launchers it presents the option.

**Comment by RWOne** [comment]
Update Google wallpapers app.

I tested on my N6 using 1.1.1xxx, and after choosing the image I'm queried as to setting home, lock or both screens.

**Comment by JamesBalbo** [comment]
With the google wallpaper app it works. But with google photos no.
google photos directly apply it only on the screen background and not of the option to apply the lock screen, or both.

But launcher in the nova launcher and google now launcher this work correctly.

**Comment by JamesBalbo** [comment]
If I get the image directly from launcher3 and apply this also works well. I just reported it because in other lacunher it works. And this is not working.

**Comment by RikKoedoot** [comment]
Set a wallpaper for both lock and home screen, then set a photo from Google
photos as wallpaper, that should work!

**Comment by RWOne** [comment]
Retried with photos, same as you, only the home screen.

Not a deal breaker for me, but I'm sure the dev may check it out.

**Comment by RikKoedoot** [comment]
I think it's more on the Google photos fault then the launcher

**Comment by amirzaidi** [comment]
Install the Google Wallpapers app and use that - using it is actually forced in the regular Pixel Launcher.
