### ISSUE TITLE
Weather widget does not show (Nexus 5x)

### ISSUE THREAD

**Issue by ansubru** [amirzaidi/Launcher3#81]
I have turned on all the permissions for launcher3 yet the weather/calendar widget does not show me the latest location and/or weather.  Am I missing something?

**Comment by ansubru** [comment]
I forgot to mention, the system language is English (US)

**Comment by ansubru** [comment]
Well, the widget definitely works!! Just that I was very impatient :(... It takes around 15 minutes to update before the first use, at least that's what I noticed. Great work developer, this is definitely the best pixel'esque launcher available today!!! Expecting more great things from you mate!

**Comment by RikKoedoot** [comment]
The launcher permissions don't matter, the weather comes from the Google
app, if you reload Google now, it will show up
