### ISSUE TITLE
Feature request: animated clock

### ISSUE THREAD

**Issue by RikKoedoot** [amirzaidi/Launcher3#82]
http://theblerg.net/post/2017/6/24/android-o-will-see-the-introduction-of-an-animated-clock-icon-in-launchers

Just like action launcher now has, is it possible to get an animated clock? because it's already in the clock app (if you have the latest APK)

**Comment by cyberon** [comment]
I would love this.

**Comment by zefnathC** [comment]
Me to

**Comment by amirzaidi** [comment]
Added for Android 8+
