### ISSUE TITLE
Feature request: search bar

### ISSUE THREAD

**Issue by RikKoedoot** [amirzaidi/Launcher3#84]
I think it would be nice to have the full search bar that appeared on some phones with the pixel launcher, it is in the real one.
![google-pixel-launcher-](https://user-images.githubusercontent.com/29402532/27546931-88e72ace-5a94-11e7-90d6-00b592e67ee6.jpg)

**Comment by lxmcf** [comment]
Would like to second this, would be nice to have it as a toggle in the settings page.

**Comment by RikKoedoot** [comment]
I've asked him personally, he doesn't include the a/b testing features in his port
