### ISSUE TITLE
4 columns grid on Huawei Honor 8 in version 1.5

### ISSUE THREAD

**Issue by reunion89** [amirzaidi/Launcher3#85]
Hello.
I installed your launcher on my Huawei Honor 8 and i see 4 columns grid on home screen and dock bar. 
Can I make a grid like a pixel phone in one of the future releases?
Thanks
My phone: Android 7.0. EMUI 5.0
![-ljycmxvmta](https://user-images.githubusercontent.com/29713966/27554188-492c1292-5ab6-11e7-9213-37157f8b2b93.jpg)

**Comment by amirzaidi** [comment]
Lower your DPI. It's in developer options -> minimum display width. Increase that value until the icons are small enough to get 5.

**Comment by reunion89** [comment]
Wow! Thanks. It works.
