### ISSUE TITLE
I can't see the weather widget

### ISSUE THREAD

**Issue by adi5497** [amirzaidi/Launcher3#87]
I can't see the weather at home screen. I just can see the clock and date.

**Comment by 4n1r0n** [comment]
Same issue. Weather widget disappeared for some reason.
I noticed Google (Beta) updated at about the time weather disappeared, so maybe it's related?
 (currently at 7.6.9.21.arm64)

**Comment by tmasrour** [comment]
I'm also on Google beta (same version as your filipcourtois) and the weather widget displays correctly. 
(on Android 6.0.1)

**Comment by adi5497** [comment]
I have non-beta 7.4.21.21.arm and I can't see on Android 7.1.2

**Comment by amirzaidi** [comment]
- Enable Google Now and the weather inside of it
- Set location to High Accuracy
- Turn Location history on
- Refresh Google Now
- Wait 30 minutes

If this doesn't work report back.

**Comment by adi5497** [comment]
Nothing happend. Still not working

**Comment by ndrychak** [comment]
@amirzaidi , thanks! Finally it works!
go to Google Now -> Customize -> Everything else -> Enable all weather options here

Nexus 5X. Android 8 beta

**Comment by adi5497** [comment]
@gontierUA, I had all these options turned on and widget is still not working

**Comment by ghost** [comment]
Just like filipcourtois stated after google beta app updated to version 7.6.9.21 Arm64  My 5X running Android 8.0  also lost the weather tried everything... still no weather    :(

**Comment by 4n1r0n** [comment]
Unfortunately problem remains.

**Comment by lambonyx** [comment]
"Issue Fixed"
the issue was related to the last update of Google beta version 7.6.9.21 as montioned by "ljfnky" above.
the fix:
1- go to your google play app
2- look for Google beta 
3- scroll down and opt-out of the Beta program
4- you'll have a note saying that it will take a few minute to restore the data...."ignore it"
5- go back to the top and tap uninstall "it's just the update"
6- go to your google home screen, log in again swipe down to refresh.
the weather widget should work as usual.

the Google beta app is exactly what you signed for it's experimental have new features and new bugs...lol, wait a few days until they fix the issue and then you guys can go back to the beta.
have a good day/night !!

**Comment by adi5497** [comment]
@lambonyx, not working for me

**Comment by lambonyx** [comment]
@adi5497 are you on Google Beta on android O OPP3?

**Comment by adi5497** [comment]
@lambonyx, no, I'm using Google 7.4.21.21.arm on Android N 7.1.2

**Comment by lambonyx** [comment]
@adi5497 locate the google app in your app store, see if the update was done around the same day when the issue appeared!
if yes, uninstall the update and give it a shot with the same procedure as above.
if not, check the location settings, the customize section of your google now, if you have multiple google account on your phone do the same for each one.

**Comment by adi5497** [comment]
@lambonyx, I installed previous version of Google apk and still have problem

**Comment by lambonyx** [comment]
@adi5497 do you have any update pending for pixel launcher and are you using a google pixel or a nexus phone?

**Comment by adi5497** [comment]
@lambonyx, wait, google pixel or nexus? So if I have Motorola moto g2 i can't have this weather widget?

**Comment by lambonyx** [comment]
you can but it's not stable since you're installing from a 3rd party apk not from the store, make sure you have the latest apk installed for pixel launcher app and google app.
if you don't have a nexus/pixel phone there's no guarantee that the weather widget will work properly.

**Comment by 4n1r0n** [comment]
@lambonyx that fixed it. I already suspected it was the beta app.
I'm more than willing to wade through some bugs here and there, but i assumed it was usefull to know that there was a problem, that's why I posted about it :-)

**Comment by ghost** [comment]
I have two Nexus 5X's the one runs android 8.0 the other is on 7.1.2 both have the Google Beta app 7.6.9.21 arm64. The one running the 7.1.2 android version has the weather working the way it should, The other on 8.0 doesn't have weather working. Just to let you know, Hope this information helps

**Comment by ProfessorWoland** [comment]
Did you tried enabling location from status bar and then swipe do google page pull down to refresh and go back to home screen voila :)
