### ISSUE TITLE
Android O

### ISSUE THREAD

**Issue by madvinegar** [amirzaidi/Launcher3#88]
Please backport the android O lancher characteristics such as the notification badges and the app recommendations even for android 7.0.
I see that the latest edition of Lawnchair did this, but I prefer your launcher as it is close to stock pixel launcher.

**Comment by amirzaidi** [comment]
I will wait until the official O Launcher sources are out before I do that

**Comment by madvinegar** [comment]
Ok, seems fair. Let's hope that they will release it soon. Keep up the good work !

**Comment by Fadmaestro** [comment]
Keep up the goodwork man!

**Comment by nyancrimew** [comment]
@amirzaidi damn, your way of thinking is way more reasonable than mine :joy: :wink:
