### ISSUE TITLE
App shortcuts

### ISSUE THREAD

**Issue by saiakhil8** [amirzaidi/Launcher3#9]
It would be great if u make app shortcuts into apps

**Comment by madvinegar** [comment]
It seems that this feature, is a feature of android 7.1 and later.
If you are on android 7.0 you will not be getting the app shortcuts. It is not a problem of the launcher.

**Comment by saiakhil8** [comment]
Im on 7.1.2 ...Nexus 6p

**Comment by madvinegar** [comment]
I have installed this launcher in my s4 mini with lineage 7.1.2 and I get the app shortcuts just fine.
Not all apps have shortcuts. Have you tried, for example, to long-press the playstore app?

**Comment by saiakhil8** [comment]
Even chrome not showing app shortcuts when using this launcher

**Comment by madvinegar** [comment]
try clearing cache and data, and try again.

**Comment by saiakhil8** [comment]
Got it working...App shortcuts only works if the launcher was set to default
