### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by cyberon** [amirzaidi/Launcher3#90]
I am having occasional lag accessing the feed and opening the drawer on my stock 6P, it didn't happen before, can you optimize the app a bit? I'm not interested in new features, only in a smooth experience.
Thanks in advance.

**Comment by amirzaidi** [comment]
Could you try the fallback 1.5 version? I've heard it doesn't have the lag. The issue seems to be the 'suggested apps' optimizer that runs in the background

**Comment by cyberon** [comment]
I have the "suggested apps" option disabled, but will try your suggestion and report back in a couple of days.

**Comment by amirzaidi** [comment]
Disabling it will just hide them but the logger is still running in the background. Tbh I should've never even imported the entire logging library, it's a hacky mess of a job

**Comment by cyberon** [comment]
The "lag" is still happening, don't know why... Is there a way for me to help finding the issue?

**Comment by amirzaidi** [comment]
Yes, note the exact timestamps when it happens (in seconds) and take a logcat with your computer. Send me the logcat and time and I'll take a look

**Comment by amirzaidi** [comment]
@cyberon I don't know if you are still reading this but if you are in the Google App beta you need to go back to stable, beta gives me stutters too
