### ISSUE TITLE
Icons disappearing on homescreen

### ISSUE THREAD

**Issue by MikeyMcG** [amirzaidi/Launcher3#94]
I've been using ver.1.3 for a couple of weeks now on my LG G6 and it is a real improvement over the stock launcher. But sometimes all the icons disappear from the homescreen. Swiping right for the Google feed still works, but swiping up for the app drawer doesn't work. I've tried swapping between launchers to see if it would perform a refresh, but only restarting the phone works. This happens randomly.

**Comment by amirzaidi** [comment]
Do you perhaps have a logcat? Could you try a force close if it happens again?

**Comment by ghost** [comment]
i really love this launcher. am on version 1.5. however, when i access it
on my apps, i have no option to unistall it. i dont want to uninstall it,
it just that am wondering how it became a system app and i havent rooted my
phone. am using UMI Touch. keep up the good work Amir. i love the google
now and stock android feel on my phone. is there any way you can make long
pressing home button launch google now screen scanning thingy? 😁

**Comment by amirzaidi** [comment]
@karanides It hasn't become a system app, but the default launcher can never be uninstalled. Set another launcher as your default and you'll be able to uninstall it. For the screen scanning thing you'll need to change your Assist app on your phone to the Google App. Go to your default apps and search for something about an Assist or Assistant app.

**Comment by ghost** [comment]
thanks so much

**Comment by AxiK101** [comment]
I noticed that after every reboot, if an app is installed/moved to external storage (microsd) then the desktop shortcut will disappear from the launcher. Is this normal to pixel launcher or just a bug of this mod version? It is not pushed as system (no root)

**Comment by neutralvibes** [comment]
I am finding that I have to recreate the same shortcut group after every reboot.

**Comment by Gurupatil228** [comment]
In My honor 6x now i am unable close the music widget and twin apps not showing in menu so please do something..

**Comment by amirzaidi** [comment]
Send me a screen recording of this issue @Gurupatil228
