### ISSUE TITLE
Sort orders of the recommended apps

### ISSUE THREAD

**Issue by daozhihun** [amirzaidi/Launcher3#95]
I think the orders of recommended apps are weird. Basically on Google Now Launcher the first line of apps are the apps I opened most, but in this launcher I don't understand how it works.

Also, I see you haven't updated the code for about a month, are you going to work on it in the furture?

Thanks.

**Comment by RikKoedoot** [comment]
He said to me he would work again when Android o is released

**Comment by daozhihun** [comment]
That's quite a long day. :)
But we could fork his work to build our own. Thanks Amirzaidi.

**Comment by RikKoedoot** [comment]
You can always try lawnchair, it has more customizability, and also some
Android o stuff.
