### ISSUE TITLE
Pixel Icons and Updates

### ISSUE THREAD

**Issue by briancork** [amirzaidi/Launcher3#98]
The phone icon does not match that found on my Pixel XL.

It's a nit-picky thing, but hoping for continuity.

That said, I appreciate your efforts as I am sure many others do as well.

**Comment by RikKoedoot** [comment]
Can you send a screenshot (I have the Moto dialer, so it  doesn't update,
maybe you also have a not Google phone app, and most don't have a round
icon because of that)

**Comment by briancork** [comment]
![img_20170723_145214](https://user-images.githubusercontent.com/30391419/28502032-84ec3e22-6fb7-11e7-89f6-ed35c87110bd.jpg)

**Comment by briancork** [comment]
I found APKs for the Google Contacts and Phone Apps. That helped.

How likely is it we can get the current Pixel look?

I have a HTC U11 by the way.  I was trying the Samsung S8. But, the HTC is more Pixel-like. While I have a Pixel XL I (like most Android Nation) want my cake and to eat is too.

**Comment by RikKoedoot** [comment]
yeah, it didnt have a round icon because htc doesnt use round icons, the
round icons only are enabled if there is a round icon in the app itself

**Comment by briancork** [comment]
Doesn't the OS dictate the shape of icons? I thought the whole point of the APK was to emulate the Pixel look on any device. I appreciate your efforts and abilities. But, can you explain? For example, how do we get the 7.1.2 Pixel round Phone App?

**Comment by RikKoedoot** [comment]
Yeah it is implemented that way in Android, but this launcher looks for if
any app has a round icon, then uses that instead of the default

**Comment by amirzaidi** [comment]
I will not include drawables in my app. Icon pack support is under consideration, but I do not want to include drawables for every OEM that decides not to support a round icon in their apps.
